### ISSUE TITLE
First run for SQL storage

### ISSUE THREAD

**Issue by YOzaz** [itsgoingd/clockwork#100]
Hey,

Few things:
* Please mention in docs, that config file should be republished, or amended with details for SQL storage.
* On first run with SQL storage enabled, Exception is thrown:
```php
// SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.clockwork' doesn't exist
if ($this->pdo->query("SELECT 1 FROM {$this->table} LIMIT 1") !== false) {
```
You need to wrap it into `try-catch` for Laravel, as default setting for warnings is to terminate application.

**Comment by itsgoingd** [comment]
Hey, thanks for the bug report! I've fixed the initialisation code and tagged a new release 1.8.1, please give it a try.

I've also added a note about the config file republishing to the changelog, unfortunately I have no better way to let users know atm. It will eventually be the default storage option, but that has to wait for 2.0 as it might be a breaking change for some users.

**Comment by YOzaz** [comment]
Thanks!
