### ISSUE TITLE
Laravel 4.2 Class 'Illuminate\Routing\Controllers\Controller' not found

### ISSUE THREAD

**Issue by InstanceOfMichael** [itsgoingd/clockwork#101]
```
URL: http://example.com/__clockwork/1436910596.9393.959026893?_=1436909497547&last_notif_at=1436910590&user=66
Class 'Illuminate\Routing\Controllers\Controller' not found
File: /home/forge/example.com/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/Controllers/LegacyController.php
Line:6
```

This started happening recently, after clockwork has been working for a while. It seems to be looking for a class that's actually ``Illuminate\Routing\Controller``, not ``Illuminate\Routing\Controllers\Controller``. I stopped getting this error after I changed that line.

**Comment by itsgoingd** [comment]
Hey, please make sure you are running latest stable version of Clockwork (1.8.1).

**Comment by InstanceOfMichael** [comment]
I was on ``~1.7``, I made the change and I think it is working now.
