### ISSUE TITLE
Support for Lumen

### ISSUE THREAD

**Issue by dawiyo** [itsgoingd/clockwork#104]
Any possibility of creating a version that supports Lumen?

**Comment by matiux** [comment]
+1

**Comment by itsgoingd** [comment]
I've added experimental support for Lumen, [installation instructions in the readme](https://github.com/itsgoingd/clockwork#lumen).

Any help with testing this is greatly appreciated as I don't use Lumen for any project atm, though I don't recommend using the current version in production yet.

**Comment by dawiyo** [comment]
You're awesome. Thanks so much. I'll let you know if I run into any problems in Lumen.

**Comment by danherd** [comment]
I think I might have found an issue - it appears to be showing duplicate database queries if you enable Eloquent and no queries at all if you don't enable it.

**Comment by kylestev** [comment]
@danherd Yeah I see the double reporting as well.

I added a log in `Clockwork\DataSource\EloquentDataSource` and saw that it only logged the queries once, yet the queries show up in the chrome developer tools console twice.

```php
app('log')->debug($query . ' ran in ' . $time);
```

![image](https://cloud.githubusercontent.com/assets/819571/9427230/dce7417c-4925-11e5-9208-109500bee925.png)

----

It also seems like events don't work with the experimental support for Lumen.

**Comment by kylestev** [comment]
@danherd are you using github.com/dingo/api by any chance?

**Comment by kylestev** [comment]
Turns out this is an issue with [dingo/api](https://github.com/dingo/api).

**Comment by kylestev** [comment]
@jasonlewis patched the issue with Lumen's middleware: https://github.com/dingo/api/commit/1cd3bf97394366dff5c5b478f902a960fad77e12

I can confirm Clockwork now behaves as expected with Lumen as far as displaying queries twice.

**Comment by Zyles** [comment]
Using latest lumen (and HHVM if it makes a difference) I followed the installation instructions.

1. Installed with composer version "dev-master"
2. Registered middleware and service provider classes in app.php

Get error:
```
Fatal error: Class undefined: Clockwork\\Support\\Lumen\\ClockworkServiceProvider in 
/home/httpd/myapp/vendor/laravel/lumen-framework/src/Application.php on line 253
```

**Comment by itsgoingd** [comment]
@Zyles Hey, please use `1.x-dev` instead of `dev-master`.

**Comment by Zyles** [comment]
Ok that worked better. Found another issue tho.

When I set API_DEBUG=false I get this:

```
lumen.ERROR: exception 'ReflectionException' with message 'Class clockwork.support does not exist'
```

So I can't run the app without debug on.

**Comment by itsgoingd** [comment]
Lumen support now included in v1.9.

@Zyles Can't replicate this, can you possibly send me a demo project?

**Comment by 2010abinas** [comment]
@itsgoingd Is it supporting with lumen 5.4 because i did all the configuration that has mentioned in the link i am getting totally blank in inspect element.  [https://github.com/itsgoingd/clockwork#lumen](config)
Could you please help me if i have missed something.

**Comment by itsgoingd** [comment]
Hey, Lumen 5.4 is supported.

Check if your responses contain the `X-Clockwork` headers in the network tab of Chrome dev tools. You can also check if the Clockwork metadata is being collected, by default this will be in a form of json files in `storage/clockwork` dir.

Don't forget that by default Clockwork runs only when you have your `APP_DEBUG` set to `true` and the `.env` file is loaded.

**Comment by 2010abinas** [comment]
Thank you for your response.
yes, in network tab X-Clockwork is showing and APP_DEBUG is also true but i am not getting any object or queries in clockwork tab of Chrome inspect elements.

**Comment by itsgoingd** [comment]
What happens if you request `your.app/__clockwork/CLOCKWORK-ID` where `CLOCKWORK-ID` is the value of the `X-Clockwork-Id` header?
