### ISSUE TITLE
Timeline not showing event "boot" and "run"

### ISSUE THREAD

**Issue by sisve** [itsgoingd/clockwork#107]
The timeline does not show the events "boot" (Framework booting) and "run" (Framework running). This seems to be due to the ClockworkServiceProvider starts listening (calls `$this->app['...']->listenToEvents();` which registers callbacks for `app->booting`) in the boot method, which executes after booting callbacks has fired.

Moving those two `...->listenToEvents();` calls to the end of the register method seems to solve this.

**Comment by itsgoingd** [comment]
Fixed in v1.9.
