### ISSUE TITLE
any way to know which function dispatch query?

### ISSUE THREAD

**Issue by OmarMakled** [itsgoingd/clockwork#111]
any way to know which function dispatch query?

i mean within database tab wouldn't be good to add column to know function name class and line number etc  

![screen shot 2015-10-28 at 2 25 36 pm](https://cloud.githubusercontent.com/assets/3720473/10788500/a327d5c0-7d80-11e5-9b1f-9370eb1a46cb.png)

**Comment by itsgoingd** [comment]
Hey, thanks for the idea. It would definitively be useful, I'll look into it.

**Comment by itsgoingd** [comment]
And more than half a year later I finally deliver. Caller file name and line number and Eloquent model name are now available in the database tab in updates released today. :)

Thanks for the idea!
