### ISSUE TITLE
Clockwork not working when autoloading files in your composer.json file

### ISSUE THREAD

**Issue by bretterer** [itsgoingd/clockwork#113]
I have a new install of Laravel and my composer file, I have added in my require section the following.

```
"files": [
 "/path/to/package/vendor/autoload.php"
]
```

I am doing this as I have a package I am developing outside of a laravel install.  When I add this in, Clockwork stops working.  There are no errors that come up, it just, doesn't do show anything in the console.

**Comment by itsgoingd** [comment]
Hey, sorry I missed your issue, did you solve the problem?
