### ISSUE TITLE
Laravel 5.2 no longer supports $this->app['router']->before() / after() methods

### ISSUE THREAD

**Issue by jonphipps** [itsgoingd/clockwork#114]
https://github.com/itsgoingd/clockwork/blob/v1/Clockwork/DataSource/LaravelDataSource.php#L104
https://github.com/itsgoingd/clockwork/blob/v1/Clockwork/DataSource/LaravelDataSource.php#L109

These methods were deprecated in Laravel 5.1 and have been removed.

**Comment by itsgoingd** [comment]
Hey, thanks for letting me know!

I've added Laravel 5.2 support in `v1.x-dev` (https://github.com/itsgoingd/clockwork/commit/653d3cb6d664e89329cf34e486312d5f852de81c), I'll tag stable `1.10` version when Laravel 5.2 final is released.

**Comment by jonphipps** [comment]
Theoretically 5.2 was 'released' yesterday, but there have been 3 more releases today, so... magic :8ball: time. :-)

**Comment by itsgoingd** [comment]
Ah, I missed the announcement, I've tagged Clockwork `1.10` now, thanks for letting me know!
