### ISSUE TITLE
Class 'CI_Controller' not found error in a Laravel 5 application

### ISSUE THREAD

**Issue by strebl** [itsgoingd/clockwork#116]
Hi all,

I get a weird error:
`Class 'CI_Controller' not found in .../vendor/itsgoingd/clockwork/Clockwork/Support/CodeIgniter/Clockwork.php on line 10`

But I only get this error if I run my phpspec suite.

I'm using Laravel 5.1.28 (LTS) with PHP 7.

It would be nice if somebody can help me fix this error.

**Comment by itsgoingd** [comment]
Hey,

Are you using the Clockwork facade in your code?

This might happen if you are using the Clockwork facade with optimised Composer autoloader without registering it, which might be the case in unit tests.

**Comment by strebl** [comment]
I think that's the reason. Thanks for your help!
