### ISSUE TITLE
EloquentDataSource not logging queries in Laravel 5.2

### ISSUE THREAD

**Issue by sebastiandedeyne** [itsgoingd/clockwork#117]
Laravel 5.2 deprecated the `illuminate.query` event in favour of `Illuminate\Database\Events\QueryExecuted`, so queries aren't captures anymore. I'd be willing to write a PR for this, but not sure how to handle backwards compatibility here.

Ref. https://laravel.com/docs/master/upgrade#upgrade-5.2.0

**Comment by itsgoingd** [comment]
Hey,

I've tagged a new version `1.10.1` including a fix for this issue (https://github.com/itsgoingd/clockwork/commit/f14f8e91a34efd0d17e8350a1db5d436154bec87).

Thanks!
