### ISSUE TITLE
Issue in Lumen 5.2

### ISSUE THREAD

**Issue by lukeed** [itsgoingd/clockwork#119]
Lumen 5.2 was just released. Didn't follow it too closely, but Clockwork isn't liking it :'(

Fresh Lumen install + Clockwork

![screen shot 2016-01-11 at 12 57 24 pm](https://cloud.githubusercontent.com/assets/5855893/12246358/e021aad8-b862-11e5-8931-9bc87d8734ac.png)

**Comment by itsgoingd** [comment]
Hey,

I've added initial Lumen 5.2 support (https://github.com/itsgoingd/clockwork/commit/c0ebd8077e6ca843f1a781ad9453c07d1d7d313e) to `dev-v1`.

Controller names and routes are not currently collected as a required method was removed in Lumen 5.2, though it was re-added in the 5.2 branch, so it should work as soon as the next Lumen 5.2.x version is tagged.

I'll tag a new Clockwork version as soon as this is resolved. I'd appreciate any help with testing as I don't have any project using Lumen 5.2 atm.

Thanks!

**Comment by lukeed** [comment]
OK. How do I install this then? Sorry

I have:

```
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/itsgoingd/clockwork.git"
        }
    ],
    "require-dev": {
        "itsgoingd/clockwork": "dev-v1#c0ebd8077e6ca843f1a781ad9453c07d1d7d313e"
    }
```
And it won't resolve

**Comment by itsgoingd** [comment]
My bad, it's version `1.x-dev`, no need to specify custom repository entry.

**Comment by lukeed** [comment]
Thanks

**Comment by lukeed** [comment]
From what I can tell with my simple usage, it works great :ok_hand: -- Just like it used to.

Can't give it an extensive run-through, but will close this issue as the installation bit is resolved.
