### ISSUE TITLE
SQL related logs in Laravel (I get no database tab in clockwork)

### ISSUE THREAD

**Issue by pdiveris** [itsgoingd/clockwork#120]
Hi

I am not sure if this is an issue or it's just the way it is, should I be getting a 'database' tab in the clockwork view? At the moment I only get to see 'Request', 'Timeline', 'Cookies' and 'Session'. As per title this refers to a Laravel 5.1 application.

Thanks, PD

**Comment by itsgoingd** [comment]
Hey,

As long as you are using Eloquent or Laravel DB calls and have a default database set in `config/database.php` there should be a Database tab shown.

If you'd like to dig into the code, the Eloquent data collector is registered in [ClockworkServiceProvider](https://github.com/itsgoingd/clockwork/blob/v1/Clockwork/Support/Laravel/ClockworkServiceProvider.php#L79) if this helper function in [ClockworkSupport](https://github.com/itsgoingd/clockwork/blob/v1/Clockwork/Support/Laravel/ClockworkSupport.php#L135) returns true (we have default database set and clockwork is not set to filter database queries). The [EloquentDataSource](https://github.com/itsgoingd/clockwork/blob/v1/Clockwork/DataSource/EloquentDataSource.php#L44) uses the query event to catch and collect all executed queries.

**Comment by pdiveris** [comment]
Hey, sorry for late response. Yes that's true now, I had to clean all json files and reload. It's probably due to the fact that you need to click on the correct 'link' at the left to see the queries - with Debugbar you get a single output for the whole 'page'!

**Comment by shreyasx** [comment]
Hello,
I do not see the 'database' tab in the clockwork extension in Chrome either. Right now, no matter which link I select in the left bar of the extension, there's only one tab, called 'Performance'. Which json files did you clean, @pdiveris?

**Comment by jan-koupil** [comment]
> Hello,
> I do not see the 'database' tab in the clockwork extension in Chrome either. Right now, no matter which link I select in the left bar of the extension, there's only one tab, called 'Performance'. Which json files did you clean, @pdiveris?

Quite the same here - only performance tab in both Chrome and Firefox. I am using MySQL database and all queries are working. Have you found any solution?

**Comment by shreyasx** [comment]
Nah, I've made an issue here you can leave a thumbs-up.
https://github.com/itsgoingd/clockwork/issues/499

**Comment by trinketbox** [comment]
I occasionally get a database tab and with only 1 query to the sessions table. I've only seen all the tabs once, it's normally just performance. Could you tell us which json files to clean (and what that even means -sorry I'm a noob) to get this to work, please?

<img width="1730" alt="Screenshot 2021-06-23 at 12 09 31" src="https://user-images.githubusercontent.com/59660545/123087778-d43ef280-d41c-11eb-8aba-d3bd7733ac8c.png">
<img width="1725" alt="Screenshot 2021-06-23 at 12 08 34" src="https://user-images.githubusercontent.com/59660545/123087789-d6a14c80-d41c-11eb-9bfc-604679ad4b1f.png">
