### ISSUE TITLE
Can I use this with php 7?

### ISSUE THREAD

**Issue by namaljayathunga** [itsgoingd/clockwork#121]
Thank you very much itsgoingd for this package. Can I use this with php 7, because php 7 changed their exception handler.

**Comment by itsgoingd** [comment]
Hey, there should be no compatibility problems with Clockwork itself. I'm developing most of my apps on PHP 7 nowadays and I have yet to run into an issue with Clockwork.

**Comment by namaljayathunga** [comment]
Thanks @itsgoingd, I have a project on laravel 4.2, Some errors not show in logs.
