### ISSUE TITLE
No Database Tab using Doctrine in Laravel 5.2

### ISSUE THREAD

**Issue by morfin** [itsgoingd/clockwork#122]
I commented out the config lines for doctrine:

```
'additional_data_sources' => array(
		 'clockwork.doctrine' => function($app)
		 {

			 return new \Clockwork\DataSource\DoctrineDataSource($app['Doctrine\ORM\EntityManager'], $app['log']);
		 }
	),
```

I'm using http://www.laraveldoctrine.org 

Clockwork is working for Request, Timeline, Cookies, and Session.

Seems that the Doctrine Data Source is not correctly applied. What else can I check ?

Thanks.

**Comment by morfin** [comment]
I figured out that in order to get the Database tab, I need to run:
```
Clockwork::info('.......);
```
Somewhere in my code. If there's no Clockwork::info() call, I don't get the Database tab.

**Comment by itsgoingd** [comment]
Hey,

I think the problem is the main Clockwork class and the additional data sources are not instantiated until they are used for the first time and we are hooking into Doctrine in the data source constructor. That also explains why calling anything on `Clockwork` facade makes things work.

I'll try to push proper fix today or tomorrow. Thanks for the report!

**Comment by patrickbrouwers** [comment]
We have a `LaravelDoctrine\ORM\Loggers\ClockworkLogger` logger in laravel-doctrine. Just tested it with Laravel 5.2 and it works without having to call Clockwork::info(); 
However I seems to have issues with Lumen 5.2 (with 1.x-dev branch), nothing seems to be send to Clockwork. Will have to investigate further and try it on a clean Lumen installation tonight.

**Comment by itsgoingd** [comment]
Ah, I didn't know there is an "official" support in laravel-doctrine, that's pretty cool. I should remove the example with our custom Doctrine data source then and add a note about using the laravel-doctrine one.

**Comment by patrickbrouwers** [comment]
The reason that we have an "official" version is that it supports multiple connections and logs all queries, not only from the "default" em.

Wouldn't remove the example though, people might be using clockwork with other frameworks/components then laravel. But a note would be nice :)

**Comment by itsgoingd** [comment]
@morfin Can you please try if 1.11 fixes this?

@patrickbrouwers Yeah, this is great news for me as I'm not Doctrine user myself and the entire Doctrine data source is user contributed so I can't guarantee as high level of the code quality as I would like to. I've added a note to the readme and the config file example that using laravel-doctrine is the preferred way.

**Comment by patrickbrouwers** [comment]
@itsgoingd Awesome. Tested it with both Laravel and Lumen 5.2, works great!

**Comment by morfin** [comment]
Works Now. Good work!
