### ISSUE TITLE
Clockwork log enhancements

### ISSUE THREAD

**Issue by crissi** [itsgoingd/clockwork#126]
1. Add file and line to each log entry, shown in new columns or like one new column: "filename.php:22" , so If you are logging a lot of thing you can actually be sure where the thing is coming from

2. Make log able to take a second argument like console.log in browsers, with a context, and show it in the log as column.

`console.log(new Date, 'context')`

**Comment by itsgoingd** [comment]
Hey, thanks for the ideas!

I'll have to take a look at performance implications of collecting the file names, but it's definitively something i would like to have. As for the context argument, we already have it in the API but we never actually use it for whatever reason, I'll take a look at fixing that.

I would also like to improve logging of exceptions with a nice interactive stack trace and such.

**Comment by itsgoingd** [comment]
Both features now available in Clockwork and Clockwork Chrome updates released today. :)

Thanks for the ideas!
