### ISSUE TITLE
Invalid argument supplied for foreach() in SwiftPluginClockworkTimeline.php:65 when no TO address is set

### ISSUE THREAD

**Issue by marksecurelogin** [itsgoingd/clockwork#128]
This happens when a mail message is sent with only a BCC address and not a TO address.

Stack trace:
#0 .../vendor/itsgoingd/clockwork/Clockwork/Support/Swift/SwiftPluginClockworkTimeline.php(65): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Invalid argumen...', '...', 65, Array)
#1 .../vendor/itsgoingd/clockwork/Clockwork/Support/Swift/SwiftPluginClockworkTimeline.php(44): Clockwork\Support\Swift\SwiftPluginClockworkTimeline->addressToString(NULL)
#2 .../vendor/swiftmailer/swiftmailer/lib/classes/Swift/Events/SimpleEventDispatcher.php(152): Clockwork\Support\Swift\SwiftPluginClockworkTimeline->beforeSendPerformed(Object(Swift_Events_SendEvent))
#3 .../vendor/swiftmailer/swiftmailer/lib/classes/Swift/Events/SimpleEventDispatcher.php(132): Swift_Events_SimpleEventDispatcher->_bubble(Object(Swift_Events_SendEvent), 'beforeSendPerfo...')
#4 .../vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(155): Swift_Events_SimpleEventDispatcher->dispatchEvent(Object(Swift_Events_SendEvent), 'beforeSendPerfo...')
#5 .../vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(85): Swift_Transport_AbstractSmtpTransport->send(Object(Swift_Message), Array)
#6 /var/www/sl2/dev/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(395): Swift_Mailer->send(Object(Swift_Message), Array)
#7 .../vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(181): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
#8 .../vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(222): Illuminate\Mail\Mailer->send('user.emails.fir...', Array, Object(Closure))
...

**Comment by itsgoingd** [comment]
Thanks! Fixed in `v1.x-dev`.
