### ISSUE TITLE
use it with API

### ISSUE THREAD

**Issue by nnnikolay** [itsgoingd/clockwork#130]
Hi, could you please help me, how should I use it with an API ?

I've an API call, which I'd like to see in chrome developer toolbar tab. I've installed chrome extension, and install server-side component. I see files appearing in the `storage/clockwork` folder. I see their content via
http request `__clockwork/1461245111.8006.916565298`
But how can I start seeing them into the Chrome DT tab?

Thanks.

**Comment by itsgoingd** [comment]
Hey,

the Chrome extension shows only the requests from the browser (and associated ajax calls), if you have api requests coming from elsewhere you can use something like the [Clockwork CLI client](https://github.com/ptrofimov/clockwork-cli) on your server or query the data manually / write a custom UI, which is pretty easy when using the SQL Clockwork data storage.

**Comment by nnnikolay** [comment]
@itsgoingd thanks for tip, I've installed it globally, went to the folder with the project and run cli client but it did show anything :( 


<img width="699" alt="screenshot 2016-04-21 21 37 52" src="https://cloud.githubusercontent.com/assets/11268878/14721969/8adf004c-0809-11e6-9116-4f292e25170e.png">

what I'm doing wrong ?
