### ISSUE TITLE
Undefined variable: timeline

### ISSUE THREAD

**Issue by greenxd** [itsgoingd/clockwork#131]
exception 'ErrorException' with message 'Undefined variable: timeline' in vendor/itsgoingd/clockwork/Clockwork/DataSource/LaravelDataSource.php:105

FIX
$this->app['events']->listen('clockwork.controller.start', function() use($timeline) 
TO
$this->app['events']->listen('clockwork.controller.start', function()

**Comment by itsgoingd** [comment]
Hey, thanks for the report. Looks like you are running `dev-master` version of Clockwork, I'd strongly suggest using latest stable version (require `~1.11` in your `composer.json`) as master might not be stable at all times.
