### ISSUE TITLE
composer dump-autoload -o causes controller not found error

### ISSUE THREAD

**Issue by ozgurky** [itsgoingd/clockwork#132]
In a lumen application when i run composer `dump-autoload -o` clockwork throws CI_Controller not found error in clockwork\Clockwork\Support\CodeIgniter\Clockwork.php while without optimizing option there was no error.

By the way I think the problem is missing namespace because adding 

`namespace Clockwork\Support\CodeIgniter;`

code the mentioned file solves the problem.

**Comment by itsgoingd** [comment]
Hey, have you tried updating your Composer and Clockwork to the latest stable version? Are you using any custom autoload rules in your `composer.json` (can you share your `composer.json` if you are not sure) ?

I've just tried this with the latest Composer and Clockwork in a Lumen 5.2 project and I can run `dump-autoload -o` just fine.

**Comment by itsgoingd** [comment]
I've finally been able to reproduce this, should be fixed in `1.11.2` by switching to PSR-4 autoloading.

Please try running `composer update` and tell me if it fixes the issue for you.

**Comment by ozgurky** [comment]
I've updated my project with composer and now it's ok. Thanks for quick fixing!
