### ISSUE TITLE
Clockwork Chrome tab empty

### ISSUE THREAD

**Issue by Luddinus** [itsgoingd/clockwork#134]
Hi.

I'm running last versions of clockwork and laravel and the chrome tab is empty (no errors, no queries, nothing)

However, the log is saving fine.

What am I missing?

Thx.

**Comment by Luddinus** [comment]
up

**Comment by itsgoingd** [comment]
Hey, do the server responses contain the `X-Clockwork-Id` header? What happens when you try to load `http://your-site/__clockwork/HEADER_VALUE`?

**Comment by Luddinus** [comment]
@itsgoingd The headers are included.

When I try to load that url it give 404 error (I'm using wamp an the url is like localhost/mysite/__clockwork/HEADER_VALUE)

**Comment by itsgoingd** [comment]
This is where the Clockwork routes are registered - https://github.com/itsgoingd/clockwork/blob/v1/Clockwork/Support/Laravel/ClockworkServiceProvider.php#L30-L36 - you might want to check whether the Clockwork controller gets registered and executed (with a simple dd statement for example).

Do you have some catch-all route or middleware returning 404 setup? Where does the not-found exception originate?

The requests should also contain the `X-Clockwork-Path: mysite` header, since your app is not running in the root path, is that correct?

**Comment by Luddinus** [comment]
It's weird, the route is registered but it nevers executed the controller action

**Comment by Luddinus** [comment]
In Laravel 5.2 I register the middleware in App/Http/Kernel.php like this:

```php
protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,

        \Clockwork\Support\Laravel\ClockworkMiddleware::class
    ];
```

**Comment by gregrobson** [comment]
I just had this issue as well - route was working fine, but the extension was never calling it.

Works fine after I removed the extension and re-added it - not sure why that fixes it, but on re-installing it Chrome asks for certain permissions, have they changed?

**Comment by itsgoingd** [comment]
@Luddinus Take a look at `php artisan route:list` output. Does it include the `__clockwork` route? If they are not included you might need to regenerate route cache if you are using it.

@gregrobson That's very strange, there were some policy changes regarding privacy on Chrome web store, but nothing that should affect Clockwork working. I'll look into it.

**Comment by UksusoFF** [comment]
Maybe it's related #118?

**Comment by ninthspace** [comment]
I had to remove the extension, then quit Chrome, then re-install extension it to work. (Merely removing and re-installing had no affect).

**Comment by octoxan** [comment]
@itsgoingd I'm having the same issue where nothing shows up in the Chrome tab.

I'm guessing it is related to a weird 404 catch all I have at the bottom of my routes that fowards the 404 over to a Wordpress site on the same server.

```php
Route::get('{any}', function() {
    require_once env('WP_INDEX', 'localhost');
})->where('any', '.*');
```

Is there any way to still use Clockwork with this setup?

**Comment by itsgoingd** [comment]
@octoxan Hey, this shouldn't be a problem as long as you register the Clockwork service provider before your RouteServiceProvider in `config/app.php`. Also don't forget to regenerate routes cache if you are using that feature.

**Comment by octoxan** [comment]
@itsgoingd Oh nice, I'll move it above the RouteServiceProvider on Monday and let you know if that fixes it for me. Thanks man!

**Comment by yaykyle** [comment]
Had the same issue yesterday after doing a fresh Homestead install. Deleting/Quitting Chrome/Reinstalling extension fixed it for me. Hat tip @ninthspace
