### ISSUE TITLE
Lumen Undefined index: REQUEST_METHOD

### ISSUE THREAD

**Issue by imjohnbon** [itsgoingd/clockwork#135]
I get this error when I try to run my PHPUnit tests on a Lumen install:

lumen.ERROR: exception 'ErrorException' with message 'Undefined index: REQUEST_METHOD' in /root/vendor/itsgoingd/clockwork/Clockwork/DataSource/LumenDataSource.php:227

Any thoughts? Running latest Lumen and Clockwork.

**Comment by itsgoingd** [comment]
Hey, can you share a sample test triggering this error?

**Comment by imjohnbon** [comment]
@itsgoingd For me it's actually getting triggered even on the basic ExampleTest on Lumen:

https://github.com/laravel/lumen/blob/master/tests/ExampleTest.php

**Comment by itsgoingd** [comment]
Hey, should be fixed in `v1.x-dev`, can you please try it out?

**Comment by imjohnbon** [comment]
@itsgoingd Thanks! Seems to have fixed it. Appreciate your fast response. Will this be put into a non-dev release soon?

**Comment by itsgoingd** [comment]
Yep, I'm tagging a new release this week.

**Comment by imjohnbon** [comment]
Awesome, thanks again.
