### ISSUE TITLE
Show requests with exception/errors/db errors

### ISSUE THREAD

**Issue by crissi** [itsgoingd/clockwork#137]
Would be cool to be able to see failed requests.

Right now they are not showing up in the clockwork requests tab, at least for Laravel.

Would love to be able to see quieries of failed SQL calls also, because I often need to debug these.

**Comment by itsgoingd** [comment]
Hey, this should already work as expected, what Laravel and PHP version are you using?

Proper handling of fatal errors, eg. a parse error, requires PHP7. Also using the `dd` function would disable Clockwork for the request, as the script execution is halted right when executing that statement and Clockwork code is not ran at all.

**Comment by crissi** [comment]
Ahh I see, I am not using PHP 7, so that must be the problem.
