### ISSUE TITLE
Extend clockwork

### ISSUE THREAD

**Issue by Chi-teck** [itsgoingd/clockwork#14]
Regards, and thanks for being working on this.
 I want to extend the clockwork with custom tab from server side. Is that possible?

**Comment by itsgoingd** [comment]
Adding custom tabs is now possible with the new user-data api in Clockwork 3.0 - [blog post](https://underground.works/blog/clockwork-3.0-now-available) and [full changelog](https://underground.works/clockwork/changelog#content).
