### ISSUE TITLE
Clockwork is failing every artisan command.

### ISSUE THREAD

**Issue by rhberro** [itsgoingd/clockwork#141]
### Laravel

Laravel Framework version 5.2.45
### PHP

PHP 7.0.8-3ubuntu3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
- with Zend OPcache v7.0.8-3ubuntu3, Copyright (c) 1999-2016, by Zend Technologies
- with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
### Clockwork

itsgoingd/clockwork v1.12

I have done all of the necessary steps to install Clockwork, it successfully works. When I clone my project repository in another computer, it fails when I try to run any artisan command. This is the output:

```
[RuntimeException]
No supported encrypter found. The cipher and / or key length are invalid.
```

It is failing because I have no app key within my .env file, but that is exactly what I am trying to do.
#### What I have done.

Added these line of code in my config/app.php file.

```
'providers' => array(
    ...
    Clockwork\Support\Laravel\ClockworkServiceProvider::class,
);

'aliases' => array(
    ...
    'Clockwork' => Clockwork\Support\Laravel\Facade::class,
);
```

Added the middleware to my app/Http/Kernel.php file.

```
protected $middleware = [
    \Clockwork\Support\Laravel\ClockworkMiddleware::class,
    ...
]
```

And I also published the configuration file.

```
php artisan vendor:publish --provider='Clockwork\Support\Laravel\ClockworkServiceProvider'
```

What am I doing wrong? You can check the project repository [here](https://github.com/rhberro/japensouse).

**Comment by itsgoingd** [comment]
Hey, this is caused by one of the Clockwork runtime dependencies requiring a valid `APP_KEY` to be set in your `.env`. A simple workaround is to disable Clockwork and run `artisan key:generate`, once you have your `APP_KEY` set, everything should be fine.

Sorry for the inconvenience, I'll try to find a better way to handle this for the next release. Thanks for the detailed report!

**Comment by Bilal898** [comment]
how can clockwork be fully uninstalled?

**Comment by itsgoingd** [comment]
Hey, first remove the package itself

```sh
$ composer remove itsgoingd/clockwork
```

If your app uses config or routes cache, regenerate the caches with `php artisan config:cache` and `php artisan route:cache`.

Finally, remove the collected metadata in `storage/clockwork`.
