### ISSUE TITLE
How can I load .json log files after I've closed a tab back onto the Chrome Inspector / Dev tools?

### ISSUE THREAD

**Issue by racl101** [itsgoingd/clockwork#143]
I've been trying to figure out how to do this but I can't find a way.  I've tried dragging the .json file to the clockwork tab in the Chrome Inspector, I've tried just dragging the Json file to a Chrome tab but all it does is output raw JSON. 

I'm not sure how the .json files are intended to be used. 

I'm basically trying to load the same output / report within the Clockwork tab of the web browser as if I had actually loaded the web page that generated the report in the first place. 

Or are the .json files meant to be used differently?

**Comment by itsgoingd** [comment]
Hey, unfortunately this is not possible.

The metadata is kept indefinitely in case you want to further analyze it, though no tools to do so exist so far, unless you make your own.

There is a workaround you could use though, with [clockwork-web](https://github.com/itsgoingd/clockwork-web) you can view any request using the url `your.app/__clockwork/app?id=REQUEST_ID`, where the `REQUEST_ID` is the name of the json file.
