### ISSUE TITLE
Call to a member function quote() on null when batch inserting into model

### ISSUE THREAD

**Issue by Braunson** [itsgoingd/clockwork#147]
Running Laravel 4.2 (yes I know, it's a legacy project).

I'm taking a large result set from a model, then chunking (250 each chunk), then looping to insert it, it seems to get to the last insert (and successfully insert all of the users) but throws this error:

Note: I'm using the version `~1.12`

**File:** `/vendor/itsgoingd/clockwork/Clockwork/DataSource/EloquentDataSource.php`
**Line:** 116

```
Call to a member function quote() on null
````

**Comment by itsgoingd** [comment]
Hey, are you doing anything weird with the database system other than the standard Elquent/DB queries (or using some package that might do so)? Are you using multiple database connections?

Looks like the PDO instance on the Laravel database connection object gets unset for whatever reason.

I'm afraid the only way I can help you is if you manage to replicate this error in an empty Laravel project you could share. A simple test case using sqlite works fine for me, but there are way too many variables with different db drivers, multiple connections, etc.

You might also want to simply disable logging queries for requests that run very large amounts of queries as logging them can be very memory (and a bit less cpu) intensive. You can do so by adding following statements before the query-intensive part of the code:

```php
DB::disableQueryLog();
Event::forget('illuminate.query');
```

**Comment by Braunson** [comment]
Yes I have multiple connections (2), I'm connecting to the second connection which is on a remote server. I already disabled the query log with no change in error.

Adding `Event::forget('illuminate.query')` seems to have resolved this error, thanks!
