### ISSUE TITLE
Add Laravel 5.4 support

### ISSUE THREAD

**Issue by itsgoingd** [itsgoingd/clockwork#148]
Note to myself, a few tweaks will be needed, relevant changes:

**The illuminate.log Event**

The illuminate.log event is now an object based event using the  Illuminate\Log\Events\MessageLogged class.

Make sure to test everything and test Lumen too (if that's still a thing)!

**Comment by KKSzymanowski** [comment]
There are two more event changes that break Clockwork. In `Clockwork\DataSource\EloquentDataSource::listenToEvents()` there's this code:
```php
$this->eventDispatcher->listen('eloquent.booted: *', function($model) use($scope)
{
    $model->addGlobalScope($scope);
});
```

In 5.4, if a handler is registered for a *wildcard event*, the first argument is the event name and the second is the payload as an array. This code should be changed to:
```php
$this->eventDispatcher->listen('eloquent.booted: *', function($eventName, $payload) use($scope)
{
    $payload[0]->addGlobalScope($scope);
});
```

Second, in `Clockwork\DataSource\LaravelDataSource::listenToEvents`(shouldn't it be `listenForEvents`?), there's this piece:
```php
$this->app['events']->listen('composing:*', function($view) use($views, $that)
{
    $time = microtime(true);

    $views->addEvent(
        'view ' . $view->getName(),
        'Rendering a view',
        $time,
        $time,
        array(
            'name' => $view->getName(),
            'data' => $that->replaceUnserializable($view->getData())
        )
    );
});
```

Same procedure:
```php
$this->app['events']->listen('composing:*', function($eventName, $payload) use($views, $that)
{
    $view = $payload[0];
    
    $time = microtime(true);

    $views->addEvent(
        'view ' . $view->getName(),
        'Rendering a view',
        $time,
        $time,
        array(
            'name' => $view->getName(),
            'data' => $that->replaceUnserializable($view->getData())
        )
    );
});
```

Hope this helps.

**Comment by itsgoingd** [comment]
Thanks! I've just tagged a new version including full Laravel 5.4 compatibility.
