### ISSUE TITLE
artisan vendor:publish failing

### ISSUE THREAD

**Issue by cubitworx** [itsgoingd/clockwork#155]
I'm new to both Laravel and Clockwork so excuse me if I'm missing something.

Running the following command
```
php artisan vendor:publish --provider='Clockwork\Support\Laravel\ClockworkServiceProvider'
```
gives me an output message of `Nothing to publish for tag [].`.

Looking at the [docs for `artisan vendor:publish`](https://laravel.com/docs/5.4/packages#configuration) it states that the `publishes()` method should be called from the `boot()` method. Extract:
```
To allow your configuration files to be published, call the publishes method from the boot method of your service provider
```
However looking at the Clockwork code the `publishes()` method is instead called in the [ClockworkServiceProvider->register()](https://github.com/itsgoingd/clockwork/blob/fdbf1f4381a9e18c59bac80f15be5686daccbac4/Clockwork/Support/Laravel/ClockworkServiceProvider.php#L44) function

For now I can get around this by manually copying the `clockwork.php` config file into the config directory.

**Comment by itsgoingd** [comment]
Hey, works fine for me. Are you sure you didn't run the command before adding the service provider? Does it work now that you have Clockwork working?

**Comment by cubitworx** [comment]
Yes, it is working now. I didn't do any further investigation since I got it working with the workaround. I'm 99% sure I followed the instructions exactly as they are in the readme.md

If you say it's working for you then it must have been something I was doing wrong - it was more a bug report than needing help ;)

Thanks for the quick follow up!
