### ISSUE TITLE
Tests fail when ClockWork added to middleware

### ISSUE THREAD

**Issue by sunscreem** [itsgoingd/clockwork#157]
I feel like I'm missing something obvious. As soon as I add 

`\Clockwork\Support\Laravel\ClockworkMiddleware::class` to my kernel (in 5.4), everything works nicely in the browser (including clockwork itself), but all my tests fail.

Any suggestions? It's like it's preventing the migrations from running.

**Comment by itsgoingd** [comment]
Hey, can you post a simple example test and what is the expected vs actual behavior you are getting?

**Comment by sunscreem** [comment]
Sure - I've been following along with Jeff Way's latest course so here's the [repo with the exact code](https://github.com/laracasts/Lets-Build-a-Forum-in-Laravel/tree/47f3c7793e0bc6fb08b90c420cbc10e749f8dd09).

The only difference is that he chose to use LaravelDebugBar instead. So, if you pull that code base in, you'll need to comment that class out in AppServiceProvider.php. If you then run the tests you'll see its all green.

If you then go ahead and add the `\Clockwork\Support\Laravel\ClockworkMiddleware::class` to the  `$middleware` in kernel.php, you'll see the tests all fail. 

The migrations, in the tests, never run so all the errors will be because he's calling for `Channels` in the AppServiceProviders boot method.

Hoping that all makes sense?

**Comment by itsgoingd** [comment]
Hey, I assume you've simply changed the DebugBar provider in `AppServiceProvider` for a Clockwork one?

This will lead to a crash in a non-local environment (eg. testing environment) as the Clockwork middleware requires services from the service provider and middleware specified in your `Http\Kernel` are executed in all environments.

You can fix this either by registering the middleware conditionally for local environment as well, in your `AppServiceProvider`:

```php
use Illuminate\Contracts\Http\Kernel;

...

    public function register()
    {
        if ($this->app->isLocal()) {
            $this->app->register(\Clockwork\Support\Laravel\ClockworkServiceProvider::class);
            $this->app[Kernel::class]->prependMiddleware(\Clockwork\Support\Laravel\ClockworkMiddleware::class);
        }
    }
```

Or you can simply register the service provider in your `config/app.php` like you'd normally do. Clockwork is by default active only if your app is in the debug mode, so you don't have to be afraid of exposing debugging information in production.

**Comment by sunscreem** [comment]
SORTED!

Thank you Sir.

As you might have guessed here's what I had in that register method:

```
    if ($this->app->isLocal()) {
          $this->app->register(\Clockwork\Support\Laravel\ClockworkServiceProvider::class);
     }
```

That's it all working perfectly now. Thank you for your time. V appreciated :)
