### ISSUE TITLE
Not showing SQL values when using ODBC driver

### ISSUE THREAD

**Issue by abhimanyu003** [itsgoingd/clockwork#158]
I'm using Laravel 5.3 with ODBC driver and sqlserver connection but somehow clockwork is not show the values that are passed in the SQL quires.

I'm attaching screenshot from chrome extension about the current situation.

You can see both ` "ticket_user_id" = and "password" = and` are blanks ?

![image](https://cloud.githubusercontent.com/assets/265913/25391732/840947a6-29f4-11e7-9a60-607a98fce9bd.png)

**Comment by itsgoingd** [comment]
Hey, unfortunately I don't have a Windows php installation available atm, so I can't replicate this myself.

If you'd like to help tracking down the issue, this is where the query shown in Clockwork is created -  https://github.com/itsgoingd/clockwork/blob/v1/Clockwork/DataSource/EloquentDataSource.php#L114-L137 - we should check what is passed as `$query` and `$bindings` to this function in your setup.

You can log contents of these variables into laravel log like this:

```php
	protected function createRunnableQuery($query, $bindings, $connection)
	{
		logger(print_r($query, true));
		logger(print_r($bindings, true));
		...
```

Then check the application log for the logged values.

Thanks!

**Comment by abhimanyu003** [comment]
Hello @itsgoingd I logged the results.

Log looks like this

```
[2017-04-26 11:38:46] local.DEBUG: select top 1 * from "test"."dbo"."ticket_users_v" where "ticket_user_id" = ? and "password" = ? and "inactive" = ? and "cannot_login" = ?  
[2017-04-26 11:38:46] local.DEBUG: Array
(
    [0] => username
    [1] => 202199986201188203836
    [2] => 0
    [3] => 0
)
```

**Comment by itsgoingd** [comment]
Hey, can you please add some additional log calls:

- $bindings at line 118 just after the prepareBindings call
- $binding at line 121 just after the quote call

Looks like one of these calls turns your bindings into nulls or empty strings.

You can also log the partially built $query at line 126 just after the preg_replace.

**Comment by abhimanyu003** [comment]
@itsgoingd This line is giving output as `false` 

https://github.com/itsgoingd/clockwork/blob/v1/Clockwork/DataSource/EloquentDataSource.php#L120

above this line, everything is fine.

Please let me know further.

**Comment by itsgoingd** [comment]
Welp, turns out the PDO_ODBC driver doesn't support quote at all according to PHP manual (http://php.net/manual/en/pdo.quote.php).

I'm not yet sure how I want to handle this in Clockwork.

As a workaround you could extend that data source class and replace the `createRunnableQuery` method with a version that doesn't do quoting by simply removing that single line (or write a custom method that does quoting for your database).

You can then register your customized database data source by adding the following call to your `AppServiceProvider`:

```php
public function boot()
{
    app('clockwork')->addDataSource(new FixedEloquentDataSource(app('db'), app('events')));
}
```

To avoid registering the original database data source you can publish the Clockwork config file and add `databaseQueries` to the filtered data array.

**Comment by itsgoingd** [comment]
@abhimanyu003 Hey, I've added a workaround for this issue, can you please try out dev-master version of Clockwork and let me know if it works for you? Thanks.

**Comment by abhimanyu003** [comment]
I checked with the latest version `1.14` but still getting same. It's not showing values.

**Comment by itsgoingd** [comment]
@abhimanyu003 Can you please share your `config/database.php`? Don't forget to remove your login and hostname.

**Comment by abhimanyu003** [comment]
@itsgoingd It's working ok with latest updates, but what I have to update

https://github.com/itsgoingd/clockwork/blob/v1/Clockwork/DataSource/EloquentDataSource.php#L146

```
if ($connection->getConfig('odbc') === true) {
```

to 


```
if ($connection->getPdo()->getAttribute(\PDO::ATTR_DRIVER_NAME) === 'odbc') {
```

What's your thought on this. ?

Thanks

**Comment by itsgoingd** [comment]
Hey, I think that's actually a better way to check for odbc, do you want to make it into a PR? :)

**Comment by abhimanyu003** [comment]
:+1:
