### ISSUE TITLE
Class clockwork.support does not exist

### ISSUE THREAD

**Issue by naseefpv** [itsgoingd/clockwork#163]
hi,
I'm using Laravel 5.4 for my project. i'm getting an error like  "Class clockwork.support does not exist" when middleware is added. 
Thank you

**Comment by itsgoingd** [comment]
Hey, did you add the service provider as well?

**Comment by naseefpv** [comment]
yes, i have added everything correct as you suggested. but still getting the above error.

**Comment by gjanz** [comment]
Also getting this in a project upgraded from laravel 5.3.

**Comment by hemantnarang33** [comment]
I resolved it by clearing cache for the config
execute this command
`php artisan config:clear`

**Comment by naseefpv** [comment]
@hemantnarang33 
Thank you so much. Issue solved after clearing config cache.
i executed this command
`php artisan config:clear`
