### ISSUE TITLE
laravel 5.2 nothing shows up in chrome

### ISSUE THREAD

**Issue by w3ion** [itsgoingd/clockwork#169]
Hi.

I'm running Laravel 5.2 and chrome clockwork extension, I ve follow the instalation steps, but the chrome tab is empty (no errors, no queries, nothing)

What am I missing?

Thx.

**Comment by itsgoingd** [comment]
Hey, check if the server responses contain the `X-Clockwork-Id` header in the network Dev Tools tab.

What happens when you try to load `http://your-site/__clockwork/X-CLOCKWORK-ID-VALUE` ?

**Comment by sunscreem** [comment]
If you are using route caching you need to clear that cache to enable clockwork. Caught me out a few times.
