### ISSUE TITLE
Returning Queries which are Cached

### ISSUE THREAD

**Issue by GeorgeHanson** [itsgoingd/clockwork#179]
Currently using Laravel 5.4, I have an eloquent query which is executed and cached in Redis. In my controller I then return this to the front end. 

However, in the Clockwork tab in Chrome, it is showing me that queries have executed when it has retrieved the cached version of the results - I know it is definitely caching it as I have used Laravel's Query Log to confirm that nothing is being executed.

Has anyone else come across this or has any ideas on how to solve this issue?

Thanks

**Comment by itsgoingd** [comment]
Hey, can you share a code snippet from your controller so I can see how are you interacting with the cache?

**Comment by GeorgeHanson** [comment]
Sure

`
return cache()->remember('posts', 60, function () {
        return Post::with('author')->all();
});
`

**Comment by itsgoingd** [comment]
Looks fine to me, if the cache is hit, the closure is not executed at all, so there is no way Clockwork would be able to know about those queries. 

You can see that by adding a simple dd call in the closure, if the data comes from the cache, your app won't be stopped. Are you sure you are not running with an array cache driver locally or something like that?

**Comment by GeorgeHanson** [comment]
That's what I thought, I'm currently using Redis for caching. I'm going to try set up a blank dummy project to test in a separate environment and application - then I should know if it is just my implementation; I will update in due course

**Comment by GeorgeHanson** [comment]
Update on this, it appears to be something to do with my environment - sorry about that. I have a dummy project I have created which works as intended.
