### ISSUE TITLE
Version column type

### ISSUE THREAD

**Issue by YOzaz** [itsgoingd/clockwork#180]
Hi, changed config to "sql" storage - got this error:
```
clockwork SQLSTATE[01000]: Warning: 1265 Data truncated for column 'version' at row 1
```
From the log, it looks like it's inserting **version** value of '1.14.2' - where column type is _INT_.
Changed to _VARCHAR(50)_, works fine.

Laravel 5.4
MariaDB 10.1.24

**Comment by itsgoingd** [comment]
Hey, this is fixed in master (https://github.com/itsgoingd/clockwork/pull/177) and will be released in the next version.

The version field is not really important atm, so either ignoring the warning or changing the column type works.

**Comment by YOzaz** [comment]
OK, thanks!
