### ISSUE TITLE
No Data in Chrome

### ISSUE THREAD

**Issue by jm-mwi** [itsgoingd/clockwork#183]
I've added Clockwork to a Laravel 5.4 app. In the network tab I'm seeing...
```
X-Clockwork-Id:1500492935.5482.290411069
X-Clockwork-Version:1.14.2
X-Powered-By:PHP/7.1.6
```
...headers, but the Clockwork tab is unresponsive in terms of any visible data.

**Comment by mikeerickson** [comment]
Have you installed the Clockwork Chrome Extension

https://chrome.google.com/webstore/detail/clockwork/dmggabnehkmmfmdffgajcflpdjlnoemp

**Comment by jm-mwi** [comment]
Yes

**Comment by itsgoingd** [comment]
Hey, what happens when you request `http://your.app/__clockwork/1500492935.5482.290411069` ?

**Comment by jm-mwi** [comment]
I'm getting the Laravel 404 page when I try to navigate to that.

`http://localhost:8000/__clockwork/1500495557.9008.1622051062`

```
X-Clockwork-Id:1500495557.9008.1622051062
X-Clockwork-Version:1.14.2
X-Powered-By:PHP/7.1.6
```

**Comment by jm-mwi** [comment]
.......Found it........

I had my routes cached. As soon as those were clear it fired right up. Sorry for the issue!

**Comment by itsgoingd** [comment]
My bad, I'll update the documentation to mention the need to regenerate the route cache.

**Comment by jm-mwi** [comment]
That would be awesome! The 404 and talking to another dev reminded me I had cached the routes a while back!
