### ISSUE TITLE
Not seeing anything in Chrome Clockwork tab - Laravel 5.4

### ISSUE THREAD

**Issue by adrianR84** [itsgoingd/clockwork#184]
Hello

I'm running Laravel 5.4 and chrome clockwork extension, done all the instalation steps, but I am not seeing anything in the Clockwork Chrome tab (no errors, no queries, nothing). The page response has two Clockwork headers, X-Clockwork-Id:1501139416.7054.1362315838 and X-Clockwork-Version:1.14.2. Also, logs are created in storage/app/clockwork folder. Also, when running "php artisan vendor:publish --provider='Clockwork\Support\Laravel\ClockworkServiceProvider'" there is not config file for clockwork.

Please help

Thank you.

**Comment by adrianR84** [comment]
I have found the problem, I had a route that was catching all the routes that were undefined... that was the problem.

**Comment by itsgoingd** [comment]
Can't reproduce this, please reopen if it's still an issue.
