### ISSUE TITLE
Class 'Clockwork\Support\Laravel\ClockworkServiceProvider' not found

### ISSUE THREAD

**Issue by beldr** [itsgoingd/clockwork#186]
I have followed all steps, and added the lines to composer.json, config/app.php and app/Http/Kernel.php, but every time I try to load any page it just says Class 'Clockwork\Support\Laravel\ClockworkServiceProvider' not found. There is something else I need to do or what is happening?

**Comment by itsgoingd** [comment]
Hey, have you actually run `composer update`? Can you see the Clockwork src in `vendor/itsgoingd`?

**Comment by waqasraza123** [comment]
installing clockwork was a nightmare, was unable to use it and now unable to remove it.
