### ISSUE TITLE
Is it possible to log memory usage and peak memory usage?

### ISSUE THREAD

**Issue by wwulfric** [itsgoingd/clockwork#188]
I think it's quite necessary.

**Comment by itsgoingd** [comment]
Hey, we don't collect memory usage by default, though you can easily use the clock helper to log the memory usage, like this `clock(memory_get_usage())`, or even use standard Laravel logging methods.

This will show up in the Clockwork "log" tab with both timestamp and file + line where the logger was called, so you can track the memory usage through the script execution.

Does this work for you or do you have some other idea how this should work? :)

**Comment by wwulfric** [comment]
Yeah it helps a lot 👍
