### ISSUE TITLE
Replace usage of env() with config()

### ISSUE THREAD

**Issue by SunMar** [itsgoingd/clockwork#190]
Hi,

During a review I came across the following lines:

https://github.com/itsgoingd/clockwork/blob/60a17e85a7f24b0161da906ab184d75ab4dceb41/Clockwork/Support/Lumen/ClockworkSupport.php#L28

https://github.com/itsgoingd/clockwork/blob/60a17e85a7f24b0161da906ab184d75ab4dceb41/Clockwork/Support/Lumen/ClockworkSupport.php#L122

Shouldn't any configuration be in a configuration in config/clockwork.php and then the config() helper used to check values. It's good practise to only use the env() helper inside config/ files and not in the application itself. Also env() can be protected in production and not return anything except when used inside the config/ scope (Clockwork is of course not something to be used in production but that shouldn't deter from doing good practise). Also for checking APP_DEBUG in general shouldn't config('app.debug') be used anyways to check for debug mode?

Not sure if this is a real issue, as I'm not a Lumen user (I'm using the full Laravel framework), it's just something that I noticed while I was doing a review of env() usage in my application.

Regards,

SunMar.

**Comment by SunMar** [comment]
I also looked at the Laravel class and there the app config is used, though access through $this->app['config'] (which may actually be better than using the helper() when writing unit tests). There's also a third method which is using the Config facade, then you can access configuration settings through Config::get() but that requires that the facade hasn't been renamed or removed which might not be a nice thing to trust as an external package.

https://github.com/itsgoingd/clockwork/blob/v1/Clockwork/Support/Laravel/ClockworkSupport.php#L27-L40
https://github.com/itsgoingd/clockwork/blob/v1/Clockwork/Support/Laravel/ClockworkSupport.php#L127

**Comment by itsgoingd** [comment]
Hey, this is indeed the case in Laravel, but I’m not so sure about Lumen.

I believe the only user-facing configuration in Lumen apps are supposed to be env variables. While Lumen does support loading configuration files, I believe this is mostly for compatibility with existing Laravel packages, since the default Lumen project does not even have a config directory, nor does Lumen have the vendor:publish artisan command.

While we can add a config file for Lumen I don’t really see the benefit of doing so, since it would only be used internally.

That being said, I’m not Lumen user myself, so any input of actual Lumen users on this is appreciated. :)

**Comment by davoaust** [comment]
I'd like to chime in on this one as I've just run into it being impossible to configure the filter in Lumen.  I'm specifically doing it to avoid storing cache queries.

It all stems from ClockworkSupport:getFilter() requiring an array but env() doesn't support them.
https://github.com/itsgoingd/clockwork/blob/3f9e9776dd549b726ae43ce2053e869aa4ebf391/Clockwork/Support/Lumen/ClockworkSupport.php#L87-L90

https://github.com/itsgoingd/clockwork/blob/3f9e9776dd549b726ae43ce2053e869aa4ebf391/Clockwork/Support/Lumen/ClockworkSupport.php#L24-L27

There's plenty of other packages that require config files for Lumen so I can't see any real reason to not use it.

**Comment by davoaust** [comment]
I've thrown a quick pull request together with the fix (directly lifted from the Laravel support file). I've tested it and it works perfectly.

I did accidentally close & have to reopen the request, apologies for any spam that caused.

**Comment by itsgoingd** [comment]
Implemented in Clockwork 2.1!
