### ISSUE TITLE
PHP environmental problems

### ISSUE THREAD

**Issue by RoseEnd** [itsgoingd/clockwork#193]
The PHP version of laravel5.5 requires 7, but the environmental requirements here are 7.1, in the hope of keeping in line with laravel's environmental requirements

**Comment by itsgoingd** [comment]
Hey, I’m not sure what is the problem. Current version of Clockwork works with any PHP version down to 5.3, next release will up this requirement to 5.4.

I think your problem might be running composer update on PHP 7.1 updating some of your packages to 7.0 incompatible versions, in that case you can explicitly specify your minimal required PHP version in your composer.json (https://getcomposer.org/doc/06-config.md#platform).

**Comment by RoseEnd** [comment]
It is ok now, thanks
