### ISSUE TITLE
v1.14.3 and v1.14.4 is not working on Laravel 4.2

### ISSUE THREAD

**Issue by bcalik** [itsgoingd/clockwork#195]
v1.14.3 and v1.14.4 is not working on my legacy Laravel 4.2 project.

I tried downgrading to v1.14.2 and its works again.

I don't know the reason.

**Comment by itsgoingd** [comment]
Hey, I've tagged a new release fixing the issue. Thanks for the report!

**Comment by bcalik** [comment]
I can confirm its working now! Thanks.
