### ISSUE TITLE
Phalcon Integration

### ISSUE THREAD

**Issue by ASalman** [itsgoingd/clockwork#196]
Hi 
is there any clear documentation how to integrate Clockwork with phalcon framework?

**Comment by itsgoingd** [comment]
Hey, I wrote a brief general guide on how to use Clockwork with vanilla php (or any framework/app really) on the [Clockwork website](https://underground.works/clockwork) (check the "vanilla php" section under "Installation").

The existing Laravel or Slim integrations might also serve as a good inspiration, the Slim2 integration is a [single middleware class](https://github.com/itsgoingd/clockwork/blob/v1/Clockwork/Support/Slim/ClockworkMiddleware.php).

Check it out and let me know if you need any help!
