### ISSUE TITLE
Not working in combination with Lumen and Dingo/Api

### ISSUE THREAD

**Issue by maesklaas** [itsgoingd/clockwork#197]
I am trying to get clockwork to work with lumen and dingo/api, but so far without success.

The tab in the chrome extensions stays empty, if i go to /_clockwork/HEADERID i get the following error, does someone has a clue what i'm missing?

`{"message":"404 Not Found","status_code":404,"debug":{"line":596,"file":"\/public_html\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php","class":"Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException","trace":["#0 \/public_html\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(533): Laravel\\Lumen\\Application->handleDispatcherResponse(Array)","#1 \/public_html\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(783): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}()","#2 \/public_html\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(535): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))","#3 \/public_html\/vendor\/dingo\/api\/src\/Routing\/Adapter\/Lumen.php(103): Laravel\\Lumen\\Application->dispatch(Object(Dingo\\Api\\Http\\Request))","#4 \/public_html\/vendor\/dingo\/api\/src\/Routing\/Router.php(513): Dingo\\Api\\Routing\\Adapter\\Lumen->dispatch(Object(Dingo\\Api\\Http\\Request), 'v1')","#5 \/public_html\/vendor\/dingo\/api\/src\/Http\/Middleware\/Request.php(126): Dingo\\Api\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))","#6 \/public_html\/vendor\/illuminate\/pipeline\/Pipeline.php(151): Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}(Object(Dingo\\Api\\Http\\Request))","#7 \/public_html\/app\/Http\/Middleware\/ApiIpMiddleware.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#8 \/public_html\/vendor\/illuminate\/pipeline\/Pipeline.php(137): App\\Http\\Middleware\\ApiIpMiddleware->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#9 \/public_html\/vendor\/nordsoftware\/lumen-cors\/src\/CorsMiddleware.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#10 \/public_html\/vendor\/illuminate\/pipeline\/Pipeline.php(137): Nord\\Lumen\\Cors\\CorsMiddleware->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#11 \/public_html\/vendor\/itsgoingd\/clockwork\/Clockwork\/Support\/Lumen\/ClockworkMiddleware.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#12 \/public_html\/vendor\/illuminate\/pipeline\/Pipeline.php(137): Clockwork\\Support\\Lumen\\ClockworkMiddleware->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#13 \/public_html\/vendor\/illuminate\/pipeline\/Pipeline.php(104): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#14 \/public_html\/vendor\/dingo\/api\/src\/Http\/Middleware\/Request.php(127): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#15 \/public_html\/vendor\/dingo\/api\/src\/Http\/Middleware\/Request.php(103): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))","#16 \/public_html\/vendor\/illuminate\/pipeline\/Pipeline.php(137): Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#17 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))","#18 \/public_html\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))","#19 \/public_html\/vendor\/illuminate\/pipeline\/Pipeline.php(104): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Illuminate\\Http\\Request))","#20 \/public_html\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(780): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#21 \/public_html\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(535): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))","#22 \/public_html\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(476): Laravel\\Lumen\\Application->dispatch(Object(Illuminate\\Http\\Request))","#23 \/public_html\/public\/index.php(28): Laravel\\Lumen\\Application->run(Object(Illuminate\\Http\\Request))","#24 {main}"]}}
`

**Comment by itsgoingd** [comment]
Hey, works fine for me with clean Lumen 5.1 and Dingo 1.0 install.

If you can share a sample project I'll take a closer look.

**Comment by maesklaas** [comment]
I created a sample project, Lumen 5.3 and Dingo 1.0
https://github.com/maesklaas/lumen-dingo-clockwork

**Comment by itsgoingd** [comment]
Hey, so I've looked into this and looks like this is a Dingo bug (or feature).

Dingo does some funky stuff with routing, including using a custom router, so you have to register your routes like

```php
$api = app('api.router');
$api->version('v1', function ($api) {
    $api->get('test', function () { ... }
}
```

In Laravel integration they also take all routes registered with the standard Laravel router (eg. using the `Route` facade) and [add them to their custom router before dispatching](https://github.com/dingo/api/blob/master/src/Routing/Adapter/Laravel.php#L75), which makes them work as expected.

The Lumen integration does no such thing.

Now this is not very obvious, since the default Lumen "root" route still works. In fact any simple route (with no dynamic parts) will work, but this is only thanks to a Lumen optimisation where [simple routes are matched via a simple isset call](https://github.com/laravel/lumen-framework/blob/5.5/src/Concerns/RoutesRequests.php#L159-L161) before even executing the dispatcher.

Simply copy-pasting the [route merging code from Laravel integration](https://github.com/dingo/api/blob/master/src/Routing/Adapter/Laravel.php#L95-L110) into the [Lumen integration](https://github.com/dingo/api/blob/master/src/Routing/Adapter/Lumen.php) and adjusting for the API differences fixes the problem.

Looks like this was [already reported](https://github.com/dingo/api/issues/997), but didn't get much attention, maybe with the information above this can now be fixed.

**Comment by maesklaas** [comment]
Great, you found what the problem is!
Did you create a working version locally?
If yes, would you be able to share it?

**Comment by itsgoingd** [comment]
I've already deleted the repo, but I believe fixed `vendor/dingo/api/src/Routing/Adapter/Lumen.php` looked like this - https://gist.github.com/itsgoingd/7f28f1690b037cb7734f25ce23528915

Try it out and feel free to PR the fix to the Dingo repo if it works for you.

**Comment by maesklaas** [comment]
Thanks, i got it to work!

I will create a PR to Dingo repo ;)

**Comment by itsgoingd** [comment]
Nice!
