### ISSUE TITLE
Undefined index: time

### ISSUE THREAD

**Issue by ddmo** [itsgoingd/clockwork#200]
Hi, with the last version I got frequently this error:

`
[2017-10-08 10:29:03] development.ERROR: Undefined index: time at /Users/stefanop/Sviluppo/Personale/gepe/laravel/vendor/itsgoingd/clockwork/Clockwork/Storage/FileStorage.php:102)
[stacktrace]
#0 /Users/stefanop/Sviluppo/Personale/gepe/laravel/vendor/itsgoingd/clockwork/Clockwork/Storage/FileStorage.php(102): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', '/Users/stefanop...', 102, Array)
#1 [internal function]: Clockwork\\Storage\\FileStorage->Clockwork\\Storage\\{closure}('1506869798.6420...')
#2 /Users/stefanop/Sviluppo/Personale/gepe/laravel/vendor/itsgoingd/clockwork/Clockwork/Storage/FileStorage.php(103): array_filter(Array, Object(Closure))
#3 /Users/stefanop/Sviluppo/Personale/gepe/laravel/vendor/itsgoingd/clockwork/Clockwork/Storage/FileStorage.php(90): Clockwork\\Storage\\FileStorage->cleanup()
#4 /Users/stefanop/Sviluppo/Personale/gepe/laravel/vendor/itsgoingd/clockwork/Clockwork/Clockwork.php(124): Clockwork\\Storage\\FileStorage->store(Object(Clockwork\\Request\\Request))
#5 /Users/stefanop/Sviluppo/Personale/gepe/laravel/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkSupport.php(123): Clockwork\\Clockwork->storeRequest()
#6 /Users/stefanop/Sviluppo/Personale/gepe/laravel/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkMiddleware.php(34): Clockwork\\Support\\Laravel\\ClockworkSupport->process(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\JsonResponse))
#7 /Users/stefanop/Sviluppo/Personale/gepe/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Clockwork\\Support\\Laravel\\ClockworkMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#8 /Users/stefanop/Sviluppo/Personale/gepe/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#9 /Users/stefanop/Sviluppo/Personale/gepe/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#10 /Users/stefanop/Sviluppo/Personale/gepe/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#11 /Users/stefanop/Sviluppo/Personale/gepe/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#12 /Users/stefanop/Sviluppo/Personale/gepe/laravel/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#13 {main}
"}
` 
Any idea?
Thanks

**Comment by itsgoingd** [comment]
Hey, have you tried updating to the latest version? This should be fixed in 2.0.3.

**Comment by ddmo** [comment]
Hi,I've 2.0.1 version... I will try to update. Thanks!
