### ISSUE TITLE
Vanilla PHP Installation instruction blow Fatal Errors

### ISSUE THREAD

**Issue by oxblue-rbollig** [itsgoingd/clockwork#201]
Just starting with Clockwork and walking through the Vanilla PHP installation instructions.  Running into some errors.

I'm getting `PHP Fatal error:  Uncaught Error: Call to protected method Clockwork\\Storage\\SqlStorage::initialize() from context '' `

I edited the code and changed that method from public to protected, then got `PHP Fatal error:  Uncaught Error: Call to undefined method Clockwork\\Storage\\SqlStorage::retrieve()` on the next attempt.

Operating on a fresh install of Ubuntu 16LTS, PHP 7.0.22 with Apache. Confirmed SQLite 3 library is installed.  CLI is also operational.  I also tried initializing the database file by creating a test table.

phpinfo, composer.lock and a copy of working space are attached.

Before I dive deep into it, is there something basic I might be missing?  Looks like some of these areas were committed September 15th - recently.

[composer.lock.txt](https://github.com/itsgoingd/clockwork/files/1403276/composer.lock.txt)
[clockwork-broken.zip](https://github.com/itsgoingd/clockwork/files/1403277/clockwork-broken.zip)
[phpinfo.txt](https://github.com/itsgoingd/clockwork/files/1403278/phpinfo.txt)

**Comment by itsgoingd** [comment]
Oops, forgot to update these for the 2.0 release:

- `initialize` should no longer be manually called
- `retrieve` was renamed to `find`

Also you might want to use the flat-file storage instead of Sqlite which is our default for all framework integrations as it's faster than Sqlite:

```php
$storage = Clockwork\Storage\FileStorage(__DIR__ . '/clockwork-data');
```

**Comment by oxblue-rbollig** [comment]
Perfect!  That fixes it.  

I see you updated the web site as well, so I think this issue is done.

Slick product!  Thanks!.
