### ISSUE TITLE
Laravel 5.5 some requests result in empty json files

### ISSUE THREAD

**Issue by jstenquist** [itsgoingd/clockwork#203]
I am attempting to upgrade Clockwork to 2.0.2 in our Laravel 5.5 app. Over 50% of the requests are resulting in empty .json files, which means over 50% of the returning data in the Chrome devtools tab is empty.

![image](https://user-images.githubusercontent.com/1971648/31904282-cb852252-b7f8-11e7-9cfe-3fd91d31b19b.png)

Laravel 5.5 with the old 1.x extension work fine.

Any ideas?

**Comment by itsgoingd** [comment]
Hey, it's possible that the collected data contain something that can't be serialized to JSON.

Are you aware of logging something that might be problematic? This also include queries, view data and emails if you have these enabled, I've seen similar behavior when sending emails with attachments.

Can you try adding `info(json_last_error_msg())` just below [this line](https://github.com/itsgoingd/clockwork/blob/master/Clockwork/Request/Request.php#L219) and see if it logs any errors? (Don't forget to also move the return statement.)

I'll take a look if we can make the serialization process more error-proof, you can use the 1.x version in the meantime which is still supported.

**Comment by sergio91pt** [comment]
I traced the issue to the json_encode in FileStorage#store, since that Request method wasn't called.
The problem, in my case, is that I use binary ids (optimized uuid's), so json_encode fails with malformed utf-8.

**Comment by sergio91pt** [comment]
A possible fix to my specific problem is to detect when PDO params are binary (invalid utf-8) and use the hexadecimal representation instead:

Adding:
```php
        if (!mb_check_encoding($binding, 'utf-8')) {
            return "x'" . bin2hex($binding) . "'";
        }
```
at the beginning of the [EloquentDataSource#quoteBinding](https://github.com/itsgoingd/clockwork/blob/172f1f68b4d095e1514c817e4c19a3f4ccc86131/Clockwork/DataSource/EloquentDataSource.php#L140) method, since I'm using Laravel.

**Comment by itsgoingd** [comment]
Hey, I'll be working on serialization improvements for the next release. This will certainly come in handy, thanks!

**Comment by itsgoingd** [comment]
Some metadata handling improvements have been implemented in Clockwork 2.1, let me know if this helps!

Will still look into more things for 3.0, including support for binary query bindings.

**Comment by coderNeos** [comment]
Hi. I'm having exactly the same issues, but with queries log in clockwork app. I think that it would be nice to convert binary bindings to hex representation.

**Here is the example.**

One query has binary bindings and other does not.

![query](https://user-images.githubusercontent.com/25342358/40781044-0e47ea86-650d-11e8-8e8d-9a970bc0ec10.png)

**Comment by itsgoingd** [comment]
Added to 3.0 todo list.

**Comment by itsgoingd** [comment]
Binary bindings are now handled in Clockwork 3.0 - [blog post](https://underground.works/blog/clockwork-3.0-now-available) and [full changelog](https://underground.works/clockwork/changelog#content).
