### ISSUE TITLE
Enable or disable

### ISSUE THREAD

**Issue by vyuldashev** [itsgoingd/clockwork#204]
Hello,

Can I disable or enable Clockwork in middleware or controller? In my case, I only want enable it for specific users only

**Comment by itsgoingd** [comment]
Hey, you can set `config([ 'clockwork.enable' => false ])`, this will cause Clockwork middleware to return early, so the metadata will not be saved and the headers won't be appended to the response.

Note that Clockwork routes will still be registered and data collected (just not saved), if you would want to completely remove Clockwork for certain requests, you would need to disable auto-discovery and conditionally register the Clockwork service provider or make the config call before the Clockwork service provider is executed.
