### ISSUE TITLE
Postman native app

### ISSUE THREAD

**Issue by abhimanyu003** [itsgoingd/clockwork#205]
Is there any way to integrate clockwork with postman native app. Postman support extension using npm may be we can use that.

Chrome apps are no longer supported and Google is also planning to shut them down.
http://blog.getpostman.com/2017/03/14/going-native/

I tried running debug console in the native app but it by pressing CTRL + ALT + J but it is not logging request and postman console do not give clockwork tab.

Please let us know.
Thanks

**Comment by itsgoingd** [comment]
Hey, with Clockwork 2.0 you can use the web UI available at `http://your.app/__clockwork`, this will show all requests even those executed outside of the browser.

**Comment by abhimanyu003** [comment]
Just updated to clockwork 2.0 and it's working good :+1:
