### ISSUE TITLE
Only see Request, Timeline and Session -- Version 2.0

### ISSUE THREAD

**Issue by mfour-merickson** [itsgoingd/clockwork#207]
Curious, why only 3 of panes appear?  There are much more in your screenshot, and most importantly for me "Logs" is missing.

![image](https://user-images.githubusercontent.com/31225533/32126748-29e318f0-bb27-11e7-93ae-a5c299fbd368.png)

**Comment by itsgoingd** [comment]
Hey, did you actually try to log something? The tabs appear only if they have something to show.

Also I've noticed the icons don't render correctly for you, is this web UI? What kind of stack are you running?

**Comment by mfour-merickson** [comment]
Ya, found the issue with the logging (I had two routes with same endpoint /test)

With regards to the icons, the above is the webview, the debugger view shows the icons.
