### ISSUE TITLE
Webview is not showing icons 

### ISSUE THREAD

**Issue by mfour-merickson** [itsgoingd/clockwork#208]
As per previous report (which was solved) I am not seeing the icons as you pointed out

![image](https://user-images.githubusercontent.com/31225533/32146481-6d2cf094-bc95-11e7-908a-0e41f51d0eae.png)

**Comment by itsgoingd** [comment]
Hey, can you check network tab in dev tools for any failed requests for webfonts?

**Comment by mikeerickson** [comment]
will do, see previous comment

**Comment by mikeerickson** [comment]
You were spot on with this one 500 error loading fontawesome web fonts

**Comment by itsgoingd** [comment]
Any error messages in the response, laravel or php/webserver error log? What kind of web stack are you using?
