### ISSUE TITLE
Still have issues with loading data in chrome debugger

### ISSUE THREAD

**Issue by mfour-merickson** [itsgoingd/clockwork#209]
I am having an issue where the log data is not being updated.  I have tried clicking the `more` button but nothing loads (just shows `loading...` and nothing happens) 

Note:  When using the webview, data is updated correctly 

![image](https://user-images.githubusercontent.com/31225533/32146990-b6551e3e-bc9c-11e7-8369-a4394f4e9921.png)

If I close the dev tools and reopen, the data appears

![image](https://user-images.githubusercontent.com/31225533/32147002-f0260e52-bc9c-11e7-9677-84bcad16479e.png)

**Comment by mikeerickson** [comment]
@itsgoingd Guessing based on lack of response you don't know what is causing this issue?

**Comment by itsgoingd** [comment]
Hey, sorry, missed this one, can you please check following when that happens:

- go to `chrome://extensions`
- click on `background page` under Clockwork
- check for errors in the console tab and network requests in the network tab

and

- go to `chrome://inspect`
- click on `inspect` on the dev tools instance in the "Other" tab
- check for errors in the console tab

Thanks!

**Comment by mikeerickson** [comment]
I am about to start a long car ride (wife will be driving so I can work), will give this a try after I get settled into the drive and report back w/  results.

**Comment by mfour-merickson** [comment]
Here you go, looks like there is indeed an error



Mike Erickson
Engineering Manager
MFour Mobile Research
(714) 754-1234 <tel:(714)%20754-1234>

MFour Blog <https://mfour.com/blog/>
 <https://mfour.com/>

**Comment by itsgoingd** [comment]
@mfour-merickson hey, if you were posting a screenshot it didn't get through
