### ISSUE TITLE
Not seeing the view tab

### ISSUE THREAD

**Issue by crissi** [itsgoingd/clockwork#210]
![image](https://user-images.githubusercontent.com/3076578/32149041-52c5fbdc-bcff-11e7-9138-6277cb6b1060.png)

I am running laravel 5.5 on PHP 7.1 and I have installed the lastest clockwork plugin and have the lastest chrome plugin installed

This page has a view.

I have digged a bit down and $this->app['events']->listen('composing:*', in LaravelDataSource are successfully firing the addEvent with my view, so the problem lies somewhere else

**Comment by itsgoingd** [comment]
Hey, view data is filtered by default, check out the `filter` key in the Clockwork config.

**Comment by crissi** [comment]
I see, thanks
