### ISSUE TITLE
Increase variable depth limit

### ISSUE THREAD

**Issue by sebastiaanluca** [itsgoingd/clockwork#211]
When viewing variables in the Chrome Clockwork panel, it seems there's a limit to their inner variable depth. Is there any way to increase this by setting a config entry or is this environment-specific (i.e. related to PHP configuration)?

<img width="390" alt="screen shot 2017-11-02 at 18 04 30" src="https://user-images.githubusercontent.com/711940/32339650-b7f61a36-bff8-11e7-92ae-d4b85fce72d1.png">

**Comment by itsgoingd** [comment]
Hey, we are not intentionally limiting the displayed data, a few reasons why this could happen:

- the item contains data that can't be serialized to json (eg. some binary data)
- the item contains recursive references
- the object has a `__toString` method returning empty value

I'll be taking a look at making our serialization process more error-proof, if you have any sample data that doesn't display correctly for you feel free to share.

**Comment by sebastiaanluca** [comment]
I'm using Clockwork in a Laravel project to view session information and other data. The screenshot above is an example of a session variable, where the object inside `items` is a simple PHP class. It doesn't override `__toString()`, so I assume it should display its (at least public) variables in some sort of way.
