### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by Bukashk0zzz** [itsgoingd/clockwork#212]
Any plans for Safari extension?

**Comment by itsgoingd** [comment]
Hey, as much as I like Safari, I don't this this is possible.

I took a quick look at the extensions api reference and there doesn't seem to be any way to extend dev tools in Safari.

Even if there was, It's unlikely to happen. Firefox recently adopted the WebExtensions api, a cross-browser browser extensions api spec based on Chrome. This makes Firefox extension possible as we can reuse 95% of the Chrome code.

If Safari ever moves to WebExtensions or adds a dev tools extensions api I'll consider adding support, right now the Safari extensions are dead.

In the meantime you can use the web UI in any browser.

**Comment by Bukashk0zzz** [comment]
Thanks for answer. Sad that Safari haven't dev tools api(
