### ISSUE TITLE
ErrorException (E_NOTICE) Undefined offset: 0 @ registerEvent

### ISSUE THREAD

**Issue by Hareland** [itsgoingd/clockwork#215]
Whenever i try to start an event with CW with Laravel 5.5, i get the following error:
http://prntscr.com/hasqcm

My code:
```PHP
$cw = new Clockwork();
$cw->startEvent('resource.margin.index', 'Loading resource w/index');
Event::fire('resource.index:before', [$request]);
//.....
Event::fire('resource.index:after', [$request, $response]);
$cw->endEvent('resource.margin.index');
```

I found that the issue was in fact in the file: vendor/itsgoingd/clockwork/Clockwork/DataSource/LaravelEventsDataSource.php#64
Which is:
```PHP
'data'      => Serializer::simplify((count($data) == 1 ? $data[0] : $data)),
```

I found that the issue was resolved when changing this to: 
```PHP
'data'      => Serializer::simplify((count($data) == 1 ? head($data) : $data)),
``` 

Solved the issue.

I am not sure this is an issue other people will have, but i figured i would post it in case it frustrates someone else.

Not sure what made this happen as the first element in the $data array is a Request and head() should pick up the same element as $data[0] but well, What do i know?

Laravel version: 5.5.14
PHP Version: 7.0.22

**Comment by itsgoingd** [comment]
Hey, fixed this in master.

I was able to reproduce this only by using an associative array as the event payload, which seems to be a valid input in Laravel 5.4+.

Thanks for the report!
