### ISSUE TITLE
Unable to scroll page details in Firefox Quantum

### ISSUE THREAD

**Issue by spaceemotion** [itsgoingd/clockwork#216]
Not sure if this has been posted here before, but while the version for chrome works perfectly fine, I am unable to scroll things like database queries in FF Quantum (the page list works).

Otherwise, thanks for this really great and lightweight alternative to debug-bar. Cheers!

**Comment by itsgoingd** [comment]
Hey, what platform and exact Firefox version are you running?

Can you try out the latest Firefox 58 beta? Clockwork is not working at all for me in 57 on MacOS, seems to work completely fine in the latest beta though.

**Comment by spaceemotion** [comment]
I'm already on the latest beta on Mac OSX (58.0b4, 64-bit).

**Comment by spaceemotion** [comment]
Small little update, scrolling seems to work fine when the window is wide enough for it to be side by side (columns). If it's too small and gets displayed as rows it no longer works.

**Comment by itsgoingd** [comment]
Ah, I kinda forgot we have that. :)

I'll try it out and fix if I can reproduce soon.

**Comment by itsgoingd** [comment]
Should be finally fixed in Clockwork 2.0.3, let me know if it works for you.

**Comment by spaceemotion** [comment]
Seems like that did the trick, thanks!
