### ISSUE TITLE
There is no data in the Clockwork tab

### ISSUE THREAD

**Issue by SerafimArts** [itsgoingd/clockwork#217]
1) Clockwork v2.0.3
2) Vanilla PHP
3) `PhpDataSource` handler
4) Sqlite storage
5) All headers are transmitted by following the documentation.
6) The page you need is there, there are also references to it when you load the page (seen from the logs of nginx)

But while the Clockwork tab is always empty.

![image](https://user-images.githubusercontent.com/2461257/33052169-98394d8c-ce7e-11e7-8124-3aa93243a505.png)

P.S.
1) [index.php](https://github.com/railt/example/blob/de0db12d33488093d0c2566cef86632290fb4cd7/public/index.php#L24-L34)
2) [clockwork.php](https://github.com/railt/example/blob/de0db12d33488093d0c2566cef86632290fb4cd7/public/clockwork.php)
3) [Add timeline and logs here](https://github.com/railt/example/blob/de0db12d33488093d0c2566cef86632290fb4cd7/src/Railt.php#L125-L141)
4) [Clockwork instance here](https://github.com/railt/example/blob/de0db12d33488093d0c2566cef86632290fb4cd7/src/Railt.php#L70-L78)

**Comment by itsgoingd** [comment]
Hey, found a bug in the Clockwork Chrome extension in processing of custom metadata request headers.

I'll try to get this fixed later today, in the meantime you can get it to work by not sending the `X-Clockwork-Header-Origin` header.

Thanks for the report!

**Comment by SerafimArts** [comment]
Yep! It works.
