### ISSUE TITLE
Allow the data sources to provide a stack trace

### ISSUE THREAD

**Issue by sisve** [itsgoingd/clockwork#225]
Hi,

I recently noticed the presentation of file:line in the browser view and dived into the code to look how I could use this in my own data source implementation. I am currently appending a stack trace to the sql statement, which makes it the most user-unfriendly thing I've ever built.

> SELECT * FROM client_logos t0 WHERE t0.client_id = "1" AND ((t0.deleted_at IS NULL OR '2018-01-08 07:14:39' < t0.deleted_at)) ... from App\Http\Middleware\SetCurrentClient->setCurrentClient:34, App\Http\Middleware\SetCurrentClient->handle:149, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}:53

My first thought was that I could now rewrite my data source to use this new functionality to present the data instead of my crappy solution. However, when reading the code, it seems we can only provide one file:line. I would really like to have this extended to allow an array of entries. This would help when there are repositories involved, and you want to figure out how the repository itself were called.

https://github.com/itsgoingd/clockwork/blob/3f9e9776dd549b726ae43ce2053e869aa4ebf391/Clockwork/DataSource/EloquentDataSource.php#L154-L166

**Comment by itsgoingd** [comment]
Collecting stack traces is now available in Clockwork 3.0 (enabled by default) - [blog post](https://underground.works/blog/clockwork-3.0-now-available) and [full changelog](https://underground.works/clockwork/changelog#content).
