### ISSUE TITLE
Incompatibility with laravel-transactional-events

### ISSUE THREAD

**Issue by sergio91pt** [itsgoingd/clockwork#226]
Adding [fntneves/laravel-transactional-events](https://github.com/fntneves/laravel-transactional-events) to a laravel project with clockwork and [barryvdh/laravel-ide-helper](https://github.com/barryvdh/laravel-ide-helper) fails with the following error:

```
In EloquentDataSource.php line 35:
                                                                                                        
  Type error: Argument 2 passed to Clockwork\DataSource\EloquentDataSource::__construct() must be an i  
  nstance of Illuminate\Events\Dispatcher, instance of Neves\Events\TransactionalDispatcher given, cal  
  led in /home/vagrant/Code/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkServiceProvi  
  der.php on line 71  
```

The problem is that imports `Illuminate\Contracts\Events\Dispatcher` instead of the contract `Illuminate\Events\Dispatcher`, although it only uses methods declared on the contract.

Affected files:
- Clockwork/DataSource/EloquentDataSource.php
- Clockwork/DataSource/LaravelCacheDataSource.php
- Clockwork/DataSource/LaravelEventsDataSource.php

**Comment by sergio91pt** [comment]
Seems this was already fixed on master

**Comment by itsgoingd** [comment]
Hey, feel free to use master, but expect things to break occasionally. Still a lot of work to be done before a stable 3.0 release.

**Comment by rovansteen** [comment]
@itsgoingd I'm running in to this issue as well, would you accept a PR that uses the contract for a 2.* minor/patch release?

**Comment by itsgoingd** [comment]
@rovansteen Hey, this will need to wait for 3.0 since it breaks Laravel 4.x compatibility.
