### ISSUE TITLE
DBALDataSource failing in convertParam

### ISSUE THREAD

**Issue by andrzejenne** [itsgoingd/clockwork#227]
Hi

I am using slim with doctrine on php 7.1 with original php.ini.
There is missing namespace for globals. 
Particularly DateTime, DateTimeImmutable and Exception cannot be found and app throws an error.

https://github.com/itsgoingd/clockwork/blob/master/Clockwork/DataSource/DBALDataSource.php#L110
https://github.com/itsgoingd/clockwork/blob/master/Clockwork/DataSource/DBALDataSource.php#L113

**Comment by itsgoingd** [comment]
Hey, thanks for the report. I'll fix this soon or accept a PR with fix against the v2 branch if you'd like to contribute (simply prefixing the classes with `\` is fine).

**Comment by itsgoingd** [comment]
Released in Clockwork 2.1, thanks!
