### ISSUE TITLE
No info returned with __clockwork route

### ISSUE THREAD

**Issue by samuelfoot** [itsgoingd/clockwork#230]
Have followed the setup guide and have added the middleware as well
I get the headers on my http and I also have the files being generated 
However if I go to the __clockwork/filename then a get an error as follows 
No query results for model [Project\Models\Page].

**Comment by itsgoingd** [comment]
Hey, looks like your app or some other 3rd party package has some sort of catch-all route which is catching the request before it gets to Clockwork. Check `php artisan route:list` for list of all registered routes.

**Comment by samuelfoot** [comment]
Hey. Thanks for the quick response. Is there a route I can add to the routes file to direct the __clockwork route correctly?

**Comment by itsgoingd** [comment]
I'd suggest trying to put the Clockwork service provider in your `app.providers` array right after the Laravel providers to make sure it's registered before any other third-party or custom providers.

Global middleware is also executed before the controller, so any custom global middleware might be interfering as well.

Also make sure Clockwork is actually enabled by setting `clockwork.enable` or `app.debug` to true.

If you want to try registering the Clockwork routes yourself, you can find them in the service provider - https://github.com/itsgoingd/clockwork/blob/master/Clockwork/Support/Laravel/ClockworkServiceProvider.php#L135-L146
