### ISSUE TITLE
Show number of SQL queries on top of tab

### ISSUE THREAD

**Issue by fgilio** [itsgoingd/clockwork#231]
I think I'd be much more useful that way. Now if the number of queries is high, I have to scroll just to see that number. Also, if for any reason, the number is really high the table gets all laggy when scrolling.

I'm proposing this here before making the PR, cause I saw that there's at least 3 places where this would need to be changed:

- https://github.com/itsgoingd/clockwork-chrome/blob/master/Clockwork%20Chrome/app.html#L292
- https://github.com/itsgoingd/clockwork-firefox/blob/master/Clockwork%20Firefox/app.html#L286
- https://github.com/itsgoingd/clockwork-web/blob/master/Clockwork/Web/public/app.html#L298

Would you like me to make those PRs?

**Comment by itsgoingd** [comment]
Hey,

I'd like to add counters similar to the "Cache" tab - https://underground.works/images/blog/2017-09-29-Introducing-Clockwork-2.0/cache-tab.png - with total number of queries, total execution time and maybe count of read/write queries.

If you'd like to try implementing this feel free to PR the `clockwork-chrome` repo (other repos are just copies of the Chrome code).

**Comment by fgilio** [comment]
Sure! I can try 😬

**Comment by robclancy** [comment]
God yes I need this. When I finally get time to help with clockwork this would be my first priority haha.

**Comment by fgilio** [comment]
I forgot to updated this issue. I tried, but failed before fully understanding how the current feature works in the "Cache" tab. I was short of time atm and had to abandon the fight.

**Comment by itsgoingd** [comment]
Hey, no problem, I've already implemented it in the meantime - https://github.com/itsgoingd/clockwork-chrome/pull/52.

There is a whole bunch of feature requests already done for 3.0, I really need to start referencing issues in the PRs, here is an overview for now - https://github.com/itsgoingd/clockwork/issues/232.

**Comment by fgilio** [comment]
Looks awesome, thanks @itsgoingd!

**Comment by itsgoingd** [comment]
Database tab improvements released in Clockwork 3.0 - [blog post](https://underground.works/blog/clockwork-3.0-now-available) and [full changelog](https://underground.works/clockwork/changelog#content).
