### ISSUE TITLE
Infinite repeated log loading

### ISSUE THREAD

**Issue by hareland** [itsgoingd/clockwork#236]
I am using clockwork 2.0.4, on php 7.1

My clockwork web UI and dev-tools just keep loading empty log files, over and over, it never stops which gives me something like this;

<img width="714" alt="screenshot at feb 23 11-23-32" src="https://user-images.githubusercontent.com/32701939/36591555-a8882448-1892-11e8-8f25-a5c105204f3f.png">

Might be linked to issue #203, where i can see that the FileStorage::store method allows saving empty files.

**Comment by itsgoingd** [comment]
Hey, can you describe your application a bit? Are you using Laravel or is this a custom Clockwork integration?

**Comment by hareland** [comment]
@itsgoingd My bad sorry...

Lumen 5.5, Nginx, MySQL, Redis, Guzzle (Also some third party profiler integration for Guzzle to Clockwork)

Our composer.json require:
```
    "php": ">=7.0",
    "laravel/lumen-framework": " 5.5.*",
    "vlucas/phpdotenv": "~2.2",
    "barryvdh/laravel-ide-helper": "^2.4",
    "itsgoingd/clockwork": "2.0.4",
    "hannesvdvreken/guzzle-clockwork": "1.1",
    "guzzlehttp/guzzle": "~6.0",
    "google/apiclient": "2.2.0",
    "spatie/array-to-xml": "2.3.0",
    "illuminate/mail": "^5.5",
    "spatie/laravel-permission": "2.9.0",
    "illuminate/redis": "5.5.*"
```

**Comment by itsgoingd** [comment]
Can you try using `dev-master` version of Clockwork? Might help with the empty requests metadata.

**Comment by hareland** [comment]
@itsgoingd It is working partly better, with more successful requests stored/displayed.
I am not getting the infinite loading of empty requests in the web ui any more.

**Comment by itsgoingd** [comment]
Requests list should now be more reliable in Clockwork 3.0 - [blog post](https://underground.works/blog/clockwork-3.0-now-available) and [full changelog](https://underground.works/clockwork/changelog#content).
