### ISSUE TITLE
Route::controllerMiddleware() protected method on Laravel 5.2

### ISSUE THREAD

**Issue by peppeocchi** [itsgoingd/clockwork#242]
Hi

[This commit](https://github.com/itsgoingd/clockwork/commit/322f3e5d5d54c3b93e84deade9d507ddcf0d524d) is a breaking change for Laravel 5.2, on that version `controllerMiddleware` is a [protected method](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Routing/Route.php#L257).

```
Call to protected method Illuminate\Routing\Route::controllerMiddleware() from context 'Clockwork\DataSource\LaravelDataSource'
```

**Comment by itsgoingd** [comment]
Fixed in Clockwork 2.2.2, thanks for reporting!
