### ISSUE TITLE
Server-Timing header format changed

### ISSUE THREAD

**Issue by kohenkatz** [itsgoingd/clockwork#244]
As of Chrome 65, only the new format for `Server-Timings` is supported.

See https://www.w3.org/TR/server-timing/#the-server-timing-header-field for the official format grammar and https://chromium-review.googlesource.com/c/chromium/src/+/767207 for the Chrome changes.

The basic idea is:

| Version | Example |
|--|--|
| Old | `app=355.61299324036; "Application", ...` |
| New | `app; dur=355.61299324036; desc="Application", ...`  |

I would do a PR, since this is pretty simple, but first this question needs to be answered: is there a reason to keep support for the old style and give people a config option (in case people are still using old versions) or should it just use the new format?

**Comment by itsgoingd** [comment]
Hey, PR would be most welcome, let's drop the old format and support the new format only.

**Comment by kohenkatz** [comment]
Great. I'll get to it this evening.

**Comment by itsgoingd** [comment]
Released as part of 2.2.3, thanks again!
