### ISSUE TITLE
v2.2.* makes flash messages persistent

### ISSUE THREAD

**Issue by phh** [itsgoingd/clockwork#247]
Since updating from `v2.1.*` to `v2.2.*` all my flash messages are getting persistent and wont go away.

Just adding messages by:
`return redirect()->route('web.testpage.create.form')->withInput($data)->with('error', $e->getMessage());`

**Comment by itsgoingd** [comment]
Hey, does your application use custom controller constructors?

So far I haven't been able to reproduce this with a clean Laravel install.

**Comment by Omranic** [comment]
@itsgoingd we're experiencing the same issue here too, it took me few hours to fined that this package is the reason of that issue. And yes, we're using custom controller constructors all over the project. Would you check and advice please..

**Comment by phh** [comment]
My `Controller extends AbstractController` (that `extends \Illuminate\Routing\Controller`) which `use`s these 3 traits:
- `\Illuminate\Foundation\Bus\DispatchesJobs`
- `\Illuminate\Foundation\Validation\ValidatesRequests`
- `\Illuminate\Foundation\Auth\Access\AuthorizesRequests`

**Comment by itsgoingd** [comment]
I suspect the problem might be collecting of middleware which was added in 2.2. This causes all controllers to be instantiated for the purpose of gathering middleware, which might not play nicely if you are doing some session stuff in the constructor.

Can you try commenting out this line and see if it helps? https://github.com/itsgoingd/clockwork/blob/v2/Clockwork/DataSource/LaravelDataSource.php#L236

**Comment by tnorthcutt** [comment]
@itsgoingd I'm having this same problem, and I can confirm that commenting out that line does solve the problem.

**Comment by phh** [comment]
@itsgoingd I can confirm that removing `'middleware' => $this->getRouteMiddleware($route)` resolves my issues regarding flash messages.

**Comment by itsgoingd** [comment]
Hey, dropped the feature in 2.2.4, as there is no way to avoid unexpected side-effects when instantiating controllers. Let me know if this works for you.
