### ISSUE TITLE
Unlink issue on FileStorage.php file

### ISSUE THREAD

**Issue by bcalik** [itsgoingd/clockwork#251]
Sometimes I get an error on this line: https://github.com/itsgoingd/clockwork/blob/e18d72abe51c07e0708a8285dd501eec19ecf937/Clockwork/Storage/FileStorage.php#L106

It tries to delete a json file that doesn't exist in storage/clockwork folder.
Maybe you should put `@` in front of it, so if the file doesn't exist, it should ignore.

**Comment by itsgoingd** [comment]
Hey, I'll accept a PR for this if you want to make one.

**Comment by itsgoingd** [comment]
Fixed in Clockwork 2.2.5.
