### ISSUE TITLE
[Bug] First start in Web UI produces 404 errors

### ISSUE THREAD

**Issue by spaceemotion** [itsgoingd/clockwork#256]
The web UI calls the `<id>/next` route every second. In a fresh installation (or if the clockwork folder has been cleared) there is no initial ID present, so it spams the console with "http://site.test/__clockwork/undefined/next could not be found" errors.

**Comment by lawmillion** [comment]
How to solve this problem?

**Comment by itsgoingd** [comment]
@lawmillion This issue should not affect functionality (will be fixed later), what's the problem exactly?

**Comment by itsgoingd** [comment]
Fixed in Clockwork 3.0 - [blog post](https://underground.works/blog/clockwork-3.0-now-available) and [full changelog](https://underground.works/clockwork/changelog#content).
