### ISSUE TITLE
SQL/file cleanup not working (Laravel)

### ISSUE THREAD

**Issue by sebastiaanluca** [itsgoingd/clockwork#257]
Noticed my Clockwork JSON files dir or SQL database quickly gets a few gigabytes large while I have `storage_expiration` set to `5` minutes.

```
'storage_expiration' => 5,
```

Been looking at previous issues and the source code, and noticed the config says _seconds_ while the internal code uses _minutes_ to define the expiration time. Code defaults to `60 * 24 * 7`, i.e. a week starting from minutes (instead of seconds).

>Maximum lifetime of the metadata in **seconds**, metadata for older requests

The SQL storage then multiplies that week by `60`, so I assume it subtracts it from `time()` in seconds? Or is that the culprit and should it remain minutes?

```php
$this->query("DELETE FROM {$this->table} WHERE time < :time", [ 'time' => time() - ($this->expiration * 60) ]);
```

### Versions

- Laravel 5.6
- Clockwork 2.2
- File or SQL driver

### References

- https://github.com/itsgoingd/clockwork/pull/178
- https://github.com/itsgoingd/clockwork/pull/178/files

**Comment by itsgoingd** [comment]
Hey, indeed the config comment has a typo, the value should be in minutes, not seconds, as you correctly deduced form the code. Thanks for letting me know!

That being said, I've tested both files and sql storage options with `storage_expiration` set to `5` and both seem to work fine. With files the cleanup runs only roughly once in 100 requests (1 in 100 chance per request), so you might occasionally see some older files, but hardly gigabytes.

Make sure the config isn't cached (you can dd-out the value to be sure). Also let me know any specifics of your environment, OS, filesystem, SQL database used..

**Comment by itsgoingd** [comment]
Ah, just remembered Sqlite doesn't actually free up disk space after deleting records in most cases. This shouldn't be a problem if you set the lower expiration right away, since the file size will never grow too much, but will definitively be a problem if you already have a large database and switch to lower metadata expiration.

We should probably just run `VACUUM` (http://www.sqlite.org/lang_vacuum.html) after each cleanup if it's fast enough, will look into it further.

**Comment by sebastiaanluca** [comment]
Aha, good to know. For now, I've just deleted the SQLite database and set the expiration to 5 minutes. So hopefully it'll never get to that size again. Thanks!

**Comment by itsgoingd** [comment]
After some further research I've decided to not `VACUUM` at all, since it shouldn't be needed under normal circumstances.
