### ISSUE TITLE
Show loaded view in tab

### ISSUE THREAD

**Issue by bertheyman** [itsgoingd/clockwork#264]
Would be really nice to see the loaded views, giving a jumpstart when working on an existing project.
Is there any way to do this currently?

**Comment by itsgoingd** [comment]
Hey, views, routes and cache queries are not collected by default to minimize the metadata size. You can publish the Clockwork configuration file and tweak the "filter" setting to allow views to be collected.

**Comment by bertheyman** [comment]
Perfect, just what I needed - thanks!

**Comment by martinandersen3d** [comment]
worked for me:
`php artisan vendor:publish --provider=Clockwork\Support\Laravel\ClockworkServiceProvider`
