### ISSUE TITLE
post param not recorded for axios request

### ISSUE THREAD

**Issue by lkloon123** [itsgoingd/clockwork#267]
post param able to be recorded by using postman, but unable to record when submitted by axios.

here's my request info: 

![42075329-05bc306e-7ba3-11e8-9d0e-6417f4155fe4](https://user-images.githubusercontent.com/21114981/42406476-0e081aa6-81db-11e8-8045-d6397daa884e.JPG)

Thanks.

**Comment by lkloon123** [comment]
Hi,

thanks for the reply, here's the network tab.

![capture](https://user-images.githubusercontent.com/21114981/42406488-53307c7c-81db-11e8-8000-033d25239d68.JPG)

**Comment by itsgoingd** [comment]
It looks like you might be posting the requests with your json data in the request body instead of using typical post data (`application/x-www-form-urlencoded` or `multipart/form-data`).

If this is the case you won't see any post data in Clockwork, but you can log the request json yourself like this (assuming this is Laravel application):

```php
clock('Request data:', request()->json()->all());
```

To log the json data for all requests you can put the snippet in a global middleware.

**Comment by lkloon123** [comment]
ohhh which means that if i post data using 
    formdata()
then it will work right?

**Comment by lkloon123** [comment]
ok great, is there any chance of including json request in parameters for future versions?

**Comment by itsgoingd** [comment]
I don't want to slow down the 3.0 release, but I'll take it into consideration for the next version. It would certainly be useful and not very hard to implement.

The only concern here is the json payloads might get very large. I work on an api that receives hundreds of megabytes of json data per request. That's also the reason why we never collect the response even if it would be useful for apis. Implementing some sort of limit for the size of collected data would solve these issues.

**Comment by lkloon123** [comment]
sure, thanks btw.

too bad that im not experience in browser extensions, else i can gv a pr :(

**Comment by spaceemotion** [comment]
Hey, are you still considering adding this? would also be okay with this being a configuration option. Cheers!

**Comment by itsgoingd** [comment]
Yep, added to the todo list.

**Comment by itsgoingd** [comment]
Support for request body data shipped in 4.0.
