### ISSUE TITLE
[LARAVEL] Enable clockwork in verified requests for production environment

### ISSUE THREAD

**Issue by joskfg** [itsgoingd/clockwork#269]
I'm trying to enable clockwork in production, but just when a secret is provided (Ex: Authorization header), but I'm having issues with that.

Laravel caches routes and config in production mode, so I need to enable clockwork for route generation but disable it for config generation to avoid clockwork to be always enabled in production.
The main issue is that, after register routes, clockwork doesn't check if it is enabled or not, so you can access the clockwork web app without authotization. The idea is to be able to enable clockwork for a single request and check it in the web app if you have the needed authorization.

Is it a bad idea? Do you already done this before?

Possibles approaches in my mind:
- Allow to add custom middlewares to clockwork routes
- Check in the route controllers if clockwork is enabled before send the response.
- Add this feature in the package itself and being configurable.

**Comment by itsgoingd** [comment]
Hey, Clockwork is getting native authentication support in 3.0. This is already available in master if you want to play with it. You will also need to use master version of the browser extension.

Out of the box we only support a simple authentication using a single password. You can enable this and set the password in the Clockwork config.

If you need a more complex authentication (eg. authenticating against users in database) you can write your own authenticator. I can provide more information on that if you are interested in doing so.

**Comment by joskfg** [comment]
I will try it to check the new version. When it is supposed to be released? Is there an approximate date?

**Comment by itsgoingd** [comment]
I've already missed the planned release date. 😅 But the code is 90% done, so it shouldn't take more than 1-2 weeks.

**Comment by joskfg** [comment]
I was checking https://github.com/itsgoingd/clockwork/pull/252 but it is just for access permissions. The idea is not to log all the requests, just log the ones that are authorized. Will be that feature supported? Do you have any idea to do it?

**Comment by itsgoingd** [comment]
Yeah, this can already done by conditionally setting `config([ 'clockwork.enable' => false ])`.

You can do so in a service provider (eg. `AppServiceProvider`), which completely disables Clockwork.

You can also do this in a middleware or anywhere really, but at that point Clockwork would register some event listeners (eg. log messages, queries etc.), potentially impacting your application performance. The collected data will be thrown out at the end of the request.

**Comment by joskfg** [comment]
I tried that conditionally approach but it is not possible due to the reasons from my first comment.

Steps I followed:

1. The routes are cached when you build the project (composer install), so you need to enable clockwork to be able to register the routes because they will be cached and if you don't have them clockwork won't be able to work.
2. I cache the config with the clockwork disabled `[ 'clockwork.enable' => false ]`, this will avoid to load all the clockwork stuff in all the requests.
3. I modify `AppServiceProvider`to modify the `clockwork.enable`config on the fly to enable it in an specific request to avoid performance issues and collect too much information.

The issue found with this and solved partially with the 3.0 release and the authentication is that routes are registered, but clockwork doesn't check if it is enable. It considers that if the routes are registered, it is enable, so you can access for exmample the web dashboard with clockwork disabled. With Authentication you have at least a auth protection so anybody can access, but it is actually enabled and not disabled as it should be.

I think that all the clockwork components should check if clockwork is enabled and avoid the usage if it is not. The listeners (I guess) are working as expected because they don't rely on cache and are registered in service provider bootstrap that already checks the clockwork status, but the routes were registered in build time and the controllers don't check the clockwork status.

**Comment by itsgoingd** [comment]
Hey, you bring up a good point about the inconsistent behaviour when running *with* and *without* the route cache. I will add the additional controller checks in 3.0 to make the behaviour consistent.

**Comment by itsgoingd** [comment]
Additional checks added in Clockwork 3.0 - [blog post](https://underground.works/blog/clockwork-3.0-now-available) and [full changelog](https://underground.works/clockwork/changelog#content).
