### ISSUE TITLE
empty panel on Google Chrome

### ISSUE THREAD

**Issue by alextime** [itsgoingd/clockwork#276]
Hi, I have upgraded to version 3, Chrome extension is on version 3 and Laravel 5.5. Chrome panel is always empty. If I visit 
http://host/__clockwork/header_id I get all the json data but the panel is always empty. Using firefox works fine, so I do not think the problem is on server side. Tried to uninstall extension, quit Chrome, install again and the problem persist. Any advice to solve this problem? Thanks!

**Comment by itsgoingd** [comment]
Hey, can you please try following - while having Clockwork open in one tab open a new tab and type in `chrome://inspect`, click on "Other" and "inspect" - this will open dev tools window for the Clockwork extension, let me know if there are any errors in the console tab. Thanks!

**Comment by alextime** [comment]
Yes they are:

`Main._createAppUI: 22.485107421875ms

shell.js:7910 Main._showAppUI: 31.60400390625ms

shell.js:7910 Main._initializeTarget: 9.60595703125ms

shell.js:7910 Main._lateInitialization: 8.56982421875ms

app.html:1 Error in event handler for (unknown): TypeError: Cannot read property 'http://genio-alpha.test/__clockwork/' of undefined at Requests.callRemote (chrome-extension://dmggabnehkmmfmdffgajcflpdjlnoemp/assets/javascripts/requests.js:119:88)
    at Requests.loadId (chrome-extension://dmggabnehkmmfmdffgajcflpdjlnoemp/assets/javascripts/requests.js:34:15)
    at api.runtime.sendMessage (chrome-extension://dmggabnehkmmfmdffgajcflpdjlnoemp/assets/javascripts/extension.js:144:19)
app.html:1

Error in event handler for (unknown): TypeError: Cannot read property 'http://genio-alpha.test/__clockwork/' of undefined
    at Requests.callRemote (chrome-extension://dmggabnehkmmfmdffgajcflpdjlnoemp/assets/javascripts/requests.js:119:88)
    at Requests.loadId (chrome-extension://dmggabnehkmmfmdffgajcflpdjlnoemp/assets/javascripts/requests.js:34:15)
    at api.runtime.sendMessage (chrome-extension://dmggabnehkmmfmdffgajcflpdjlnoemp/assets/javascripts/extension.js:144:19)`

**Comment by itsgoingd** [comment]
Hey, can you please try this version? 
https://github.com/itsgoingd/clockwork-chrome/archive/fix-maybe.zip

To load the extension from zip file, extract it, go to `chrome://extensions`, enable "Developer mode" top-right and click "Load unpacked extension".

**Comment by alextime** [comment]
Yes, this one load correctly! Many Thanks!!

**Comment by alextime** [comment]
I just realized that the version you post it is working but it is killing laravel performance:

I am using:
Laravel Version: 5.5.40
PHP Version: 7.2
Database Driver & Version: MySQL 5.7.23
Valet version: 2.0.12
Mac: MacBook Pro 15'' 16GB 500SSD late 2015

The is an enormous difference between rendering a relative complex "naked" collection only (avoiding the entire web UI, views, etc. and without clockwork) and rendering the very same content using views and clockwork; the difference is 1.704ms against 217.893ms (2 seconds against 21!) and from 14MB to 380MB. If I disable that clockwork version posted I get good performance.

![schermata 2018-08-23 alle 18 04 47](https://user-images.githubusercontent.com/11634019/44538238-11c92180-a701-11e8-9615-f3153745fc47.png)
![schermata 2018-08-23 alle 18 04 41](https://user-images.githubusercontent.com/11634019/44538239-11c92180-a701-11e8-9669-23854ef5a521.png)

**Comment by itsgoingd** [comment]
Hey, are you running the latest version (3.0.1)? If you are executing a lot of database queries or log messages you can also try disabling the stack traces collecting to improve performance.

**Comment by alextime** [comment]
I had 3.0, now I got 3.0.1 but even if the time counter shows the time Laravel would spend without the package left active, the time to render the page is the same as before. As you see in the picture the first page request was on 3.0 for almost 11 seconds; the second request is on 3.0.1 and it requires 3.6 seconds, but even if clockwork states 3.6 seconds in reality the page renders in 10 seconds anyway. collect_stack_traces=>off produces the same result. If I disable the package I really get the page in more or less  3 seconds...

![schermata 2018-08-27 alle 14 42 18](https://user-images.githubusercontent.com/11634019/44660342-9cfb2d80-aa07-11e8-9f86-7023d1e39084.png)

**Comment by itsgoingd** [comment]
Can you please reproduce the slow request and send me the last metadata file from `storage/clockwork` to info@underground.works?
