### ISSUE TITLE
Memory exhausted in StackTrace.php:17 when request has large number of queries

### ISSUE THREAD

**Issue by marcusbetts** [itsgoingd/clockwork#278]
I'm getting the following error when I make a request that performs a large number of queries.

```
Symfony\Component\Debug\Exception\FatalErrorException: Allowed memory size of 536870912 bytes 
exhausted (tried to allocate 20480 bytes) in 
/var/www/html/vendor/itsgoingd/clockwork/Clockwork/Helpers/StackTrace.php:17 Stack trace: 
#0 {main} {"identification":{"id":"08b683fd-b607-447e-b789-d143b2339853"}} []
```

My particular request is executing over 4500 queries. If I add 'databaseQueries' to the config filter, all is fine. I haven't had any luck using the 'filter_uris' as it seems to just be ignored. Here is my attempt at the filter:

```
'filter_uris' => [
        '/__clockwork/.*', // disable collecting data for clockwork-web assets
        '/horizon/.*', // disable collecting data for Laravel Horizon requests
        '/registration-periods/wizard/.*', // disable collecting data for cloning a registration period
],
```

**Comment by itsgoingd** [comment]
Hey, what is the url you are trying to filter?

You can also try turning off collecting stack traces in the config. This will help a lot with metadata size, since by default we are collecting stack traces for all queries.

**Comment by marcusbetts** [comment]
The complete uri I am having this issue with is:

```
/registration-periods/wizard/clone/create-new-registration-period
```

I need/want to collect stack traces while in dev and qa environments but would be willing to exclude the above uri.

**Comment by itsgoingd** [comment]
Hey, Clockwork is not very smart here, instead of not collecting metadata for filtered urls it *does* collect the data, but throws it away instead of saving it in the end. I'll take a look at fixing this in 3.1.

In the meantime you can either disable collecting stack traces or disable collecting of queries for the database-heavy controller by including this call at the top of the controller:

```php
app('events')->forget(\Illuminate\Database\Events\QueryExecuted::class)
```

**Comment by jeffersonmartin** [comment]
I ran into a similar issue. Here's the screenshot of what I encountered for your debug reference. 

I'm just going to roll back to v2.x for now. Thank you for helping the community with such a fantastic tool!

<img width="1659" alt="screenshot 2018-08-20 13 53 48" src="https://user-images.githubusercontent.com/2792208/44366276-05cf2c80-a481-11e8-8200-816e00a82a39.png">

**Comment by johanvanhelden** [comment]
I am having the same issue with Laravel Nova. First I blamed Nova, turned out the memory issue was caused by Clockwork.

**Comment by marcusbetts** [comment]
> Hey, Clockwork is not very smart here, instead of not collecting metadata for filtered urls it _does_ collect the data, but throws it away instead of saving it in the end. I'll take a look at fixing this in 3.1.
> 
> In the meantime you can either disable collecting stack traces or disable collecting of queries for the database-heavy controller by including this call at the top of the controller:
> 
> ```
> app('events')->forget(\Illuminate\Database\Events\QueryExecuted::class)
> ```

Thanks for helping and providing an option. I'll test this option when I get back to this project.

BTW...I'm a huge fan of clockwork...I can't tell you how many hours it has saved me when debugging.

**Comment by itsgoingd** [comment]
Improved filtered uris implementation now available in master, will be included in Clockwork 3.1.

**Comment by Zolak94** [comment]
> Hey, Clockwork is not very smart here, instead of not collecting metadata for filtered urls it _does_ collect the data, but throws it away instead of saving it in the end. I'll take a look at fixing this in 3.1.
> 
> In the meantime you can either disable collecting stack traces or disable collecting of queries for the database-heavy controller by including this call at the top of the controller:
> 
> ```
> app('events')->forget(\Illuminate\Database\Events\QueryExecuted::class)
> ```

Can you be more specific with where we need to put that line of code, which document and where it is? Thank you.

**Comment by itsgoingd** [comment]
Hey, this was already fixed, if you want to disable Clockwork for a specific URI you can simply add it to the `filter_uris` array in config.

You can also globally disable collecting db queries by adding `databaseQueries` to the `filter` array in config.

If you have issues with high memory usage, you can try some suggestions from this comment https://github.com/itsgoingd/clockwork/issues/308#issuecomment-464092527
