### ISSUE TITLE
Vanilla PHP Response Resolution Problem

### ISSUE THREAD

**Issue by okridgway** [itsgoingd/clockwork#284]
1. Clockwork v3.0.2
2. Vanilla PHP
3. PhpDataSource handler
4. FileStorage storage

Tab wont resolve the page response or give any data. Help? 

<img width="1310" alt="screen shot 2018-09-13 at 21 59 24" src="https://user-images.githubusercontent.com/19399895/45527305-79263e80-b7a0-11e8-957d-e0c75b90284d.png">

<img width="1294" alt="screen shot 2018-09-13 at 21 59 17" src="https://user-images.githubusercontent.com/19399895/45527307-7a576b80-b7a0-11e8-8df7-6177ae04135b.png">

<img width="1295" alt="screen shot 2018-09-13 at 22 02 33" src="https://user-images.githubusercontent.com/19399895/45527358-bbe81680-b7a0-11e8-9e98-27b716ccc82f.png">

**Comment by itsgoingd** [comment]
Hey, sorry for the slow response. By default Clockwork apps expect the data to be available at `/__clockwork/<ID>`, this can be overridden by sending an `X-Clockwork-Path` header with a custom uri-prefix. In your case you will need to send an `X-Clockwork-Path: /pages/clockwork.php?id=` header.
