### ISSUE TITLE
Clockwork web UI - Xdebug profiler never finishes processing

### ISSUE THREAD

**Issue by newlinkcapital** [itsgoingd/clockwork#286]
When trying to view the profiler information in the web UI, this message shows up on console and the spinner never goes away.

`Uncaught (in promise) TypeError: Cannot read property 'split' of undefined
    at Function.parseSync (VM1217 callgrind.js:21)
    at Promise (VM1217 callgrind.js:10)
    at new Promise (<anonymous>)
    at Function.parse (VM1217 callgrind.js:9)
    at Profiler.parseProfile (profiler.js:75)
    at requests.loadExtended.then.request (profiler.js:67)
    at angular.min.js:137
    at m.$digest (angular.min.js:148)
    at m.$apply (angular.min.js:151)
    at l (angular.min.js:103)`

The problem seems to be that on line VM1217 callgrind.js the `data` variable is empty.

`data = data.split("\n") // cant call split() of undefined`

![image](https://user-images.githubusercontent.com/39839168/46422120-04dd1c00-c70a-11e8-846c-b9516f675c88.png)

![image](https://user-images.githubusercontent.com/39839168/46422133-0dcded80-c70a-11e8-866f-dbcdff723233.png)

**Comment by itsgoingd** [comment]
Hey, this would mean we did not receive any Xdebug profile data.

When you open the profiler you should see a request to `/__clockwork/123/extended` in the network tab. Check the response for the `xdebug` key under which you should see `profile` key with a path to the profile file and `profileData` with a huge blob of the profile content.

Is the `profileData` key empty/not included? Does the referenced file under `profile` exist and is it readable?

**Comment by crissi** [comment]
Had the same error. This answer to this question fixed it for me: https://stackoverflow.com/questions/46245662/xdebug-profiler-laravel-5-5-windows-empty-grindfile

**Comment by AlejandroAkbal** [comment]
> Had the same error. This answer to this question fixed it for me: [stackoverflow.com/questions/46245662/xdebug-profiler-laravel-5-5-windows-empty-grindfile](https://stackoverflow.com/questions/46245662/xdebug-profiler-laravel-5-5-windows-empty-grindfile)

Thank you! This did it for me!

**Comment by flexchar** [comment]
@itsgoingd Hey! Fudging amazing product! But I've faced the same error running the latest versions. Has this been pushed to live yet? :)

Version: 5.1.0
