### ISSUE TITLE
Content type on auth requests

### ISSUE THREAD

**Issue by ssnepenthe** [itsgoingd/clockwork#287]
Not the end of the world, but I just noticed...

When using the web view, requests to __clockwork/auth are sent with a content type of application/json.

When using the browser extension view, they are sent as multipart/form-data.

On the server I have clockwork 3.0.2.

Tested in both firefox and chrome with the latest extension version.

**Comment by itsgoingd** [comment]
Fixed in Chrome master, form-data is the intended format. Thanks!
