### ISSUE TITLE
Missing assets after installation

### ISSUE THREAD

**Issue by icamys** [itsgoingd/clockwork#288]
I am using Laravel 5.7.

After installation all requests to `__clockwork/assets` are getting 404 response.

I've copied `vendor/itsgoingd/clockwork/Clockwork/Web/public` to my `public/__clockwork` and it has started to work.

**Comment by itsgoingd** [comment]
Hey, just tested on a clean Laravel 5.7 install and it should work fine. Can you post the not-found exception with a full stack trace? Might be some middleware or catch-all route interfering.

**Comment by icamys** [comment]
Hi! Sorry for wasting you time - I've decided to use another profiling tool, so I can't send you the full stack trace.
