### ISSUE TITLE
laravel5.6 Unable to use the latest version of v3.0.2

### ISSUE THREAD

**Issue by duzhenxun** [itsgoingd/clockwork#289]
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package itsgoingd/clockwork ^3.0 exists as itsgoingd/clockwork[dev-add-cache-queries-support, dev-add-laravel-events-data-source, dev-add-support-for-laravel-package-auto-discovery, dev-authentication, dev-disable-in-console-by-default, dev-drop-laravel-4-support, dev-fix-collecting-queries-when-using-odbc, dev-fix-sqlstorage-postgresql-compatibility, dev-improve-doctrine-bindings-preparation, dev-laravel-automatically-push-middleware, dev-master, dev-metadata-expiration, dev-require-php-55, dev-resolve-stack-trace-view-names, dev-rework-code-style-drop-php5-support, dev-serialization-rework, dev-server-timing-support-tweaks, dev-stack-traces, dev-storage-api-rework, dev-subrequests, dev-symfony-support, dev-tweak-request-id-format, dev-user-data, dev-web-ui, dev-web-ui-dark-theme, v0.9.0, v0.9.1, v1.1, v1.10, v1.10.1, v1.11, v1.11.1, v1.11.2, v1.12, v1.13, v1.13.1, v1.14, v1.14.2, v1.14.3, v1.14.4, v1.14.5, v1.2, v1.3, v1.4, v1.4.1, v1.4.2, v1.4.3, v1.4.4, v1.5, v1.6, v1.7, v1.8, v1.8.1, v1.9, v1.x-dev, v2.0, v2.0.1, v2.0.2, v2.0.3, v2.0.4, v2.1, v2.1.1, v2.2, v2.2.1, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.x-dev] but these are rejected by your constraint.

**Comment by itsgoingd** [comment]
Hey, I assume you are running PHP 5.5+ since you are using Laravel 5.6? Clockwork has pretty much no dependencies, so there should not be any conflict. Might be just some random composer issue, try deleting composer cache etc.

**Comment by duzhenxun** [comment]
> Hey, I assume you are running PHP 5.5+ since you are using Laravel 5.6? Clockwork has pretty much no dependencies, so there should not be any conflict. Might be just some random composer issue, try deleting composer cache etc.

I found the cause of the problem.Because I used my Chinese composer update.Probably the largest version of China's data is v2.2.5
I really like the extension you have developed. Thank you.
