### ISSUE TITLE
Post data not recorded correctly

### ISSUE THREAD

**Issue by ametad** [itsgoingd/clockwork#298]
Post data contains a array with key and empty value (network tab):

![image](https://user-images.githubusercontent.com/1582541/48067344-54fb4280-e1d0-11e8-8aac-7d2ddffbad66.png)

Dump (`dd($request);`) in Laravel correctly shows:

![image](https://user-images.githubusercontent.com/1582541/48067654-17e38000-e1d1-11e8-9989-85f7cf74095a.png)

But Clockwork recorded the Post data incorrectly as:

![image](https://user-images.githubusercontent.com/1582541/48067442-9ab80b00-e1d0-11e8-9b99-a301d68c6168.png)

Notice the key is "0" instead of "2".

**Comment by itsgoingd** [comment]
Fixed in master, thanks!

**Comment by ametad** [comment]
How often do you release a new version about?

**Comment by itsgoingd** [comment]
I'm planning on releasing a bigger 3.1 release this or next week including this fix.

**Comment by ametad** [comment]
You're the best :+1: Thank you very much!
