### ISSUE TITLE
Sorting by SQL asc/desc not in proper order

### ISSUE THREAD

**Issue by fitztrev** [itsgoingd/clockwork#305]
On the Database tab, when clicking the "SQL" header to sort, the queries are not sorted alphabetically.

I'll get queries in the following order:

```sql
SELECT * FROM `a` ...
SELECT count(*) as ...
SELECT * FROM `a` ...
SELECT * FROM `bb` ...
SELECT * FROM `a` ...
```

It is a useful sort to have when looking for duplicate/redundant queries on a page.

**Comment by itsgoingd** [comment]
Fixed, thanks!

**Comment by fitztrev** [comment]
@itsgoingd Thank you for fixing. Do you know which release this will be in?

**Comment by itsgoingd** [comment]
Hey, this should already be out, your extension should auto-update. The current version number is 3.1.3, you can check `chrome://extensions/` for the installed version.

**Comment by fitztrev** [comment]
Ah, ok. Yes, I'm on 3.1.3. The SQL column is indeed fixed. I think there's a similar issue with the Model column. I'll open a different issue. Thank you
