### ISSUE TITLE
Make ignored packages for the stack traces configurable

### ISSUE THREAD

**Issue by robclancy** [itsgoingd/clockwork#306]
https://github.com/itsgoingd/clockwork/blob/4fbd14aefcbe8486515d1ae0da711525705ad606/Clockwork/Request/Log.php#L29

We use https://github.com/fntneves/laravel-transactional-events which wraps all transactions so we get the stacktraces from that and then illuminate things until we get to our app stuff.

I'm going to override the `clockwork.log` with this added but would be nice to be able to just set it. Maybe not in the config file because it's very specific but statically using a provider.

**Comment by itsgoingd** [comment]
Added to the todo list, thanks.

**Comment by karptonite** [comment]
Would also be nice to ignore non-vendor files. I wanted to wrap clockwork in my own adapter class, but all errors were being reported from the same line in my adapter.

**Comment by itsgoingd** [comment]
Configurable ignored packages and classes shipped in 4.0, re-publish config file. You can also ignore files and functions in code.
