### ISSUE TITLE
Clockwork with laravel REST Api 

### ISSUE THREAD

**Issue by DavidSprauel** [itsgoingd/clockwork#307]
I'm developing a REST Api with laravel and have been told about clockwork and wanted to give it a try since i'm focusing my work on perf.
I installed the package and use the webapp (as i got no front end in an api).

Unfortunately the web app doesn't seems to monitor call i'm doing from postman. Is there any solution or maybe i missed something ?

Thanks.

**Comment by itsgoingd** [comment]
Hey, the web UI should show any HTTP requests to the app. Do you see any errors in the dev tools console for the web UI? Can you see Clockwork metadata files being created in `storage/clockwork`?

**Comment by DavidSprauel** [comment]
Alright just, opened again the web app and now works without any intervention. 
Sorry for the issue.

**Comment by itsgoingd** [comment]
I believe there is actually a bug when you open the web UI after installing Clockwork, before making any requests to the app. That would explain why it's working now, will investigate further.

Thanks for the report and sorry for the inconvenience.
