### ISSUE TITLE
Profiler not enabled when using docker.

### ISSUE THREAD

**Issue by BRafols** [itsgoingd/clockwork#319]
So I've come a long way and finally wrapped my head around the profiler and ended up with the following setup using PHP inside a Docker container

I have installed XDebug and configured it correctly, now when opening clockwork the XDEBUG_PROFILE cookie is set. And the response headers include `X-Xdebug-Profile-Filename: /tmp/cachegrind.out.6.08a3b8`

Now I mapped my local `/tmp` folder to the container `/tmp`, which means that that cachegrind file is present in the host machine.

However, Clockwork still says that profiler is NOT enabled.

Any clue what I'm missing?

**Comment by itsgoingd** [comment]
Hey, by not enabled, do you mean the "Profile is not present for current request." message?

If you open the last metadata file in `storage/clockwork` after making a request with profiler enabled, do you see an `xdebug` key with the `/tmp/cachegrind` file as value?

Btw. the profile files do not need to be readable on the host machine for Clockwork to read the profile data, this is done by the php-part of Clockwork.

**Comment by nyrik8989** [comment]
docker

php8
xdebug3

php.ini
[xdebug]
xdebug.mode = profile
xdebug.start_with_request = yes
xdebug.use_compression = false

**Comment by brunofunnie** [comment]
I've added the full steps for setting up Clockwork Profiler to work with Docker in this thread #591

**Comment by videni** [comment]
@nyrik8989 , did you make it work?  I got exactly config in docker, not working at all , xdebug 3.2
