### ISSUE TITLE
Is there any way to search over old stored requests?

### ISSUE THREAD

**Issue by Ir00man** [itsgoingd/clockwork#323]
Very useful thing is to search over all stored meta-data to find some errors or just filter by URL.
Is this something possible now with current extension? Or maybe planned to be implemented?

Because when we have Clockwork enabled on production and we have some report about 400/500 error it's not possible (or at least not easy) to find exact request with all meta-data included.

Hope to hear you back! Thx.

**Comment by itsgoingd** [comment]
Hey, requests history search is coming out in Clockwork 4 pretty soon.

You will be able to search by URI, method, controller, response status, response time and request date.

See https://github.com/underground-works/clockwork-app/pull/6 for details.

**Comment by itsgoingd** [comment]
Requests history search shipped in 4.0.
