### ISSUE TITLE
Ajax requests do not appear in chrome extension

### ISSUE THREAD

**Issue by mmoray-havas** [itsgoingd/clockwork#325]
When trying to view the ajax requests/responses logging information in the chrome extension, nothing is being outputted. I was able to get the json via .../storage/clockwork, but would like to view this information within the chrome extension. Any insight would be greatly appreciated.

Chrome Version: Version 74.0.3729.131 (Official Build) (64-bit)
Laravel Version: Laravel Framework 5.6.39

Thanks!

**Comment by itsgoingd** [comment]
Hey, can you elaborate on what exactly is happening?

Do the requests show in the requests list but the content is missing or do they not show up at all?
Do other non-ajax requests work correctly?
Are the ajax requests executed by the page in the browser tab you opened the dev tools window for?
Do they show up in the web UI (your.app/__clockwork) ?

Thanks.

**Comment by mmoray-havas** [comment]
Hey,

1. Nothing shows up in requests list when making the request (so, the finer details do not show up)
2. Sometimes, when hitting the same endpoint as the ajax call, I still do not receive any information in the requests list. 
3. The ajax requests are triggered by a user action (click of a button) on the page (so yes, I believe so)
4. I have not been able to get the your.app/__clockwork page to load. I keep getting a 400 error.

**Comment by marcus-at-localhorst** [comment]
Not sure if that's relevant, since I don't use Laravel, instead I use Clockwork with Vanilla PHP and the Fatfreeframework.

The problem why my Ajax calls didn't show up in Clockwork was, an `exit;` in the controller code that made it impossible to reach `$clockwork->requestProcessed()` in my app (I know laravel is setup differently with some magic, but maybe it's similar).

Here is a minimal setup that should give you an idea:

```php

$f3->set('clockwork', Clockwork\Support\Vanilla\Clockwork::init());
$f3->route('GET /ajax', '\Controller->get()');
$f3->run();

```

```php
class Controller{
	public function get()
	{
		if ($this->f3->get('GET.format') == 'json') {
			// output json
			echo $this->template->render('_data.json', 'application/json');
			// this exit prevented this->afterroute() from executing and therefore 
			// no clockwork data was added to the request. 
			exit;
		}

	}

    function afterRoute() {
        // add Clockwork headers etc.
        $this->f3->get('clockwork')->requestProcessed();
    }
}
```

**Comment by mmoray-havas** [comment]
Hey @marcus-at-localhorst,

You are most-likely correct. Currently the application I am supporting is huge, and I know it's riddled with some exit and die's. 

Thank you for following up and helping me out with this!

Thanks,
@mmoray-havas
