### ISSUE TITLE
You rerender or something when new requests come in so it switches tab after I have selected one, super annoying

### ISSUE THREAD

**Issue by robclancy** [itsgoingd/clockwork#328]
When loading if I select a tab and another request finishes it changes the tab to the last request instead of where I am reading.

**Comment by itsgoingd** [comment]
We currently pause showing new requests if you manually select request in the requests list. Doing the same when you change tab seems like a reasonable thing to do, will add in the next release.

**Comment by robclancy** [comment]
This is still happening. I don't see why anyone would ever want to auto focus the newest tab, that's not how tabs work on anything. Just never mess with focus no matter if one is selected or not. It's even more random now too, it focuses the first thing in the list.

**Comment by itsgoingd** [comment]
The new requests should stop auto-focusing when you manually select a request different than the last one or change a tab in the request details. It will resume once you select the last request or clear the requests list.

The idea behind the auto-focus of new requests is so you don't have to manually click on the new request every time you refresh when debugging a particular endpoint.

Now this gets a bit annoying when the page does some ajax calls, esp. with ajax polling. Maybe we should auto-focus new requests only when they are full-page reloads.

Also ability to hide ajax requests and/or marking them in the requests list might be a good idea.

Would this help or is your use-case something different?

**Comment by robclancy** [comment]
Select the first one on load and just don't do anything after. Any website/app or anything jumping or switching without my action saying to do that is bad.

**Comment by robclancy** [comment]
This is still happening. Every new request makes the first tab get selected. I'm getting to the point I'll just use debugbar because it takes me a lot longer just to get where I want to be because I have to fight to have my tab shown, literally have to keep clicking my tab over and over as new requests come in.

**Comment by itsgoingd** [comment]
Changing active tab should stop new requests getting automatically selected - http://abyss.shadowfall.eu/its/Screen%20Recording%202019-09-21%20at%2022.05.03.mp4

Or am I misunderstanding?

**Comment by robclancy** [comment]
It has never stopped it for me. I click multiple times to get my tab back.
It keeps selecting the first tab. It shouldn't ever select any other than
first by default. Like network tools.

**Comment by itsgoingd** [comment]
Update on this - you will be able to fully disable this behavior in the upcoming 4.1 release (https://github.com/underground-works/clockwork-app/pull/19).

**Comment by itsgoingd** [comment]
This is now configurable in Clockwork 4.1.
