### ISSUE TITLE
Make request failures red in the tab, like the network tab does

### ISSUE THREAD

**Issue by robclancy** [itsgoingd/clockwork#330]

**Comment by itsgoingd** [comment]
By request failures you mean HTTP 500 responses? Clockwork 4.0 will have redesigned requests list with color-coded status codes (https://github.com/underground-works/clockwork-app/pull/6).

**Comment by robclancy** [comment]
Basically I think the requests section should mimic the network tab as much as possible. So any failure code should be red etc.

The PR you show looks good.
