### ISSUE TITLE
Is it possible to add Clockwork to other frameworks like CodeIgniter without Composer?

### ISSUE THREAD

**Issue by rostamiani** [itsgoingd/clockwork#333]
Hi
Can I add this perfect library to my CodeIgniter project?
 How can I do it without Composer?

Thanks

**Comment by itsgoingd** [comment]
Hey, CodeIgniter support was dropped in 2.0, but you can still use the 1.x version here https://github.com/itsgoingd/clockwork/tree/v1.

**Comment by rostamiani** [comment]
Thanks, Can I still write my own library to import it to CodeIgniter 3?
Are [these documents](https://github.com/itsgoingd/clockwork/wiki/Development-notes) still valid for the last version of Clockwork? :
https://github.com/itsgoingd/clockwork/wiki/Development-notes

**Comment by itsgoingd** [comment]
They are still mostly valid, just missing some newer data fields. Also check out the docs on the official website https://underground.works/clockwork/extending-implementation?#content.

I'd also suggest taking a look at the original CodeIgniter integration or the other newer integrations for inspiration. If you run into any issues let me know.
