### ISSUE TITLE
Error In Lumen 5.8 After Upgrade To 4.0

### ISSUE THREAD

**Issue by Owlnofeathers** [itsgoingd/clockwork#334]
Hey, 

Thanks for such a great tool! Its been working great for me.

However, I  upgraded from v3.1.4 to 4.0 with Lumen v5.8.10. Attempting to run commands from the terminal (ive tried both `php artisan` and `vendor/bin/phpunit`) immediately return this error:

```
In LaravelDataSource.php line 54:

  Argument 1 passed to Clockwork\DataSource\LaravelDataSource::__construct() must be an instance of Illuminate\Contracts\Founda
  tion\Application, instance of Laravel\Lumen\Application given, called in .../vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkServiceProvider.php on line 155
```
which is interesting because im registering the lumen service provider in app.php.
```
$app->register(Clockwork\Support\Lumen\ClockworkServiceProvider::class);
```

Thanks for any help, or direction if ive missed something in the docs somewhere for this 4.0 upgrade in lumen.

**Comment by itsgoingd** [comment]
Hey, tagged version 4.0.1 with a bunch of Lumen fixes, give it a try.

Thanks for the report and sorry for the inconvenience!

**Comment by Owlnofeathers** [comment]
Working great now. Thank you!
