### ISSUE TITLE
net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by williamqian** [itsgoingd/clockwork#336]
when I open app/__clockwork/app?dark# in chrome，the network show these errors

![image](https://user-images.githubusercontent.com/19399075/61282149-64b23880-a7ed-11e9-9bb9-38deb19ebf10.png)

**Comment by lachlankrautz** [comment]
I'm getting the same error here.

Looks like it's assuming localhost:8000 instead of using the `app_url`. Ironically the part of the image you blurred likely contains the answer.

**Comment by williamqian** [comment]
> I'm getting the same error here.
> 
> Looks like it's assuming localhost:8000 instead of using the `app_url`. Ironically the part of the image you blurred likely contains the answer.

thanks for your answer，but my APP_URL is not 127.0.0.1:8000

**Comment by lachlankrautz** [comment]
I know I'm saying the library is using `127.0.0.1:8000` instead of the correct value which would be in your `app_url`.

**Comment by lachlankrautz** [comment]
For now it'll work if you roll back to v3.

**Comment by williamqian** [comment]
> For now it'll work if you roll back to v3.

Thank you very much！it works now

**Comment by itsgoingd** [comment]
Oops, a wrong file found its way into release in 4.0.2. Tagged 4.0.4 with a working version. Thanks for reporting!
