### ISSUE TITLE
Error: Web UI is empty. Ajax is showing error in the empty method

### ISSUE THREAD

**Issue by eduardodgarciac** [itsgoingd/clockwork#342]
I am on php5.6 and the **Clockwork\Storage\Search.php:83** is throwing an error in the empty method. Seems like php5.6 cant use native method names in the classes. If you change the method name, it works correctly.

**Comment by itsgoingd** [comment]
Fixed in master, thanks. Let me know if you run into any more 5.6 issues.

**Comment by eduardodgarciac** [comment]
Thank you. Sure, for now everything's working fine
