### ISSUE TITLE
clockwork:clean command does nothing

### ISSUE THREAD

**Issue by judahnator** [itsgoingd/clockwork#344]
Versions:
------------
* Laravel: 5.8.30
* Clockwork: 4.0.7 (also tested 4.0.6)

Command run:
-------------------
All of:
```
php artisan clockwork:clean
php artisan clockwork:clean -a
php artisan clockwork:clean -e 1
```

Expected behaviour:
--------------------------
The command deletes the JSON files in the storage/clockwork directory

Actual behaviour:
----------------------
No files are deleted

**Comment by itsgoingd** [comment]
Are you upgrading from Clockwork 3 by chance? In that case you need to remove the old data manually one time.
