### ISSUE TITLE
Clockwork shows performance alert, but no details

### ISSUE THREAD

**Issue by sebastiaanluca** [itsgoingd/clockwork#346]
On v4.0.7, Clockwork shows me an alert with a number indicating there's a performance issue, but no details in the pane on the right (above timeline).

<img width="318" alt="Screenshot 2019-08-22 at 14 44 49" src="https://user-images.githubusercontent.com/711940/63515580-73c28f80-c4eb-11e9-9c1d-806644bdb065.png">

If I set the _slow queries_ threshold to 1ms, the alert count increases and I get the details of both the slow queries and the n+1 eager loading performance issues that weren't visible before. It seems they are grouped in a conditional and not shown when the threshold isn't met or there aren't any slow queries?

Our configuration file: https://gist.github.com/sebastiaanluca/1895439d3829c18ab84891b52b40c94e. We're also using Telescope and debug bar, but even with those disabled we don't get the performance details.

**Comment by itsgoingd** [comment]
Thanks for the report. Your assumption is indeed correct, will tag a fixed version in a day or two.

**Comment by itsgoingd** [comment]
Fixed in Clockwork 4.0.8 / Clockwork App 4.0.5.
