### ISSUE TITLE
Your eloquent n+1 doesn't work

### ISSUE THREAD

**Issue by robclancy** [itsgoingd/clockwork#348]
You are checking `getRelationValue` which is called on everything if it is loaded or not. https://github.com/itsgoingd/clockwork/blob/master/Clockwork/DataSource/Concerns/EloquentDetectDuplicateQueries.php#L36

https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L378

And if you go this direction checking the right method to detect if a query is run you will still have issues because you can change a relationship query on the fly. You should be looking at the SQL instead. Same query with different bindings.

**Comment by itsgoingd** [comment]
This definitively needs more work, that's why it's not enabled by default for now.

Looking at the executed queries brings new challenges, like detecting false positives, but might be worth exploring.

**Comment by robclancy** [comment]
Thing is right now basically every query is a false positive. What does the
other library do? I thought you did the same thing so had uninstalled it.

**Comment by itsgoingd** [comment]
Turns out the detection algorithm is fine, I just can't PHP - https://github.com/itsgoingd/clockwork/commit/a2dccd7a95f50bffed5157086291ba63508c59f7

Will tag a fixed version in a moment.

**Comment by robclancy** [comment]
Ah nice.
