### ISSUE TITLE
Not sure if I got it working or not 😞

### ISSUE THREAD

**Issue by ngocphamm** [itsgoingd/clockwork#349]
I'm trying out Laravel 6, as a total newbie to Laravel, and have this in `web.php` route file

```
Route::get('/test', function () {
    clock('test');
    dd('looking for something?');
});
```

I tried both Clockwork add-on/extension for Chrome and Firefox and I don't see anything in the log of the Clockwork tab in DevTools of both browsers.

I also tried to generate the config file with this but I don't see anything being added to `/config` folder as well. The command returned "Publishing complete."

`php artisan vendor:publish --provider="Clockwork\Support\Laravel\ClockworkServiceProvider" --tag=config`

Can anyone please tell me what I did wrong/did not do?

**Comment by ngocphamm** [comment]
I'm still not being able to generate the config, though. Do you have any idea about that @fitztrev ?

**Comment by fitztrev** [comment]
@ngocphamm just use `php artisan vendor:publish` (no flags) and select it from the list

**Comment by ngocphamm** [comment]
Oh... I didn't even know I could just do that without any flags... Thanks a bunch @fitztrev!!!
