### ISSUE TITLE
add model collector?

### ISSUE THREAD

**Issue by kalsolio** [itsgoingd/clockwork#351]
like this [https://github.com/barryvdh/laravel-debugbar/pull/947/files](https://github.com/barryvdh/laravel-debugbar/pull/947/files)

**Comment by itsgoingd** [comment]
Yes, collecting model events is on the roadmap, might happen in 4.1.

**Comment by Sinnbeck** [comment]
Might not be optimal but I added this to my EventServiceProvider to get an overview of models for now :)

```
/**
     * @var UserData
     */
    protected $clock;

    /**
     * @var array 
     */
    protected $models = [];

    /**
     * Register any events for your application.
     *
     * @return void
     */
    public function boot()
    {
        parent::boot();
        $this->clock = clock()->userData('models')->title('Models');

        Event::listen('eloquent.*', function ($event, $models) {
            if (Str::contains($event, 'eloquent.retrieved')) {
                foreach (array_filter($models) as $model) {
                    $class = get_class($model);
                    $this->models[$class] = ($this->models[$class] ?? 0) + 1;
                }
                $this->clock->data($this->models, 'counters')->showAs('counters');
            }
        });

    }

**Comment by mstaack** [comment]
@Sinnbeck this works perfect for me.
@itsgoingd any plans to include this?

**Comment by itsgoingd** [comment]
@mstaack yep! didn't quite make it into 4.1, but will def be done for the next release

**Comment by itsgoingd** [comment]
my initial attempt at implementing this https://github.com/itsgoingd/clockwork/pull/397 (screenshots in the linked app pr)
