### ISSUE TITLE
Clockwork on Lumen: Call to undefined method Laravel\Lumen\Application::configPath()

### ISSUE THREAD

**Issue by codeclem** [itsgoingd/clockwork#354]
I just installed the latest Clockwork 4.0.10 on a fresh Lumen app. I registered the service provider in bootstrap/app.php:

`if ($app->environment('local')) {
    $app->register(Laravel\Tinker\TinkerServiceProvider::class);
    $app->register(Clockwork\Support\Laravel\ClockworkServiceProvider::class);
}`

Then when I run `php artisan vendor:publish` I get this error
`PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Laravel\Lumen\Application::configPath() in /home/user/projects/lumen-app/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:296
Stack trace:
#0 /home/user/projects/lumen-app/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkServiceProvider.php(61): config_path('clockwork.php')
#1 /home/user/projects/lumen-app/vendor/laravel/lumen-framework/src/Application.php(200): Clockwork\Support\Laravel\ClockworkServiceProvider->register()
#2 /home/user/projects/lumen-app/bootstrap/app.php(87): Laravel\Lumen\Application->register(Object(Clockwork\Support\Laravel\ClockworkServiceProvider))
#3 /home/user/projects/lumen-app/artisan(18): require('/home/user/proj...')
#4 {main}
  thrown in /home/user/projects/lumen-app/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 296

In helpers.php line 296:
                                                                                       
  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined m  
  ethod Laravel\Lumen\Application::configPath() in /home/user/projects/magnet-directo  
  ry/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:296                
  Stack trace:                                                                         
  #0 /home/user/projects/lumen-app/vendor/itsgoingd/clockwork/Clockwork/Suppor  
  t/Laravel/ClockworkServiceProvider.php(61): config_path('clockwork.php')             
  #1 /home/user/projects/lumen-app/vendor/laravel/lumen-framework/src/Applicat  
  ion.php(200): Clockwork\Support\Laravel\ClockworkServiceProvider->register()         
  #2 /home/user/projects/lumen-app/bootstrap/app.php(87): Laravel\Lumen\Applic  
  ation->register(Object(Clockwork\Support\Laravel\ClockworkServiceProvider))          
  #3 /home/user/projects/lumen-app/artisan(18): require('/home/user/proj...')   
  #4 {main}                                                                            
    thrown`

Edit: After removing Clockwork and trying to get back to work on my app I had the issue described here https://github.com/laravel/lumen-framework/issues/504 It seems related. I had to nuke composer's cache and the vendor directory to get things working again. See the comment by lsl about half way down that page.

**Comment by itsgoingd** [comment]
Hey, looks like you've registered the Laravel service provider instead of the Lumen one.

**Comment by j-clem** [comment]
Oh jeez. Thank you. 

So that fixed that problem, but I still can't get it to work right. First I got a bunch of 404s on the web frontend assets, so I just manually copied `vendor/itsgoingd/clockwork/Clockwork/Web/public/*` to `public/__clockwork`. Now the interface shows up but it's not responding to any requests I send to the server. Could you share with me the correct steps to setup Clockwork with Lumen? Thank you so much.

**Comment by itsgoingd** [comment]
Are you using the built-in php server? It doesn't process urls with dots (like out web assets) correctly. I'd suggest using a proper web server, though copying the assets should also work.

Can you see any errors or network requests in Dev Tools when you open up the web interface?
