### ISSUE TITLE
Location of `clock()->info()` in Vanilla implementation

### ISSUE THREAD

**Issue by marcus-at-localhost** [itsgoingd/clockwork#359]
I just updated the server-side script to 4.x and noticed that the location of `clock()->info()` in my scripts is not shown first in the Log tab. Was ist always like that?
Is there something I can do to get the right filename:linenumber in the column?
![image](https://user-images.githubusercontent.com/1337223/67050989-7c0c0500-f0ff-11e9-9a24-8c56d8e80852.png)

**Comment by itsgoingd** [comment]
Hey, I can confirm this is a Clockwork issue, will try to get a fix out tomorrow.

**Comment by itsgoingd** [comment]
Just tagged 4.0.13 with a couple of stack trace fixes. Please let me know if it works for you.

**Comment by marcus-at-localhost** [comment]
Just updated to 4.0.13 and unfortunately, nothing changed.

This is the call at line number 378 I expect to see at first position
```php
clock()->info("Sanitize Fields", $this->service['fields']);
```

Is there anything I can try to debug this?

**Comment by itsgoingd** [comment]
Hey, can you try reproducing this in an empty project? I've tested this again and the 4.0.13 release indeed fixes the issue in my test project. The only caveat is you have to have stack traces enabled (which you do have according to the screenshot).

**Comment by marcus-at-localhost** [comment]
I close this, because it seems to be an issue with the implementation in the f3 framework. Thanks.
