### ISSUE TITLE
No connection column in clockwork ?

### ISSUE THREAD

**Issue by sanmusir** [itsgoingd/clockwork#362]
I get no connection column in clockwork  v4.0.13  laravel 5.2
![image](https://user-images.githubusercontent.com/37208700/69324537-9c415d80-0c83-11ea-8f9f-37bcdb84677c.png)

**Comment by itsgoingd** [comment]
Hey, the connection column is shown only when the request has queries from at least two different connections. I also found the latest Clockwork release crashing for me on Laravel 5.2 (tagged a new release with a fix).
