### ISSUE TITLE
Allowed memory size of 536870912 bytes exhausted (tried to allocate 268435456 bytes)

### ISSUE THREAD

**Issue by dev** [itsgoingd/clockwork#364]
Just finished installing clockwork in my projects and looks like it doesn't work for me.
I keep getting memory errors at line 86 of FileStorage:
`$data = @json_encode($request->toArray(), \JSON_PARTIAL_OUTPUT_ON_ERROR);`

![image](https://user-images.githubusercontent.com/12158001/70433405-f6af2c00-1a81-11ea-8d74-f19d2e944508.png)

Running PHP 7.3, Laravel 5.8.35, Vagrant machine (4096 MB memory)

**Comment by itsgoingd** [comment]
Hey, this might happen if Clockwork collects more data than can fit into your memory limit, couple things you can try (most of these can be changed in the Clockwork config):

- increase the `memory_limit` php setting
- disable unnecessary Clockwork features (database queries, etc)
- lower the number of collected frames for stack traces or completely disable collecting of traces
- lower the serialization depth and blackbox additional classes (blackboxed classes don't have contents logged)
- completely disable Clockwork for high memory-intensive endpoints (using filter_uris setting)

**Comment by mahagr** [comment]
@itsgoingd I found a bug which causes this. 

Serializer breaks if you have a nested structure with over than 10 levels.

Let me create a pull request to fix this issue.
