### ISSUE TITLE
Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Redis\RedisManager

### ISSUE THREAD

**Issue by TCM-dev** [itsgoingd/clockwork#368]
I get this error when installing clockwork on lumen.
All I did was installing via composer and adding this line
`$app->register(Clockwork\Support\Lumen\ClockworkServiceProvider::class);`

And the error
`Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Redis\RedisManager`

I thought issue #347 was related but when I try its fix I get another error
`Call to undefined method Redis::enableEvents()`

So I don't really know what I should do :/

> Laravel Framework Lumen (6.2.0) (Laravel Components ^6.0)

**Comment by itsgoingd** [comment]
Thanks for the report, I'll check it out and get back to you soon.

As a workaround you can disable the redis feature of Clockwork in the config file or by setting an env variable `CLOCKWORK_REDIS_ENABLED=false`.

**Comment by itsgoingd** [comment]
I've submitted a PR to Lumen for the first issue (https://github.com/laravel/lumen-framework/pull/1021).

For the second error - do you have the latest Clockwork and illuminate/redis version installed? Can you share your composer.lock?

**Comment by TCM-dev** [comment]
https://pastebin.com/Y65kNd9R Here is my current composer.lock, it should be the same as last time except there is no clockwork anymore. I tried without phpbar too at the time.

**Comment by itsgoingd** [comment]
Clockwork 4.1 has some improvements for Lumen feature detection, please reopen if the issue persists.
