### ISSUE TITLE
Permission error creating storage directory

### ISSUE THREAD

**Issue by mikeerickson** [itsgoingd/clockwork#37]
I have confirmed the parent directory has correct privileges but still receive error?  This is working with Slim framework

var_dump result -->  string '/requests/storage/path' (length=22)

Slim Application Error
The application could not run because of the following error:

Details

Type: ErrorException
Code: 2
Message: mkdir(): Permission denied
File: /Users/mikee/Documents/Projects/slim-clockwork/vendor/itsgoingd/clockwork/Clockwork/Storage/FileStorage.php
Line: 26
Trace
#0 [internal function]: Slim\Slim::handleErrors(2, 'mkdir(): Permis...', '/Users/mikee/Do...', 26, Array)
#1 /Users/mikee/Documents/Projects/slim-clockwork/vendor/itsgoingd/clockwork/Clockwork/Storage/FileStorage.php(26): mkdir('/requests/stora...', 448, true)
#2 /Users/mikee/Documents/Projects/slim-clockwork/vendor/itsgoingd/clockwork/Clockwork/Support/Slim/ClockworkMiddleware.php(32): Clockwork\Storage\FileStorage->__construct('/requests/stora...')
#3 /Users/mikee/Documents/Projects/slim-clockwork/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Clockwork\Support\Slim\ClockworkMiddleware->call()
#4 /Users/mikee/Documents/Projects/slim-clockwork/vendor/slim/slim/Slim/Slim.php(1261): Slim\Middleware\PrettyExceptions->call()
#5 /Users/mikee/Documents/Projects/slim-clockwork/public/index.php(40): Slim\Slim->run()
#6 {main}

**Comment by younes0** [comment]
Clockwork is enabled as middleware but I'm unable to use it for logging variables.
`$app->clockwork->info('test');` results in `Identifier "clockwork" is not defined.`

**Comment by devopsmica** [comment]
This is still an issue for me. My user is part of the www-data group and need to be able to delete the folder (I keep three copies of the site with my CI that deploy my site).

I don't want to run anything as sudo with my deployer user, so it should be able to delete de folder as being part of the www-data group. 

Is there anywhere I can setup that? Thanks
