### ISSUE TITLE
[feature request] routing support for sub domain routing

### ISSUE THREAD

**Issue by chrisLeeTW** [itsgoingd/clockwork#370]
We currently have some routing use Sub-Domain Routing features, and we found out clockwork is not working for this setup.

Hopefully clockwork can support it.

Thanks.

**Comment by itsgoingd** [comment]
Thanks for the request, I'll check it out and get back to you soon.

**Comment by itsgoingd** [comment]
@chrisLeeTW Hey, what exactly doesn't work in your setup?

I've created a sample app and it seems to be working fine, I can see requests from both the main domain and subdomains in both the web UI and the Chrome extension.

**Comment by chrisLeeTW** [comment]
@itsgoingd I thinks maybe the routing register part ?

You currently register route without subdomains (https://github.com/itsgoingd/clockwork/blob/master/Clockwork/Support/Laravel/ClockworkServiceProvider.php#L270)

So for example I have some routing with subdomain "api.127-0-0-1.dev.local", and when clockwork chrome extension try to access routing "http://api.127-0-0-1.dev.local/__clockwork/xxxxxx", and laravel shows that routing is not exists.

**Comment by itsgoingd** [comment]
I've created a new Laravel app, installed Clockwork and used this sample from Laravel docs in my routes file:

```php
Route::domain('{account}.subdomain-test.wip')->group(function () {
    Route::get('/', function ($account) {
        return $account;
    });
});
```

Both `subdomain-test.wip` and `foo.subdomain-test.wip` requests show in Clockwork.

Maybe there is something more to your setup that makes it not work?

I'm happy to look at some code if you can share any or create a non-working example.
