### ISSUE TITLE
Symfony 4/5 support does not work

### ISSUE THREAD

**Issue by llaville** [itsgoingd/clockwork#373]
Hello,

First, thanks for this project that seems really cool for debugging application.

Now, the issue i've found with either Symfony 4 (4.4.3) or Symfony 5 (5.0.3). The code need some patches to be really up and running ! (I could provide some PR to solve it)

I've tested either Firefox or Chrome extensions with same results : 

- Extension display always 
```
Error loading request metadata.
Server returned an error response.
```
While, i found no error in Symfony Profiler or error_log file.

How can we debug and see what happens. Help will be greatly appreciated.

Some screenshots from Chrome 79.0.3945.130 ((64 bits)
I've also tested it with Firefox 72.0.2 (64 bits) that give the same results.

![clockwork_chrome_symfony](https://user-images.githubusercontent.com/364342/73364620-2a9d1580-42ab-11ea-81a7-1465d9f841f9.png)
![symfony_profiler_2840c9](https://user-images.githubusercontent.com/364342/73364631-2ec93300-42ab-11ea-9910-1c7b7480e7e0.png)

**Comment by itsgoingd** [comment]
Hey, thanks for giving it a try!

The best way to get some insight into what's happening would be using the web UI (`your.app/__clockwork`), assuming it works, you can open it in dev tools and see what's going on.

I'm pretty sure this will be some bug on our side, the Symfony support was introduced as "beta" and I didn't have much time to work on it further.

I'll see what I can do to get it working again for the upcoming Clockwork 4.1 release, but unfortunately it's not a very high priority at the moment, since I'm not using Symfony myself and Symfony already has a great profiling tools out of the box.

I'm definitively open to PRs with fixes or improvements for the Symfony support, that would be greatly appreciated.

**Comment by llaville** [comment]
i've already tried the app/__clockwork but it produced none results.
i may be open a PR tomorrow to improve Symfony support and fix some little errors.

**Comment by itsgoingd** [comment]
I've been curious how broken it is and ended up getting it fixed pretty quickly, check out the PR - https://github.com/itsgoingd/clockwork/pull/374

Only a minimal effort to get it working atm, still needs some work.

**Comment by llaville** [comment]
I've just tested your PR #374 with Symfony 4.4.3 and Symfony 5.0.3 and all seems good now. 
The reason why i don't see anything is because i've found as you all files to patch except the `Clockwork/Support/Symfony/Resources/config/routing/clockwork.php`

**Comment by llaville** [comment]
When you tell in PR, that "some UI stuff is still broken" i suppose you make reference to appareance feature setting 

![new-settings-modal](https://user-images.githubusercontent.com/364342/73434335-d9426400-4346-11ea-88c0-1a7be3c3e21d.png)

that is missing (either with Firefox and Chrome extensions)

![extension_ui_setting_issue](https://user-images.githubusercontent.com/364342/73434356-e2cbcc00-4346-11ea-9b7a-86d8b36715cf.png)

**Comment by itsgoingd** [comment]
The appearance settings are new in Clockwork 4.1 which is not released yet.

Some of the issues I found (some might not be Symfony-specific):

- cache queries break timeline because they have wrong start time
- views have NaN rendering time

If you notice anything else, let me know.

**Comment by llaville** [comment]
Another web ui (extension) issue: 
The "clear" button (near preserve log) sometimes clear only the left side panel. I suggest it clear all panels.

Here is an example after pressing clear button 

![clear_request-issue](https://user-images.githubusercontent.com/364342/73531382-a10c5580-441a-11ea-83a2-b8620c76fd68.png)

**Comment by llaville** [comment]
Another Web UI issue : Database time is rounded too much 1ms where in this case it's only around 0.50ms

![database_time](https://user-images.githubusercontent.com/364342/73532339-c601c800-441c-11ea-9890-9d1284c15a13.png)

Confirmed with Symfony Profiler 

![doctrine_profiler](https://user-images.githubusercontent.com/364342/73532462-04978280-441d-11ea-8479-ed745e91b31d.png)

**Comment by llaville** [comment]
Another WebUI issue: 
- When you choose a code editor, but want to revert back to blank (this entry : default, is then missing)

See following screenshot

![code_editor_setting](https://user-images.githubusercontent.com/364342/73853735-a6f6a200-4831-11ea-922c-f9f23b8cd876.png)

**Comment by llaville** [comment]
An issue related this time to Symfony and WebUI:

When you add a specific config file (i.e: `config/packages/clockwork.yaml` in project installed (https://github.com/DamienHarper/doctrine-audit-bundle-demo) that help me to test clockwork SF support.

Content example:  
```yaml
clockwork:
  web_dark_theme: true
```
Symfony confirm (with `bin/console debug:config clockwork` command) that it was accepted
```
Current configuration for extension with alias "clockwork"
==========================================================

clockwork:
    web_dark_theme: true
    enable: true
    web: true
    authentication: false
    authentication_password: VerySecretPassword
```

But when I display WebUI, the URL  is :  "http://doctrine-audit-bundle-demo.local/__clockwork/app?dark"  (?dark)  added ok but it still use light theme

![dark_theme_sf](https://user-images.githubusercontent.com/364342/73855902-00ac9b80-4835-11ea-91ac-5cc93c86a664.png)

I've also tested it with "?dark=1" (as explained https://underground.works/clockwork/web-interface?#content) but it gave same result

**Comment by llaville** [comment]
Deactivate WebUI config issue:

With following yaml config file
```yaml
clockwork:
    web_dark_theme: true
    enable: false
    web: false
    authentication: false
    authentication_password: VerySecretPassword
```
WebUI is still available with empty content. See following screenshot

![disable_webui](https://user-images.githubusercontent.com/364342/73857456-423e4600-4837-11ea-9b9d-01665ede1c0a.png)

Perharps it should be better to have a 404 http status code instead, when `web = false`. What do you think about this ?

**Comment by itsgoingd** [comment]
Additional checks for the "enable" and "web" settings implemented in master. I would prefer to not register the Clockwork routes at all when disabled, but I have no idea how to conditionally register routes in Symfony, might investigate later.

The dark theme setting is no longer relevant, since you can now set the appearance in the Clockwork-app itself. I've removed the setting in master.

**Comment by llaville** [comment]
After Changing password in my yaml config (related to https://github.com/underground-works/clockwork-app/issues/31), i've tested again symfony application with firefox extension.

After submiting good password, the middle panel is not refreshed, while it seems it work good with Chrome.

![firefox_ext_auth_disp_issue](https://user-images.githubusercontent.com/364342/74014081-33b67280-498e-11ea-9858-7402182f7539.png)

**Comment by llaville** [comment]
ping about https://github.com/itsgoingd/clockwork/issues/373#issuecomment-582451971 that is still an issue, even with `itsgoingd/clockwork                 dev-master ab933b7`  commit
