### ISSUE TITLE
Data collection only

### ISSUE THREAD

**Issue by Youniteus** [itsgoingd/clockwork#376]
Is it possible to do data collection only, without exposing the data in the web ui or the Chrome / Firefox plugins?

I understand that I can disable the web ui with `CLOCKWORK_WEB=false` to disable the web ui.
`CLOCKWORK_COLLECT_DATA_ALWAYS=true` with `CLOCKWORK_ENABLE=false` doesn't seem to work.

I'm using Clockwork 4.0.15 with Laravel 6.11.0

**Comment by itsgoingd** [comment]
Hey, your configuration is indeed correct.

There was a bug where "collect data always" didn't work, I've tagged 4.0.16 with a fix.

Thanks for the report!
