### ISSUE TITLE
cleanup for FileStorage is eating memory

### ISSUE THREAD

**Issue by ikkez** [itsgoingd/clockwork#377]
When FileStorage is cleaning up, it's using searchIndex which calls loadRequest (why?) which then json_decodes the request data.. actually, when you only want to clean up the data, it should not load the request data into memory again. I had a folder with ~ 500mb of request data.. impossible to cleanup with clockwork and "only" 128mb php max_memory

**Comment by itsgoingd** [comment]
Good point, this is especially bad since the cleanup can also happen when storing metadata for a request. I'll take a look at this soon.

**Comment by mahagr** [comment]
This may actually be the reason why I've seen memory running out randomly now and then inside clockwork for no apparent reason. Good catch!

**Comment by itsgoingd** [comment]
Made several improvements to the cleanup method in master - https://github.com/itsgoingd/clockwork/commit/74cccaad04597f29e1e3276537fa0948be475b0e

- reading full request metadata is now a separate action from searching the index, so cleanup no longer needs to load full metadata
- cleanup now searches index from the oldest request and stops on first non-expired request, previously was searching from latest two times, so we do much less index reads
- fixed a crash where the index was double closed at the end of cleanup, so it actually works :x

Will back-port this one into 4.0 as well.

**Comment by itsgoingd** [comment]
Tagged 4.0.17.
