### ISSUE TITLE
Bindings in addDatabaseQuery

### ISSUE THREAD

**Issue by tminich** [itsgoingd/clockwork#379]
I might be missing something, but I cannot find bindings displayed anywhere in the database tab in the extensions. The parameter is set (verified in Clockworks sqlite database), so it seems to either be missing in the debugging frontend or, like I said, I'm missing something =)

**Comment by itsgoingd** [comment]
Hey, we actually don't show the bindings anywhere at the moment, sorry for the confusion.

The Laravel integration replaces the bindings directly into the query

https://github.com/itsgoingd/clockwork/blob/master/Clockwork/DataSource/EloquentDataSource.php#L163-L193

You can implement something similar in your database layer, but if you prefer to see the original query and separate bindings in the app, we could definitively add that.

**Comment by tminich** [comment]
Personally I'd prefer to see the raw data so adding a display would be highly appreciated. I sometimes have to deal with legacy code so it can be vital to see which parameters are used via bindings and which are not.

**Comment by itsgoingd** [comment]
Added in master, will be released soon as part of Clockwork 4.1.

<img width="534" alt="Screenshot 2020-02-05 at 00 34 11" src="https://user-images.githubusercontent.com/821582/73797967-b0402a00-47b1-11ea-8c01-69582ec6e8fd.png">

**Comment by itsgoingd** [comment]
Clockwork 4.1 now released.
