### ISSUE TITLE
Xdebug profiler with Symfony application

### ISSUE THREAD

**Issue by llaville** [itsgoingd/clockwork#380]
Hello, 

I've opened a new issue report because i'm pretty sure it's not related to #373.

I've follow instruction to enable xdebug profiler specified in https://underground.works/clockwork/xdebug-profiler?#content, and http://xdebug.org/docs/profiler

Here are my xdebug settings with PHP 7.3.14

![doctrine-audit-bundle-demo_local__profiler_phpinfo](https://user-images.githubusercontent.com/364342/73829106-b90d1c00-4802-11ea-9e34-b992c074cb5c.png)

When I try to read profiler part of performance tab, i see nothing. 
When I click on Enable profiler link, i see it changing to disable profiler than back again to Enable profiler without results (with Web UI only) Firefox extension did not process the link change !

![doctrine-audit-bundle-demo_local___clockwork_app_profiler](https://user-images.githubusercontent.com/364342/73829481-4d777e80-4803-11ea-8fd8-9dc098a04e54.png)

Perharps a regression to issue #277  ?

When I read `http://doctrine-audit-bundle-demo.local/__clockwork/ff2f63` with `ff2f63` is latest SF token used by request (see screenshot), i don't see any xdebug profiler data 

Tests are run with "itsgoingd/clockwork                 dev-fix-symfony-support ef08837"

Did i missed something ?

**Comment by llaville** [comment]
Following this tip in issue #277 

> Alternativaly you can enable Xdebug profiler for all requests by setting xdebug.profiler_enable=1 instead of xdebug.profiler_enable_trigger in your php.ini.

I confirm, that i've cachegrind files produced, but still nothing in WebUI or Firefox extension

**Comment by itsgoingd** [comment]
Hey, unfortunately xdebug is not supported when used with Symfony.

The Symfony integration only translates the data provided by the Symfony profiler, so any feature that requires collecting some Clockwork-specific data (like the xdebug profile path) won't work.

**Comment by melroy89** [comment]
It is now btw: https://symfony.com/blog/new-in-symfony-6-1-profiler-improvements-part-2#xdebug-information-page
