### ISSUE TITLE
Custom data sources

### ISSUE THREAD

**Issue by sinnbeck** [itsgoingd/clockwork#381]
It seems that the documentation for creating custom datasources is outdated?

https://underground.works/clockwork/extending-data-sources?#content

First of all the Request namespace is wrong. Also it does not mention where this addDataSource() should be added. If I add it to the register method of a service provider, it just throws an exception (Target class [queue] does not exist.)

If I do this instead it does not give errors, but there does not seem to come any new tabs?
```
(new \Clockwork\Clockwork())->addDataSource(new ModelDataSource());

**Comment by itsgoingd** [comment]
Hey, indeed the namespace is wrong but the rest of it is correct.

You should avoid calling `clock()` in the register method as all the dependencies might not have been registered at that point (explains the queue error).

The best place to register your custom data sources is in the `boot()` method of your service provider (at this point all service providers are registered), middleware should also work.

I'll update the docs with more details on custom data sources.

**Comment by Sinnbeck** [comment]
Thanks. Sounds good. Looking forward to it. Hope you can write a bit about using this datastream for something. Just logging it, but not outputting the data, isnt that useful :)

I hope to make a proper model datasource (currently I have sort of a hack).

**Comment by Sinnbeck** [comment]
Made a simple data source for models. Not pretty as it has to use userData. But it works :)

```
<?php
namespace App\DataSources;

use Clockwork\Request\UserData;
use Clockwork\DataSource\DataSource;
use Clockwork\Request\Request;
use Illuminate\Contracts\Events\Dispatcher as EventDispatcher;

class ModelDataSource extends DataSource
{
    protected $models = [];
    /**
     * @var \Illuminate\Contracts\Events\Dispatcher
     */
    private $eventDispatcher;

    public function __construct(EventDispatcher $eventDispatcher)
    {
        $this->eventDispatcher = $eventDispatcher;
    }

    public function resolve(Request $request)
    {
        $userData = new UserData();
        $userData->title('Models')->data($this->models, 'counters')->showAs('counters');
        $request->userData = array_merge($request->userData, [$userData]);

//        return $request;
    }

    /**
     * Start listening to eloquent retrieved
     */
    public function listenToEvents()
    {
        $this->eventDispatcher->listen('eloquent.retrieved: *', function ($event, $models) {
            foreach (array_filter($models) as $model) {
                $class = get_class($model);
                $this->models[$class] = ($this->models[$class] ?? 0) + 1;
            }
        });

    }

}
```
And register it in AppServiceProvider::boot
```
$modelDataSource = new ModelDataSource(app('events'));
clock()->addDataSource($modelDataSource);
$modelDataSource->listenToEvents();
