### ISSUE TITLE
Error 500 in lumen 6.3

### ISSUE THREAD

**Issue by MahdiMajidzadeh** [itsgoingd/clockwork#386]
hey

I want use clockwork in lumen but after registered provider, I get server error (500) with no response text.

my lumen version is `v6.3.4` and my clockwork version is `v4.0.17`

**Comment by itsgoingd** [comment]
Hey, you can find more information about the error either in the application log or in your web server's error log.

**Comment by MahdiMajidzadeh** [comment]
that was because of bad file permissions, sorry
