### ISSUE TITLE
Declare required php extensions in composer.jon

### ISSUE THREAD

**Issue by staabm** [itsgoingd/clockwork#388]

**Comment by itsgoingd** [comment]
good point, added in master (https://github.com/itsgoingd/clockwork/commit/b7b7c6792277ae4971646aed223d71f71679a5a6)

the sql file storage also requires pdo and whatever db driver you want to use, but that's entirely optional. i could put those as suggested by composer, but that's just annoying as it's unlikely to be used by most users anyway.

**Comment by staabm** [comment]
Thanks
