### ISSUE TITLE
Lumen 7 no show any request on clockwork..

### ISSUE THREAD

**Issue by maiconmva** [itsgoingd/clockwork#391]
i trying to make with this route test:
![image](https://user-images.githubusercontent.com/5194641/80315160-388c0500-87cc-11ea-8e34-19922cd90ba0.png)

on web: 
![image](https://user-images.githubusercontent.com/5194641/80315153-28742580-87cc-11ea-9625-a65610fc8cf7.png)

the clockwork is returning dd null;

can someone help me?

**Comment by itsgoingd** [comment]
hey, this is expected behavior with dd.

clockwork collects the debugging data in a middleware after the request is finished processing. calling dd will immediately stop php execution, so this part of clockwork code is never run.

**Comment by maiconmva** [comment]
thank you man!! i could fix;
