### ISSUE TITLE
Tabs missing in the clockwork app and the extensions.

### ISSUE THREAD

**Issue by AndreasHotelbird** [itsgoingd/clockwork#396]
I did install clockwork today and it looks like it is working serverside as I did expect it, but I only have three tabs in the app or extension.(Performance, Database, Views)

I am storing data to SQL and I see the logs and events in there but not in the UI. What am i missing?

**Comment by itsgoingd** [comment]
hey, we only show tabs that have some data to show. can you show some examples of what is missing?
