### ISSUE TITLE
Troubles with October CMS and Laravel

### ISSUE THREAD

**Issue by Ilya1vanov** [itsgoingd/clockwork#402]
Hey, guys!
Trying to setup Clockwork for October + Laravel application

`
"laravel/framework": "5.5.48",
"october/rain": "1.0.461",
`

and getting the next error

`[2020-06-19 00:10:36] development.ERROR: ErrorException: array_map(): Expected parameter 2 to be an array, bool given in D:\projects\rump\reg-business-reestr\vendor\itsgoingd\clockwork\Clockwork\Storage\FileStorage.php:134
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'array_map(): Ex...', 'D:\\projects\\rum...', 134, Array)
#1 D:\projects\rump\reg-business-reestr\vendor\itsgoingd\clockwork\Clockwork\Storage\FileStorage.php(134): array_map(Object(Closure), false)
#2 D:\projects\rump\reg-business-reestr\vendor\itsgoingd\clockwork\Clockwork\Storage\FileStorage.php(67): Clockwork\Storage\FileStorage->loadRequests(false)
#3 D:\projects\rump\reg-business-reestr\vendor\itsgoingd\clockwork\Clockwork\Support\Laravel\ClockworkSupport.php(54): Clockwork\Storage\FileStorage->latest(Object(Clockwork\Storage\Search))
#4 D:\projects\rump\reg-business-reestr\vendor\itsgoingd\clockwork\Clockwork\Support\Laravel\ClockworkController.php(33): Clockwork\Support\Laravel\ClockworkSupport->getData('latest', NULL, NULL)
#5 [internal function]: Clockwork\Support\Laravel\ClockworkController->getData('latest', NULL, NULL)
#6 D:\projects\rump\reg-business-reestr\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): call_user_func_array(Array, Array)
#7 D:\projects\rump\reg-business-reestr\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('getData', Array)
#8 D:\projects\rump\reg-business-reestr\vendor\laravel\framework\src\Illuminate\Routing\Route.php(212): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Clockwork\Support\Laravel\ClockworkController), 'getData')
#9 D:\projects\rump\reg-business-reestr\vendor\laravel\framework\src\Illuminate\Routing\Route.php(169): Illuminate\Routing\Route->runController()
#10 D:\projects\rump\reg-business-reestr\vendor\laravel\framework\src\Illuminate\Routing\Router.php(658): Illuminate\Routing\Route->run()
#11 D:\projects\rump\reg-business-reestr\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 D:\projects\rump\reg-business-reestr\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 D:\projects\rump\reg-business-reestr\vendor\laravel\framework\src\Illuminate\Routing\Router.php(660): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#14 D:\projects\rump\reg-business-reestr\vendor\laravel\framework\src\Illuminate\Routing\Router.php(635): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#15 D:\projects\rump\reg-business-reestr\vendor\laravel\framework\src\Illuminate\Routing\Router.php(601): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#16 D:\projects\rump\reg-business-reestr\vendor\october\rain\src\Router\CoreRouter.php(20): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#17 D:\projects\rump\reg-business-reestr\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(176): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#18 D:\projects\rump\reg-business-reestr\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#19 D:\projects\rump\reg-business-reestr\plugins\wedev\manager\middleware\CacheControlMiddleware.php(32): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 D:\projects\rump\reg-business-reestr\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Wedev\Manager\Middleware\CacheControlMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 D:\projects\rump\reg-business-reestr\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 D:\projects\rump\reg-business-reestr\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 D:\projects\rump\reg-business-reestr\vendor\october\rain\src\Foundation\Http\Middleware\CheckForMaintenanceMode.php(24): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 D:\projects\rump\reg-business-reestr\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 D:\projects\rump\reg-business-reestr\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 D:\projects\rump\reg-business-reestr\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 D:\projects\rump\reg-business-reestr\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#28 D:\projects\rump\reg-business-reestr\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#29 D:\projects\rump\reg-business-reestr\index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#30 D:\projects\rump\reg-business-reestr\server.php(18): require_once('D:\\projects\\rum...')
#31 {main}  `

Do you have any idea on what is going on?

**Comment by itsgoingd** [comment]
hey, looks like there is a bug in clockwork where we crash instead of returning an empty array when we have no data to return.

if your app does not collect data make sure the debug mode is enabled and your app does not use dd/dump. you should see files being created in the `storage/clockwork` directory when everything works correctly.

**Comment by Ilya1vanov** [comment]
APP_DEBUG=true
no dumps are used

storage/clockwork has .gitignore and an empty index file

**Comment by itsgoingd** [comment]
this is the middleware where we store the collected data, can you check if this is executed in your app? (with a simple dd call for example)

https://github.com/itsgoingd/clockwork/blob/master/Clockwork/Support/Laravel/ClockworkMiddleware.php#L33

**Comment by Ilya1vanov** [comment]
It is executed.
A new 1592596827-1888-1076300341.json file was created in storage/clockwork. And now the app goes out-of-memory (512M is the current limit). 😕

**Comment by itsgoingd** [comment]
you can find some tips on lowering memory usage when using clockwork here

https://github.com/itsgoingd/clockwork/issues/364#issuecomment-564735519

first thing i would try is disabling "events" in the features configuration in case october emits a lot of custom events (not very familiar with october, just a guess).
