### ISSUE TITLE
Allow filtering requests by method

### ISSUE THREAD

**Issue by mortenscheel** [itsgoingd/clockwork#404]
It would be nice to be able to filter requests by method.
With cross-origin AJAX requests, clockwork logs every single OPTIONS preflight request, which is kind of meaningless. Maybe these should be ignored except if explicitly included in a config setting.

**Comment by itsgoingd** [comment]
hey, ability to filter requests by closure is already on the todo list  (https://github.com/itsgoingd/clockwork/issues/403)

ignoring pre-flight requests by default makes a lot of sense, adding that one as well. i've never noticed this being an issue with laravel though, are you using the vanilla integration?

**Comment by mortenscheel** [comment]
I'm using Sanctum for auth on the backend, and the frontend is a SPA on a different subdomain. Hence the cross-origin requests.

**Comment by itsgoingd** [comment]
i've released clockwork 4.1.6 with support for filtering requests by method (options requests are filtered by default)
