### ISSUE TITLE
Explain database queries

### ISSUE THREAD

**Issue by yhortuk** [itsgoingd/clockwork#407]
It would be great to have an option to unable query explain in database tab to efficiently gain performance insights on particular query.

I've implemented rough solution for laravel as data source plugin, but this feature seems a good candidate to be in a core.

**Comment by itsgoingd** [comment]
hey, this was suggested before and i've decided to not pursue it at that time (https://github.com/itsgoingd/clockwork/issues/281), though i'm open to ideas on how to make it work.

**Comment by yhortuk** [comment]
@itsgoingd missed this one, thanks for the link with clarification. I'll close for now
