### ISSUE TITLE
Guzzle requests logging

### ISSUE THREAD

**Issue by yhortuk** [itsgoingd/clockwork#408]
On my current project I got a lot of requests to internal and external apis and it's a huge pain to debug and inspect those calls. I thought it can be displayed as guzzle log in clockwork (request, timing, response). It's most common library for http commutation so it makes sense for me to have it.

Also, very common use case for me as well as it might be for other developers is to share misbehaving call to third party api. It can be implemented as "copy as curl" action in clockwork listing described above. Package https://github.com/namshi/cuzzle can help achieve this use case.

**Comment by itsgoingd** [comment]
hey, there is a 3rd party package for collecting guzzle requests - https://github.com/hannesvdvreken/guzzle-clockwork

copy as curl - sounds pretty useful, you should suggest it for the guzzle-clockwork library

**Comment by yhortuk** [comment]
It makes sense to make proposal on this package repository, thanks.
