### ISSUE TITLE
Weird Bug "Call to a member function getParent() on null"

### ISSUE THREAD

**Issue by mstaack** [itsgoingd/clockwork#414]
Don't know how to really reproduce this, but it started to appear the last days:

![image](https://user-images.githubusercontent.com/10169509/89764334-7d764600-daf4-11ea-9bfa-a30811874640.png)

```
laravel/framework                        v7.24.0
laravel/nova                             v3.8.2
itsgoingd/clockwork                      v4.1.6
```

clearing cache / deleting storage files does not help :/

any hints/ideas?

**Comment by itsgoingd** [comment]
hey, will check this out soon, in the meantime you can turn off the duplicate queries detection:

```
CLOCKWORK_DATABASE_DETECT_DUPLICATE_QUERIES=false
```

**Comment by mstaack** [comment]
thanks this helps for now 👍

**Comment by mstaack** [comment]
i feel it has something todo with nova

**Comment by Sinnbeck** [comment]
Not using Nova and I am getting it from time to time.

**Comment by itsgoingd** [comment]
Released Clockwork 4.1.7 with an additional check to avoid the crash. I would still like to know why the stack frame object would be null, but I guess that will remain a mystery.

**Comment by Sinnbeck** [comment]
I managed to get my debugger to catch it. In my case it seems to be triggered by spaties permissions package.

http://i.imgur.com/3wkFDaZ.png
http://i.imgur.com/eCpZuPe.png

**Comment by itsgoingd** [comment]
Ah, it's a static call so there is no object instance. Very useful, will investigate further, thanks.

**Comment by Sinnbeck** [comment]
Disabling clockwork, refreshing, and enabling it again solves the issue (temporarily)

**Comment by mstaack** [comment]
great so see some investigations & improvements 🚀
