### ISSUE TITLE
I get performance panel only.

### ISSUE THREAD

**Issue by qingfengbaili** [itsgoingd/clockwork#416]
laravel version : v7.25.0
php version : 7.4.7

## I did these steps

1. `composer require itsgoingd/clockwork`
2. open `http://localhost:8090/__clockwork/app#`

So,I can not see database panel.

![image](https://user-images.githubusercontent.com/44765369/90973915-fe075e80-e558-11ea-9b25-649f8a9337e6.png)

Is there something wrong with my operation?

Thank you.

**Comment by itsgoingd** [comment]
Hey, are you using Eloquent on that page? We only show the tabs when we have some data to show.

**Comment by qingfengbaili** [comment]
## test1(from frontend)
This is my request.
![image](https://user-images.githubusercontent.com/44765369/91118380-683c1280-e6c3-11ea-8c3a-003f591c06e0.png)
And There are some data in the response.
![image](https://user-images.githubusercontent.com/44765369/91118400-7427d480-e6c3-11ea-9789-c5805c8af1a2.png)

Then, I open clockwork page.
![image](https://user-images.githubusercontent.com/44765369/91118574-d7196b80-e6c3-11ea-8795-ccd3cf3686bb.png)


## test2(from nova)
Open resource index page.
![image](https://user-images.githubusercontent.com/44765369/91118716-29f32300-e6c4-11ea-9298-e4ad0ae876b3.png)

Still no tabs.
![image](https://user-images.githubusercontent.com/44765369/91118762-48591e80-e6c4-11ea-8885-c6625de1b094.png)

**Comment by itsgoingd** [comment]
Hmm, this is a weird one, can you send me a sample file from `storage/clockwork` to `info@underground.works`?

Did you customize your Clockwork config? Are you doing something or using some third-party packages that might interfere with Laravel's database stuff? Do you see a log tab if you try logging something, eg. `clock('foo')`?

**Comment by qingfengbaili** [comment]
An email has been sent.

I use default config. I don't even have a configuration file in my config dir.

This is my composer file.No interference I guess.
![image](https://user-images.githubusercontent.com/44765369/91256602-54171480-e79a-11ea-9154-b70dd48edbb4.png)

**Comment by qingfengbaili** [comment]
May is there some necessary php-extensions I forgot add?
I run my app in docker container. And I only opened thoes php-extensions than I need.

**Comment by itsgoingd** [comment]
Thanks for sharing the debugging data, unfortunately I'm not much wiser as for what the issue might be. You don't need any special php extensions or settings. I'm afraid we'll have to dig into the code to find out what's wrong.

Looks like we don't collect database queries at all in your app. Can you `dd` the condition here to see if it passes?

https://github.com/itsgoingd/clockwork/blob/v4/Clockwork/Support/Laravel/ClockworkServiceProvider.php#L92

If it *does not* pass, can you check this statement?

https://github.com/itsgoingd/clockwork/blob/v4/Clockwork/Support/Laravel/ClockworkSupport.php#L339

If it *does* pass, can you check if this method is ever called?

https://github.com/itsgoingd/clockwork/blob/v4/Clockwork/DataSource/EloquentDataSource.php#L89

**Comment by qingfengbaili** [comment]
Oh sorry. I am sure it is a docker issue.Pls close it.

**Comment by bhyordi** [comment]
Was checking clockwork out and had the same issue (only performance tab). I'm not using docker or any virtulization, just laragon (which uses a WAMP stack).
Using a dd() in my page would result in clockwork not even picking it up.
I must confess i de-installed it, i have not time to sort this out :D sorry

Note: i still have debugbar + telescope installed when testing (maybe this could help you)

**Comment by mpemberton5** [comment]
I know this is closed, but had the same issue.  Fixed by running **`php artisan config:clear`**

Hope it helps others!
