### ISSUE TITLE
array_combine(): Both parameters should have an equal number of elements is back

### ISSUE THREAD

**Issue by mahagr** [itsgoingd/clockwork#418]
It happens randomly in Grav 1.7 admin with v4.1.7 …/vendor/itsgoingd/clockwork/Clockwork/Storage/FileStorage.php line 285

Parameters for me are:

```
array:8 [▼
  0 => "id"
  1 => "time"
  2 => "method"
  3 => "uri"
  4 => "controller"
  5 => "responseStatus"
  6 => "responseDuration"
  7 => "type"
]

array:11 [▼
  0 => "1582548042-5053-611931862"
  1 => "1582548042.501"
  2 => "POST"
  3 => "/admin/pages/core/modular/_callout.json1582891095-7666-622537541"
  4 => "1582891095.76"
  5 => "GET"
  6 => "/plugins/shortcode/ui"
  7 => ""
  8 => "200"
  9 => "87.949991226196"
  10 => "request"
]
```

**Comment by itsgoingd** [comment]
Hey, looks like your index file got corrupted by Clockwork writing metadata from two requests at the same time.

We try to avoid this issue using file locks, but the code was a bit too optimistic and didn't handle the case where we fail to acquire the lock at all.

Can you please try updating to 4.1.8 and see if it helps?

**Comment by mahagr** [comment]
I will, thanks!

**Comment by mahagr** [comment]
It looks like the issue has been fixed, thanks!

**Comment by mahagr** [comment]
Nope, I just got the error again from the latest clockwork. :(

**Comment by itsgoingd** [comment]
Forgot to tell you to manually delete `storage/clockwork` contents after the update. Once the index file becomes corrupted it has to be manually removed. Let me know if this helps.

**Comment by carlosmolano** [comment]
Hi..
cd ../storage/clockwork
find . -type f -delete

Sometimes the files are corrupt, or may not be able to be removed ... it worked for me by removing the contents of the folder.

**Comment by mahagr** [comment]
Unfortunately deleting the cached entries doesn't help, it will still happen every few minutes if you use the dev site heavily.

**Comment by itsgoingd** [comment]
What platform and filesystem are you using?

I guess we'll just have to fix the symptom with better error handling when reading from the index for now. I would much prefer finding the root cause which is corrupting the index, bud I'm kinda out of ideas atm.

**Comment by itsgoingd** [comment]
Tagged 5.0-beta1 with improved handling of corrupt index records.

**Comment by mahagr** [comment]
Let me try it out. I'll report back what happens.

**Comment by mahagr** [comment]
Converted the code to work with 5.0..

One note: you removed `Clockwork->userData()` method, why? It's not a biggie, though, I'm getting it from the request now.

**Comment by itsgoingd** [comment]
The main Clockwork class now dynamically forwards unknown method calls to the request instance, so you should still be able to call `$clockwork->userData()`.

https://github.com/itsgoingd/clockwork/blob/master/Clockwork/Clockwork.php#L221-L229

Breaking changes with links to some documentation can be found at https://underground.works/clockwork/beta, there will also be a proper upgrade guide on release.

**Comment by mahagr** [comment]
You should probably add some docblock entries for the unknown methods so that PhpStorm sees them.

I would also add phpstan tests and typehints, it really helps to find the bugs in the code!

Thanks for the docs, I'll take a look into them.

**Comment by itsgoingd** [comment]
Have you had any further issues with the index file on 5.x?

**Comment by mahagr** [comment]
I had some issues not too long ago, but with the 2 latest versions none yet. Though I haven't used it enough to know if the issue has been fixed or not.

**Comment by mahagr** [comment]
Looks like the issues may have been fixed in the latest releases. Closing the issue.
