### ISSUE TITLE
Minor documentation fix

### ISSUE THREAD

**Issue by mattbit** [itsgoingd/clockwork#420]
Hi, very nice project!

I was integrating clockwork with a legacy project by manually recording the queries following the instructions on https://underground.works/clockwork.

You present this code snippet:
```php
function database_query($pdo, $query, $bindings) {
   $time = microtime(true);
 
   $stmt = $pdo->prepare($query);
   $stmt->execute($bindings);
 
   $results = $stmt->fetchAll();
 
   clock()->addDatabaseQuery($query, $bindings, microtime(true) - $time);
 
   return $results;
}
```

but according to the `Clockwork::addDatabaseQuery` definition, you need to pass the duration in  **milliseconds** (`microtime` is returning seconds). At first I got very surprised by the _absolutely incredible_ speed of my queries, then I noticed this discrepancy… a factor 1000 should be added to the time:
```
clock()->addDatabaseQuery($query, $bindings, 1000 * (microtime(true) - $time));
```
or alternatively it should be done in the `addDatabaseQuery`.

**Comment by itsgoingd** [comment]
Hey, good catch, thanks!

Haha, I get confused about which values are in milliseconds and which in seconds myself all the time.

Fixed the example for now, hopefully I can open-source the website soon so you can send a PR and get a credit next time. :)

**Comment by mattbit** [comment]
That's great, thank you!
