### ISSUE TITLE
Use is_dir() and is_file() instead of file_exists()

### ISSUE THREAD

**Issue by staabm** [itsgoingd/clockwork#433]
.. file_exists() is up to 100 times slower

Inspired by https://bugs.php.net/bug.php?id=78285

See also https://github.com/symfony/symfony/issues/36493

**Comment by itsgoingd** [comment]
I've actually seen this before, but couldn't reproduce the improvement at the time. Will re-do some benchmarks myself, since the linked bug report looks pretty convincing. Thanks.

**Comment by itsgoingd** [comment]
Changed for Clockwork 5.3 (https://github.com/itsgoingd/clockwork/commit/12d40a21e8a15571eb18ff7f03bcb29b9d8287f3).
