### ISSUE TITLE
Composer install out of memory

### ISSUE THREAD

**Issue by juhasev** [itsgoingd/clockwork#435]
php-fpm /var/www/html composer require itsgoingd/clockwork

Using version ^4.1 for itsgoingd/clockwork
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)

PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleWatchGraph.php on line 52

**Comment by itsgoingd** [comment]
Hey, this is not really related to Clockwork, but a Composer issue in general. I'd suggest trying out Composer 2 beta (`composer self-update --2`), which has been much faster with much lower memory usage for me.

**Comment by juhasev** [comment]
Thanks will do. I had to boost PHP memory limit to 2GB to get this working. That is certainly too much!
