### ISSUE TITLE
Performance monitoring GET requests (5.0)

### ISSUE THREAD

**Issue by sinnbeck** [itsgoingd/clockwork#439]
After upgrading to v.5.0 the performance tab is suddenly empty for all GET requests. POST requests have data though. Strangely, if I click on a POST request and then a GET request, the data is transfered over. I have tried installing the client metrics npm package and importing it.

I am unsure how to debug it, but I will happily give a hand in doing to.

Edit: I managed to find what causes the issue. If I disable `detect_duplicate_queries` the performance screen is rendered correctly.

**Comment by itsgoingd** [comment]
Hey, thanks for finding time to debug and report this. Will try to replicate and fix later today. Also tagging first patch releases today/tomorrow.

**Comment by itsgoingd** [comment]
Fixed in 5.0.1, thanks for reporting!
