### ISSUE TITLE
userData tabs missing in Clockwork 5.0.1

### ISSUE THREAD

**Issue by martbean** [itsgoingd/clockwork#440]
Hi,

My application logs additional data to new tabs using userData() and this had been working fine but since the Firefox addon updated to v5.0.1 these tabs are missing. I can still see other data in the Performance and Database tabs and if I var_dump() the Clockwork object I can see my custom data in the userData() array, so it's definitely being added.

PHP 7.2.34
Vanilla PHP app
Clockwork server-side v4.1.8
Firefox 83.0

Any ideas?

Thanks,
Martin.

**Comment by itsgoingd** [comment]
Hey, I can confirm this is a bug in the Clockwork App and will be fixed in the next patch release. In the meantime you can use the v4 server-side web ui (http://your.app/__clockwork/app).

**Comment by martbean** [comment]
Excellent, thanks!

**Comment by itsgoingd** [comment]
Fixed in 5.0.2, thanks for reporting!

**Comment by martbean** [comment]
Amazing, thanks! Just updated the add-on and can confirm I've got my userData tabs back 👍

**Comment by mahagr** [comment]
Confirmed to be fixed.
