### ISSUE TITLE
Xdebug profiler checkbox flickers on and off

### ISSUE THREAD

**Issue by AlexGodbehere** [itsgoingd/clockwork#442]
I've installed the profiler as outlined in the documentation but when I try to enable it the checkbox flickers on and off and requests are not captured by clockwork. If I disable it, all works as expected.

PHP: **7.4.9**
Clockwork: **5.0.1**

<img width="323" alt="Screenshot 2020-11-23 at 22 24 56" src="https://user-images.githubusercontent.com/6726523/100022250-bce24d00-2dda-11eb-8b24-58a25bc9403f.png">
<img width="323" alt="Screenshot 2020-11-23 at 22 24 56" src="https://imgur.com/VupTtwb.gif">

**Comment by itsgoingd** [comment]
Hey, the flickering is a known UI issue, it should have no effect on the functionality though. Did the requests execute successfully after enabling the profiler? Can you see new files being created in `storage/clockwork`?

Btw. loading of existing profiles is broken atm, should not affect collecting of profiles though https://github.com/itsgoingd/clockwork/issues/441

**Comment by AlexGodbehere** [comment]
If I try to reload the page with the profiler enabled (but still flickering), I can confirm I get an `XDEBUG_PROFILE = 1` header in the requests.

The `storage/clockwork` directory contains over 240 `.json` files, despite being empty before the initial page refresh. The Clockwork dashboard shows 6 requests, each taking 10x longer than usual (although this could be a result of the behaviour that I'm trying to debug).

**Comment by itsgoingd** [comment]
Can you reproduce the broken requests list on the first screenshot? You can send me some sample `.json` files to `info@underground.works`.

The requests taking 10x longer is indeed a normal thing with the Xdebug profiler enabled and a sign that it works (this overhead is from Xdebug itself, not Clockwork related).

**Comment by AlexGodbehere** [comment]
I can't seem to reproduce the strange requests in the first screenshot and the multiple requests seem to have been a one-off thing!

If the flickering is a known issue then I'm happy to close this.

**Comment by itsgoingd** [comment]
The flickering should be fixed in 5.0.2 btw.
