### ISSUE TITLE
Clockwork 5.0: No duration for events?

### ISSUE THREAD

**Issue by mahagr** [itsgoingd/clockwork#443]
Clockwork app has option to display events inside the timeline, but it looks like enabling that feature will just break timeline (no entries shown in the next request).

`Request::addEvent()` is also missing logic to add `end` and/or `duration`, which makes no sense.

**Comment by itsgoingd** [comment]
Hey, can you post an example of what are you trying to do?

Just to clarify, there are two different things referred to as "events" in Clockwork:

- timeline events - the bars on the timeline, just presentational, no semantic meaning, added by `clock()->event()` api
- application events - application events in event-based applications (eg. a `UserRegistered` event), shown in a separate tab and on timeline, added by `Request::addEvent()` api

Duration for `Request::addEvent()` api can be added.

**Comment by mahagr** [comment]
I'm adding PSR-14 events into the Events tab of the Clockwork. They appear there just fine, but they are not added into the timeline. Thus filtering by events of the main Performance tab and clicking on the Events breaks the timeline on the next page load.

**Comment by itsgoingd** [comment]
I can reproduce the timeline issue, will be fixed in the next patch release.

**Comment by itsgoingd** [comment]
Fixed in 5.0.2, `Request::add*` apis now also all have support for start/duration. Thanks for reporting!

**Comment by mahagr** [comment]
Fixed in release.
