### ISSUE TITLE
[Idea] Redis Storage Engine?

### ISSUE THREAD

**Issue by hailwood** [itsgoingd/clockwork#446]
So I haven't looked into this much but had a thought that clockwork data is exactly the kind of transient data that redis is good at storing and quickly.
Do you think it would be possible to create a storage driver that works based off Redis?

**Comment by itsgoingd** [comment]
Hey, yes it's not only possible, but pretty easy to do.

The storage sub-system is extensible, Redis was one of the future implementations I had in mind while designing it, just never got around to implement it. We already have an SQL storage implementation that can be used as a reference. Search might be awkward to implement in Redis, but that's optional anyway.
