### ISSUE TITLE
cant composer install on php8

### ISSUE THREAD

**Issue by stillzombie** [itsgoingd/clockwork#447]
when running:

`composer require itsgoingd/clockwork`

got errors:

  Required parameter $message follows optional parameter $level 

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

**Comment by itsgoingd** [comment]
Hey, just tagged 5.0.3 that should be PHP8 compatible.

**Comment by stillzombie** [comment]
hey great, really cool job man!

**Comment by stillzombie** [comment]
Works like a charm!

**Comment by zschuessler** [comment]
Thanks for the fix! Works for me, too

Any chance of keeping the issue open for visibility until its merged into a release? This would let others trying to search for known issues to find it in the Open issues list :)

**Comment by itsgoingd** [comment]
The fix is already released, good idea to pin this issue for a bit anyway as people might try to use 4.x with PHP 8.
