### ISSUE TITLE
Releases are missing since 4.1.6

### ISSUE THREAD

**Issue by mahagr** [itsgoingd/clockwork#448]
See https://github.com/itsgoingd/clockwork/releases, there are only tags, no releases.

**Comment by itsgoingd** [comment]
Yeah, I'll fill those out later today. I always forget to update the releases and website, need to automate these. The up-to-date changelog is always in the repo:

https://github.com/itsgoingd/clockwork/blob/master/CHANGELOG.md

**Comment by itsgoingd** [comment]
All repositories have had all release notes added, thanks for the reminder!

**Comment by mahagr** [comment]
TY!
