### ISSUE TITLE
BUG: Call to undefined method Clockwork\DataSource\LumenDataSource::getMethod()

### ISSUE THREAD

**Issue by alexbegoon** [itsgoingd/clockwork#450]
Hi,

Found a bug using Lumen `Call to undefined method Clockwork\DataSource\LumenDataSource::getMethod()`. [Source](https://github.com/itsgoingd/clockwork/blob/master/Clockwork/DataSource/LumenDataSource.php#L93)

- laravel/lumen-framework: v8.2.1
- itsgoingd/clockwork: v5.0.3

**Comment by itsgoingd** [comment]
Fix included in the 5.0.4 release, thanks!
