### ISSUE TITLE
Breaks on PrimaryKey with an array value

### ISSUE THREAD

**Issue by Binternet** [itsgoingd/clockwork#453]
When Enabling clockwork, I'm getting
`array_key_exists(): The first argument should be either a string or an integer `

You can see the flare here:
https://flareapp.io/share/w5BYyA87#F65

**Comment by itsgoingd** [comment]
Hey, looks like you are overriding some Eloquent behavior in your `BusinessToCity` model, which causes `$model->getKey()` to crash (possibly setting `$primaryKey` to null?). I would need to see the full source of that model to help more, if you want to share privately you can use `info@underground.works` or discord.

**Comment by Binternet** [comment]
@itsgoingd oh, my `$primaryKey` is an array with two entries, I guess thats the reason.

**Comment by itsgoingd** [comment]
I don't think Laravel supports non-string primary keys (at least the docblock says so). If you have some custom implementation for that, you have to make sure the `getKey()` method also works.

**Comment by Binternet** [comment]
It is, see https://stackoverflow.com/a/37076437/999270

**Comment by itsgoingd** [comment]
Well, your solution unfortunately breaks standard Eloquent api, nothing we can fix on our side.

**Comment by Binternet** [comment]
Got it, will think of a workaround. Thanks.
