### ISSUE TITLE
Feature : toolbar support for vanilla integration

### ISSUE THREAD

**Issue by reeslo** [itsgoingd/clockwork#455]
Can you add toolbar support for vanilla integration ? 

Thanks :)

**Comment by itsgoingd** [comment]
As I've said in Discord, I'm down to add this. Little busy right now, but I should have some time later this week.

**Comment by itsgoingd** [comment]
Added in 5.0.5, also added client-metrics and better PSR-7 support while at it, enjoy. :)

**Comment by reeslo** [comment]
Thanks 😊 I will check that after holidays !  And thank you for your nice work !
