### ISSUE TITLE
Feature: Magento 2 extension

### ISSUE THREAD

**Issue by michaellehmkuhl** [itsgoingd/clockwork#456]
New to Clockwork, but I'm impressed with the ease of use and existing framework support. It sure would be cool if there was a pre-built integration with Magento 2, though.

**Comment by itsgoingd** [comment]
Hey, a first-party integration is unlikely to happen as I have no experience with Magento and the maintenance burden would be too high. If there is someone who would like to build an integration I'd be happy to help however I can though.

**Comment by michaellehmkuhl** [comment]
I completely understand. I may even take a stab at developing the integration myself. Thanks for a really great tool.

**Comment by itsgoingd** [comment]
If you or anyone else would like to work on a new integration, I'd recommend joining our [Discord](https://discord.gg/NUuCGE4). There we can have a chat and come up with a plan on how to best tackle this. As long as you have a really good understanding of the integrated platform, the Clockwork part is actually pretty simple.

If there is ever a well-maintained third-party Magento (or any other) integration created, I will happily promote it in Clockwork docs as an "official" installation option.

**Comment by itsgoingd** [comment]
@INPVLSA Looks great, thanks for making it! Linked on the [Clockwork website](https://underground.works/clockwork/#docs-extensions) as well.
