### ISSUE TITLE
Enabled profiler triggers Xdebug on chrome-extension calls

### ISSUE THREAD

**Issue by Defimas** [itsgoingd/clockwork#458]
Enabling profiler within the chrome-extension forces Xdebug to trigger profiling (xdebug.start_with_request=trigger) by the extensions own "__clockwork" calls.
Througth its polling behavior cachegrinds start to pile up, which i dont think is intended?

**Comment by itsgoingd** [comment]
Hey, this is definitively not intended. We explicitly remove the trigger cookie when doing metadata requests, can you inspect one of the profiles to make sure it's caused by Clockwork?

**Comment by Defimas** [comment]
Trigger is present.

![cl](https://user-images.githubusercontent.com/50416302/102788554-14a4b180-43a3-11eb-9aaf-87a1b64eb87d.jpg)

**Comment by itsgoingd** [comment]
This should be fixed in Clockwork 5.3 (https://github.com/underground-works/clockwork-app/commit/cda016c0759c160e3981ada44584ebecbb23a84d).
