### ISSUE TITLE
Laravel + Clockwork + Chrome not working

### ISSUE THREAD

**Issue by JasonMortonNZ** [itsgoingd/clockwork#46]
So after many hours of frustration here's where I'm at.

1) Brand new installation of Laravel 4 (v4.1.21)
2) Added `"itsgoingd/clockwork": "1.*"` to my composer.json file.
3) Ran composer update and Clockwork (v1.4.4) installed.
4) I added the `'Clockwork\Support\Laravel\ClockworkServiceProvider'` to my providers array, and added `'Clockwork' => 'Clockwork\Support\Laravel\Facade',` to my aliases array.
5) I added the following to my `app/filters.php` file:

```
App::before(function($request)
{
Event::fire('clockwork.controller.start');
});


App::after(function($request, $response)
{
Event::fire('clockwork.controller.end');
});
```

5) Ran a `composer dump-autoload -o` for good measure.
6) Next I boot up laravel using `php artisan serve` and we're running on (localhost:8000).
7) I hit `localhost:8000` in chrome, check the headers and here's where things get strange :)

The headers read:

`X-Clockwork-Id:1392079506.9878.449334262`
`X-Clockwork-Version:1.4.2`

**Note:** Composer installed Clockwork v1.4.4 , which is weird?

This is from my composer.lock file:

```
    "name": "itsgoingd/clockwork",
        "version": "v1.4.4",
        "source": {
            "type": "git",
            "url": "https://github.com/itsgoingd/clockwork.git",
            "reference": "2d39c88ba507fde4bd21b11971e429762303224c"
        }
```

I hit the clockwork tab in Chrome (Version 32.0.1700.107) and nothing appears.

I do at this point have `.json' files in`app/storage/clockwork` containing all the correct data that should be being displayed by the Chrome extension.

A few points where I feel the issue could be laying are:

1) The use of PHP's built-in web server?
2) Using SQLite as the database driver of choice?
3) Chrome on Ubuntu LInux (which I am using).

I've seen other's mention that white space has been an issue for them, but this isn't the case here. I'll be interested to see if there's a solution to this.

**Comment by xalloa** [comment]
In my case it was a problem with the mod_rewrite rule. I mention that just in case.

**Comment by trevorgehman** [comment]
@xalloa How did you correct the mod_rewrite issue you had?

**Comment by xalloa** [comment]
@trevorgehman in my case a colleague had "installed" the web app at a subdir ( webform.int ) so I wrote a rule specific to the clockwork path like that:

```
RewriteRule ^.*__clockwork/(.*)$ /webform.int/index.php/__clockwork/$1 [L] 
```

hope this helps though it is a workaround and not the solution (i.e. I have not fixed the original rule that caused the problem since i didn't had the time to).

**Comment by trevorgehman** [comment]
I actually discovered my issue was I had to clear the route cache with
```
php artisan route:cache
```

**Comment by xalloa** [comment]
Nice, I'll give it a try, however or other reasons we are running on nginx now so I have left mod_rewrite alone :smile:

**Comment by bcalik** [comment]
I have the same problem.

I have several laravel websites with same nginx configuration, all is working well but one of them does not work *(which was actually working well previously. A lot of development is going on this project, so I don't know what caused Clockwork to stop working.)* 

Interesting thing is, **[clockwork-cli](https://github.com/ptrofimov/clockwork-cli) is working well**, but the **chrome extension does not work** for this project. It just doesn't show anything.

**Comment by bcalik** [comment]
**Ok I have found the issue.**

I have created a singleton named 'app'. Which causes the Clockwork error like this:
`Argument 1 passed to Clockwork\Support\Laravel\Controllers\LegacyController::__construct() must be an instance of Illuminate\Foundation\Application, instance of stdClass given``

Here is the code caused the issue:
```php
  App::singleton('app', function(){
    $app = new stdClass;
    ...
    return $app;
  });
  $app = App::make('app');
```
