### ISSUE TITLE
marginal vs. meaningfull event indication

### ISSUE THREAD

**Issue by staabm** [itsgoingd/clockwork#465]
looking at the timeline all events, no matter how long they take, look similar:

![grafik](https://user-images.githubusercontent.com/120441/103036825-e376dd80-456a-11eb-8808-64cfc688756f.png)

though, there are events which are more interessting performance wise then others.
events taking only a few ms are not important comparing to those taken tenth or even hundreds of ms.

maybe it would make sense to get some inspiration by e.g. blackfire.io which gives color-wise indication when events are more important then others

example blackfire.io callgraph:
![grafik](https://user-images.githubusercontent.com/120441/103036982-3781c200-456b-11eb-836e-839a54c7a897.png)

the more pink, the more important is the element within the blackfire.io graph.

**Comment by itsgoingd** [comment]
Revisiting this old issue, but I'm not sure what the idea is here. We represent the timeline events as bars, where the bar length is determined by how much time the event took. I feel like this makes it very clear, what the important events are.
