### ISSUE TITLE
[DOC] Wrong instructions for vanilla setup

### ISSUE THREAD

**Issue by bbalet** [itsgoingd/clockwork#466]
I took me a while to understand what was going wrong. In https://underground.works/clockwork/#docs-installation-vanilla you suggest this init code:

    $clockwork = Clockwork\Support\Vanilla\Clockwork::init([
       'storage' => 'sql',
       'storage_database' => 'sqlite:' . __DIR__ . '/clockwork.sqlite'
    ]);

but `storage_database` param doesn't exist, it is `storage_sql_database` instead

**Comment by itsgoingd** [comment]
Oops, I've changed that example completely to use a more common configuration option.
