### ISSUE TITLE
BUG : Xdebug 3 - Not compatible

### ISSUE THREAD

**Issue by neopheus** [itsgoingd/clockwork#468]
Hi,

I have a problem with Xdebug 3, with this configuration :
```
xdebug.mode=debug
xdebug.start_with_request=trigger
```
same problem with mode profile
Clockwork isn't compatible with Xdebug 3

Have you a solution ?

Thx

**Comment by kw-pr** [comment]
I think `xdebug.mode=debug` is wrong. I am using `xdebug.mode=profile` see https://xdebug.org/docs/all_settings#mode

phpinfo() shows: Profiler | ✔ enabled

Still clockwork profile does not load "Profile is not present for current request"

I guess there is some other issue.

**Comment by neopheus** [comment]
I confirm ;)

**Comment by peterthomson** [comment]
Yep. The config settings to turn on profiling have changed in Xdebug 3. And it seems that the way the output is generated may have changed because even when I manually enable profiling, the output isn't displayed in Clockwork in the way it used to with Xdebug 2.

**Comment by tsukasagenesis** [comment]
Same there, it doesn't work anymore, and unfortunately xdebug 3 is now the default on ppa:ondrej/php that everyone on debian base use to get recent release :/

**Comment by askvortsov1** [comment]
> Ok it work, just have to setup correctly the trigger.
> 
> In the php.ini right after opcache:
> zend_extension=xdebug.so
> xdebug.mode=profile
> xdebug.start_with_request=trigger
> xdebug.trigger_value=secrettrigerhere
> 
> then call a page with xdebug_info(); inside and ?XDEBUG_TRIGGER=secrettrigerhere, you should get "Profile File" not empty and set to a path.
> 
> But there is still a bug tho, the time is not correct :
> 
> ![21-02-2021-09-26-15](https://user-images.githubusercontent.com/374009/108619706-da00d900-7426-11eb-81cc-f0280668f925.png)

I'm experiencing these issues as well

**Comment by itsgoingd** [comment]
Hey, looks like Xdebug 3 changed the measurements accuracy from *1 ms* to *10 ns*, so the displayed values are 100 times larger than they should be, eg. *579.3ms* in the screenshot is really *579.3 * 10 ns*, or *5.793 ms*. This will be updated in the next minor Clockwork release to correctly convert to ms.

Btw. if you remove `xdebug.trigger_value` from your configuration you will be able to control whether profiling is active from the Clockwork UI, otherwise the configuration is correct.

**Comment by ajcastro** [comment]
@itsgoingd  I want to see xdebug profiler when running tests. How can I solve it? Thanks! I am also using xdebug 3 and latest clockwork version

**Comment by itsgoingd** [comment]
Fixed in Clockwork 5.1, both Xdebug2 and high-precision Xdebug3 metrics are correctly displayed.
