### ISSUE TITLE
get the whole trace

### ISSUE THREAD

**Issue by matthiouze** [itsgoingd/clockwork#470]
Hi,

I have a problem with laravel and clockwork (using couchbase).
I'm using laravel as api and I wanted to install clockwork to have performances (I had to edit the vendor folder).

I've have succed to install it and I get all queries.
I'ld like to know if there is a possibility to see what the framework does because I only can see what my controller does.

![Sans titre](https://user-images.githubusercontent.com/1607309/104019444-dc330f00-51bb-11eb-8835-d183b018fd9e.png)

In production the servor is good and I still have a TTBF too high even if I skip the controller part.
With controller 1.7s
Without 1s

Hope to get help,

Thanks

**Comment by itsgoingd** [comment]
Hey, the "Controller" event starts as soon as the Clockwork middleware is executed. Following happens before that:

- register method on all service providers is executed
- boot method on all service providers is executed
- middleware registered before Clockwork is executed

If I had to hazard a guess, I'd say you or some package you use is doing something expensive when booting a service provider (eg. database queries, etc.). This could also point to a configuration or HW issue, eg. Xdebug or slow IO might slow down request execution by a lot.

Unfortunately it's awkward to debug these kinds of issues with Clockwork, as the slow-down happens before Clockwork is even initialized.
