### ISSUE TITLE
Sublime URL handler that is suggested in the Clockwork UI has been abandoned 

### ISSUE THREAD

**Issue by peterthomson** [itsgoingd/clockwork#472]
The current suggestion in the Clockwork UI goes to:
https://github.com/asuth/subl-handler

That package no longer works on current gen Operating Systems. Based on my research, I'd suggest we send instead people to:
https://github.com/inopinatus/sublime_url

Or alternatively, just suggest that they search git for a "Sublime URL Handler".

**Comment by itsgoingd** [comment]
Hey, thanks for the suggestion. Will test it out and update the suggestion in the next minor release.

**Comment by itsgoingd** [comment]
This was done in Clockwork 5.1.
