### ISSUE TITLE
Web UI custom path

### ISSUE THREAD

**Issue by haleemhosein** [itsgoingd/clockwork#473]
```
/*
|------------------------------------------------------------------------------------------------------------------
| Enable web UI
|------------------------------------------------------------------------------------------------------------------
|
| Clockwork comes with a web UI accessibla via http://your.app/clockwork. Here you can enable or disable this
| feature. You can also set a custom path for the web UI.
|
*/

'web' => env('CLOCKWORK_WEB', true),
```

How do I set a custom path for the web UI?
I tried `'web' => 'http://localhost/myapp/v1/',`, but this did not work 😢 

Laravel Framework 5.7.29
PHP 7.4.13
Clockwork 5.0.6

**Comment by itsgoingd** [comment]
Hey, you've almost got it, it's a uri without the host part, in your case: `'web' => 'myapp/v1',`.

**Comment by haleemhosein** [comment]
Thank you. I did this, but if I click the little blue arrow for the toolbar, it takes me to the wrong URI.
![image](https://user-images.githubusercontent.com/59444383/105351163-9108fb00-5bc2-11eb-8a61-bca866eb6914.png)

How can I configure this button's URI?

**Comment by itsgoingd** [comment]
I don't think we support custom paths in toolbar atm, will look into improving that for the next release.

**Comment by haleemhosein** [comment]
Ok thanks, appreciate it man!
