### ISSUE TITLE
No events for an Artisan commands with dd()

### ISSUE THREAD

**Issue by GeorgII-web** [itsgoingd/clockwork#474]
Have no new json files in storage/clockwork while exec an artisan commands if there is a dd() or die().
May be not issue, but needs to be added to the documentation.

**Comment by itsgoingd** [comment]
Hey, yeah, this is correct behavior, calling `die` stops the script execution immediately. I'll add a little faq section to the documentation for common questions like this one.

**Comment by itsgoingd** [comment]
The documentation has been updated.
