### ISSUE TITLE
Desktop App

### ISSUE THREAD

**Issue by jonorozcoc** [itsgoingd/clockwork#476]
It would be awesome to have a desktop app in order to use this tool for API's

**Comment by itsgoingd** [comment]
Hey, you can already use the web UI for apis. Just go to `http://your.app/clockwork` and you'll see all requests made against your app.

I've actually [prototyped a dedicated desktop app](https://twitter.com/itsgoingd/status/1348041451616301059/photo/1) a while ago, but have no plans to finish it atm, as it has no real advantage over using the web UI. Might reconsider if there is enough interest or I can think of some cool desktop-specific feature.
