### ISSUE TITLE
Wrong Closure

### ISSUE THREAD

**Issue by hferradj** [itsgoingd/clockwork#478]
Hi,

https://github.com/itsgoingd/clockwork/blob/1de3f9f9fc22217aa024f79ecbdf0fde418fc0a1/Clockwork/Request/Timeline/Event.php#L50

This should be `\Closure` instead of `Closure`, otherwise it's taken from the wrong namespace.

**Comment by hferradj** [comment]
This triggers an error - because it tries to use `Closure` from the `Clockwork\Request\Timeline` namespace (which does not exist).

The function signature should be `public function run(\Closure $closure)` to use Closure from the global namespace.

![image](https://user-images.githubusercontent.com/7561279/109918143-f24ae080-7ccf-11eb-9da1-452dfe7abe94.png)

**Comment by itsgoingd** [comment]
Hey, thanks for the report. This is fixed in master and will be released soon.

**Comment by itsgoingd** [comment]
Included in Clockwork 5.0.7.
