### ISSUE TITLE
sentMessage: Undefined array key -1

### ISSUE THREAD

**Issue by beekmanbv** [itsgoingd/clockwork#479]
I'm using Clockwork version 5.0.6 and Laravel version 8.27.0

When I use $this->dispatchSentEvent($message) (laravel/framework/src/Illuminate/Mail/Mailer.php) I get this error:

![image](https://user-images.githubusercontent.com/32930324/107656650-aaaed700-6c84-11eb-9176-c2fc1a20354c.png)

Hope someone can help me.
Thanks

**Comment by itsgoingd** [comment]
Hey, what does your code triggering the mail sending looks like?

**Comment by itsgoingd** [comment]
Released Clockwork 5.0.7 with a couple of improvements and fixes for notifications collecting, which should also fix your issue.
