### ISSUE TITLE
Would you consider publishing assets sources

### ISSUE THREAD

**Issue by rtripault** [itsgoingd/clockwork#480]
Hi,

First of all, much thanks for the work done on this project, i've been enjoying playing with it lately (with Slim).

I was wondering if you considered open sourcing the assets sources (JS/CSS), since only the minified versions are available.

This could allow people to ship their tweaks easily (if need be), and hopefully might help people submit fixes/proposals/contributions upstream.

Many thanks

**Comment by itsgoingd** [comment]
Hey, the Clockwork client-side app is already open-source, you can find it here:

https://github.com/underground-works/clockwork-app

This single repository is used to build both the web app and the browser extensions. You can find some instructions on how to build the final app in the readme. It's built with vue-cli, so you can also check out their docs on how to use it for development.

**Comment by rtripault** [comment]
oh! Sorry for missing that! Many thanks for your fast reply
