### ISSUE TITLE
ErrorException Undefined offset: 1

### ISSUE THREAD

**Issue by iainheng** [itsgoingd/clockwork#481]
Hi, I am using Laravel 7.x with clockwork v5.0.6. I am getting this `ErrorException Undefined offset: 1` in file `vendor/itsgoingd/clockwork/Clockwork/DataSource/LaravelNotificationsDataSource.php:227` whenever I turn on clockwork on my server. The `APP_DEBUG` is set to `true`. 

![image](https://user-images.githubusercontent.com/3263759/108395153-74f38a80-7250-11eb-89bf-536fc28f1346.png)

This is the `toMail()` inside my `Notification` class 

![image](https://user-images.githubusercontent.com/3263759/108395684-0236df00-7251-11eb-86b4-3d3d69a02c0c.png)

Thanks. Hope it helps.

**Comment by itsgoingd** [comment]
Hey, thanks for the report, will be fixed soon.

**Comment by itsgoingd** [comment]
Released Clockwork 5.0.7 with a fix.
