### ISSUE TITLE
unable to share log? Too big?

### ISSUE THREAD

**Issue by MattAppleton** [itsgoingd/clockwork#482]
I am using Clockwork to help debug a GRAV page that is taking a while to save... great extension and tool!! Thanks!

 — but I don't seem to be able to share the logs etc.. is that because they are too big

**Steps**
1. Open Clockwork, save a page in GRAV
2. Hit the 'Share' button after the page finishes saving (35secs!)

It then spins indefinitely... 
Any settings I should tweak to try fixing this?

I can get basic 'Performance' output (https://clockwork.underground.works/share/nbocwail) but no more than this so far...

**Comment by itsgoingd** [comment]
Hey,

it is definitively possible for it to be too large, the limit is 8MB of metadata at the moment. I believe you should get an error message if that is the case though.

Can you check the network tab to see what happens with the ajax request sending the metadata?

**Comment by mahagr** [comment]
Metadata size is usually about 150-200KB for Grav.
