### ISSUE TITLE
No connector for [azure]

### ISSUE THREAD

**Issue by nomad23** [itsgoingd/clockwork#483]
Hi,

Apologies for this if I'm doing this wrong.
While using https://github.com/squigg/azure-queue-laravel  for Azure Queues, clockwork cannot find the connector. 
I believe this might be linked to the issue raised here: https://github.com/vyuldashev/laravel-queue-rabbitmq/issues/32 for rabbitMQ in laravel 5.8 and it is the only reference I can find on the same.

All other providers ( redis, sync etc ) work well. 
Any suggestions for laravel 7?

**Comment by nomad23** [comment]
Quick update:

After moving it down the list in bootstrap/cache/services, it works.
It appears the issue is that when Clockwork is loaded before the queue provider, it doesn't capture the connection.
Leaving this issue open for any feedback, questions or comments.

![image](https://user-images.githubusercontent.com/2137137/109384075-82b5a980-78fb-11eb-97c0-75ba934074ea.png)

**Comment by itsgoingd** [comment]
Hey, yeah I've run into this issue with a different package (https://github.com/itsgoingd/clockwork/issues/464), your workaround is exactly what I would suggest.

**Comment by itsgoingd** [comment]
Fixed in master (https://github.com/itsgoingd/clockwork/commit/2d7ec7587536ef31edd79965b11f4587217c29be), will be included in the next minor release.

**Comment by nomad23** [comment]
> Fixed in master ([2d7ec75](https://github.com/itsgoingd/clockwork/commit/2d7ec7587536ef31edd79965b11f4587217c29be)), will be included in the next minor release.

Thank you!!
