### ISSUE TITLE
Very limited data when running Feature Tests

### ISSUE THREAD

**Issue by AAllport** [itsgoingd/clockwork#485]
Whilst running unit test's there is extremely limited usefulness for clockwork.

For context, the test that is being run includes adding some data to the db, and then making some requests to verify the response of an endpoint.
However, when running the test, I'm only seeing the entry below.

I've verified that I'm seeing what I'm expecting to see when running it outside of a test environment (sending a request to the same endpoint) is working correctly.
Test's are being run via PHPStorm's PHPUnit runner.
I've also made sure I have the `setupClockwork` call in `setup`

I would be expecting to see (at the least) a tab for database queries since that's what I'm currently trying to debug

I believe clockwork should be showing the database queries for (at least) the request the test is making.
Is this a bug? Or should this be a feature request?

Example: 
![image](https://user-images.githubusercontent.com/3750120/109843857-7440f800-7c43-11eb-9d22-5d5e77011dae.png)

**Comment by SimBig** [comment]
@AAllport is it possible that you did not publish the config file. I am observing the same behaviour when the `CLOCKWORK_TESTS_COLLECT` is set to false (defaults to false if you have not published/modified the config file).

https://github.com/itsgoingd/clockwork/issues/559

**Comment by antongorodezkiy** [comment]
@AAllport To record tests you will need to make changes to your test file like stated in the docs - https://underground.works/clockwork/#docs-collected-data

> To collect data about ran tests, you also need to add and boot a Clockwork testing trait in your tests/TestCase.php:


```
use Clockwork\Support\Laravel\Tests\UsesClockwork;
 
abstract class TestCase extends BaseTestCase
{
    use CreatesApplication, RefreshDatabase, UsesClockwork;
 
    protected function setUp() :void
    {
       parent::setUp();
       $this->setUpClockwork();
    }
}
```

**Comment by itsgoingd** [comment]
I would need to see some reproduction code for this one, please feel free to reopen if this is still an issue.
