### ISSUE TITLE
How can I enable toolbar on my custom project

### ISSUE THREAD

**Issue by abramov-ks** [itsgoingd/clockwork#486]
I'm not using awesome frameworks but clockwork works with chrome extension.
I want to enable toolbar on my project, but doesn't know how.

I just added script from CDN but it doesn't affect

**Comment by itsgoingd** [comment]
Hey, previously you'd also need to enable it server-side. I've just released 5.0.7, which enables it by default, so it should start working after the update with no changes required.

**Comment by abramov-ks** [comment]
Nice. I see it correctly, but it doesn't work for my SPA app.
First, it's frozen and show only info about first request (it was loaded from ./clockwork.php correctly). But it doesn't refreshes after next XHR requests. So, may be I need to fire some event while I make XHR requests ?

Second, If I click "show details" it redirects me to /clockwork route, but I don't have it. Is it possible to make custom panel like chrome extension looks ?

Thanks for your work!

**Comment by itsgoingd** [comment]
It does not currently show XHR requests, which I guess makes it not very useful for SPAs. The toolbar is supposed to be a simple addition to the full Clockwork UI, not a replacement. I will see if we can improve things for the next release though.

The "show details" button opens the Clockwork web app, which is not supported in the vanilla integration atm. I've already did some work on this, so you can expect it being added in a future release.

**Comment by itsgoingd** [comment]
Vanilla web UI is now available in Clockwork 5.1.
