### ISSUE TITLE
Turning off "Keep requests log" in web interface causes endless refreshing

### ISSUE THREAD

**Issue by piperone** [itsgoingd/clockwork#489]
Thanks for this awesome set of debugging tools! They look and work great!

I've been having one issue lately though. I'm not sure if I'm doing something wrong or where exactly the issue is, but when I disable the "Keep requests log"-option and refresh a clockwork-enabled page a couple of times, the web interface keeps refreshing and showing an empty GET request. I attached a video below showing the issue (this was on the clockwork website).

https://user-images.githubusercontent.com/351744/112738019-87ec2f80-8f5f-11eb-8640-ceca800e8bbd.mp4

I tried disabling all browser extensions. Tested in Firefox 88.0b3 and Chrome 89.0.4389.90 on macOS 11.2.3. With the "Keep requests log"-option enabled, this doesn't happen.

Thanks again!

**Comment by itsgoingd** [comment]
Hey, thanks for the report, "keep requests log" currently only works in the extension, where we use the webextension apis to track when the user navigates to a new page.

In a future release we should either implement a different solution for the standalone version or just hide the option.

**Comment by itsgoingd** [comment]
Fixed in Clockwork 5.1.
