### ISSUE TITLE
Lumen: An error occurs when calling the command, job

### ISSUE THREAD

**Issue by 2Attack** [itsgoingd/clockwork#490]
Hi, i found bug

`Call to a member function getStatusCode() on null {"exception":"[object] (Error(code: 0): Call to a member function getStatusCode() on null at /var/www/project/vendor/itsgoingd/clockwork/Clockwork/DataSource/LumenDataSource.php:144)`

Need fix method getResponseStatus in LumenDataSource like in LaravelDataSource -> `return $this->response ? $this->response->getStatusCode() : null;`

**Comment by itsgoingd** [comment]
Fixed in master, thanks!

**Comment by itsgoingd** [comment]
Fixed in the 5.0.8 release.
