### ISSUE TITLE
Clockwork headers are not set and clockwork tab is empty Nginx

### ISSUE THREAD

**Issue by creativedevs** [itsgoingd/clockwork#495]
Hi,

I am using nginx , laravel 8 and clockwork latest version

I am getting clockwork tab empty, and clockwork response headers are not set as well.

Created folder in stoage/clockwork with 755 permission. but still same.

It is working fine in local with apache. Is ther any setting needs to do in nginx?

**Comment by itsgoingd** [comment]
Hey, no there is no configuration specific to nginx.

Make sure Clockwork is actually working (files are being created in `storage/clockwork`), note that Clockwork is by default enabled only when the application is in the debug mode.
