### ISSUE TITLE
404 Files Using Web interface in Lumen

### ISSUE THREAD

**Issue by luciano-work** [itsgoingd/clockwork#500]
I have two APIs using `Lumen` and I'm trying to use Clockwork.
when I try to access the web interface I receive 404 error for some files (css and js)

![image](https://user-images.githubusercontent.com/12519008/118818362-a1886400-b88a-11eb-862d-69ac746efe4a.png)

All the API's are using PHP 7.3 and Lumen ^8.0
There is something to fix this problem?

All the best.

**Comment by itsgoingd** [comment]
Hey, this unfortunately won't work with the built-in php server (`php -S`), because of limitations when serving uris with dots. Should work fine with a real web server like nginx.

**Comment by luciano-work** [comment]
Hi @itsgoingd,
Clockwork is an amazing tool, please is there anything to make this work using php artisan serve?
All the best!

**Comment by itsgoingd** [comment]
It should work fine with Laravel's artisan serve, I don't believe Lumen has such command.

**Comment by luciano-work** [comment]
I am using this lumen packge that also has the command artisan serve
https://github.com/flipboxstudio/lumen-generator

**Comment by itsgoingd** [comment]
That just uses the built-in php server with a public dir, which won't work with Clockwork unfortunately. I'd recommend using a real web server like nginx even for development.

**Comment by luciano-work** [comment]
Thank you @itsgoingd
