### ISSUE TITLE
Does the asterisk have any special meaning?

### ISSUE THREAD

**Issue by pys1992** [itsgoingd/clockwork#505]
I'm just curious.😅
![image](https://user-images.githubusercontent.com/44765369/120090413-ef2b8900-c134-11eb-8004-3940d39462b0.png)

**Comment by itsgoingd** [comment]
Hey, yes indeed it does. The asterisk prefixed attributes are protected, tilde prefixed attributes are private and public attributes have no prefix.

**Comment by pys1992** [comment]
Got it.
