### ISSUE TITLE
Error with SQL Server

### ISSUE THREAD

**Issue by urielgi** [itsgoingd/clockwork#508]
Good day

Everything works fine with MySQL, but when using it with SQL Server I get the following error:
_array_key_exists(): The first argument should be either a string or an integer_

I thought it was my mistake when creating the database query, but when I uninstalled Clockwork everything works fine. Is Clockwork incompatible with SQL Server?

IIS: 8.5
PHP: 7.4.1
Laravel: 8.49.2
Clockwork: 5.0.7

Greetings

(Sorry for my bad English)

**Comment by itsgoingd** [comment]
Hey, would you be able to send a full stack trace for that error? Unfortunately I don't have a Windows Server setup to reproduce.

**Comment by urielgi** [comment]
Good day.  Yes, it's ok. I attach a file with the full stack trace.

[SQL Server Trace.txt](https://github.com/itsgoingd/clockwork/files/6849324/SQL.Server.Trace.txt)

Regards.

**Comment by itsgoingd** [comment]
Thanks for the trace, this does not look like a Clockwork issue though. Looks like either your app uses some non-standard Eloquent setup in regards to primary keys or it might be an actual Laravel bug (unlikely).
