### ISSUE TITLE
Extension shows nothing, No tabs, no data. 

### ISSUE THREAD

**Issue by JackJohansson** [itsgoingd/clockwork#509]
I've installed the browser extension on FireFox, Chrome and MS Edge. I can't seem to be able to use it at all. There are no tabs ( only performance ). and there's no content in that tab either. None of the buttons work either. 

I tried reinstalling it but no avail. The same exact issue exists across all the browsers.

Could this possibly be an OS issue? I was using it on my macOS but I don't have access to my mac now, so I installed it on a computer running Windows 7, which doesn't work.

Here's an screenshot:

![clockwork](https://user-images.githubusercontent.com/29520157/126898464-d2570666-c809-4ac2-bec6-812cdcf52476.jpg)

There are no files related to clockwork under this directory: 

User\AppData\Local\Microsoft\Edge\User Data\Default\Storage

Clockwork used to show some basic information about any websites, but nothing now.

**Comment by itsgoingd** [comment]
Hey, does your web app have the Clockwork server-side library correctly installed?

If you'd just want to try if the extension works you can try it on https://underground.works/clockwork/, which has Clockwork server-side installed.

**Comment by phuhung273** [comment]
@itsgoingd please help me, i have Clockwork installed using composer, default config. But it only shows performance tab!
![image](https://user-images.githubusercontent.com/40334379/143731137-a60f8eb9-16d9-4dd4-b57e-f1f267c28a9d.png)

**Comment by JackJohansson** [comment]
@itsgoingd Sorry I forgot that I posted here! My issue was that clockwork wasn't enabled. It worked fine after enabling it.

@phuhung273 Did you try on a fresh Laravel installation? Did you try it on a different browser? You could narrow down the issue, to figure out if it's related to the plugin, Laravel, or the browser.

**Comment by rvanbaalen** [comment]
@JackJohansson how did you enable it? I have it installed and APP_DEBUG=true but no Clockwork data is showing up in the extension.

**Comment by rvanbaalen** [comment]
Update; for me, installing the latest version of Clockwork server-side did the trick. Removed the package and installed the latest. I think the versions were out of sync somehow.

**Comment by LeToyek** [comment]
I have same issue untill now but I've already installed clockwork through composer and it show nothing
![image](https://user-images.githubusercontent.com/88649781/209981029-c1f29e05-488d-499d-90f0-29635a05e3d8.png)

**Comment by y1n0** [comment]
this issue has driven me crazy for the past hour.. make sure to set env variable CLOCKWORK_ENABLE to true.. it is only became after v5.2
