### ISSUE TITLE
FileStorage->cleanup() missing oldest file

### ISSUE THREAD

**Issue by ssnepenthe** [itsgoingd/clockwork#510]
I noticed this on my own custom implementation but just confirmed the same is happening on a fresh laravel install with the latest version of clockwork.

When using file storage with an expiration of 0 and calling ->cleanup(true) (i.e. running php artisan clockwork:clean --all), the index is cleared out and all of the metadata files are removed except for the oldest one.

Expected behavior is for all metadata files to be removed.

To reproduce, create a fresh laravel install, install clockwork, run the dev server, visit the site and refresh a few times to generate a few metadata files and then inspect the storage/clockwork directory.

<img width="303" alt="Screen Shot 2021-08-03 at 8 58 27 PM" src="https://user-images.githubusercontent.com/10903810/128120139-a955c38e-d312-4b2f-aa08-90eb171f604d.png">

<img width="702" alt="Screen Shot 2021-08-03 at 8 58 40 PM" src="https://user-images.githubusercontent.com/10903810/128120158-ec38b103-5abc-416a-90fe-9bba133baa73.png">

Now run php artisan clockwork:clean --all and re-inspect the storage/clockwork directory:

<img width="280" alt="Screen Shot 2021-08-03 at 9 01 20 PM" src="https://user-images.githubusercontent.com/10903810/128120295-7e070412-c1dc-405a-9dd8-44c8d24d1a8a.png">

<img width="593" alt="Screen Shot 2021-08-03 at 9 01 31 PM" src="https://user-images.githubusercontent.com/10903810/128120300-5fc95096-ee9c-49fa-b5aa-d24e0ec1f42a.png">

**Comment by itsgoingd** [comment]
This should be now also fixed by fixing the mentioned issue.
