### ISSUE TITLE
DB tab always shows same file: EventDispatcherDecorator 

### ISSUE THREAD

**Issue by hcivelek** [itsgoingd/clockwork#513]
I used to see the file that was responsible for the query. But now just the EventDispatcherDecorator file showing.

![image](https://user-images.githubusercontent.com/371721/128788745-8bde91f4-9fcc-4cc1-abb7-792cee5d2c24.png)

**Comment by itsgoingd** [comment]
Hey, there is no EventDispatcherDecorator in Clockwork and it doesn't seem to be part of Laravel either. Is this something from your application or from some other package?

**Comment by hcivelek** [comment]
Yes, you are right. It belonged to this: https://github.com/lorisleiva/laravel-actions
Thank you very much.
