### ISSUE TITLE
Possible null value provided to SqlSearch::fromBase()

### ISSUE THREAD

**Issue by ssnepenthe** [itsgoingd/clockwork#520]
There are four storage methods that accept an optional/nullable search parameter.

In the SqlStorage implementation, that search parameter is then passed to SqlSearch::fromBase() which does not accept a null value.

**Comment by itsgoingd** [comment]
Looks like the only thing we can do is to remove the type-hint from `SqlSearch::fromBase` (the lowest PHP version we support does not have nullable type-hints unfortunately).

Will gladly accept a PR for this.

**Comment by ssnepenthe** [comment]
We don't have nullable type-hints as in `?Search $search` but we should still be able to use the implied nullable by setting a null default as in `Search $search = null`. In fact it looks like this is already what you are doing in `StorageInterface`.

I will send a PR for you to take a look at.

**Comment by ssnepenthe** [comment]
#524
