### ISSUE TITLE
Eloquent/DB database queries

### ISSUE THREAD

**Issue by rikiless** [itsgoingd/clockwork#525]
I am using vanilla PHP application with DB/Eloquent integration. Is there easy way to configure clockwork to log these database queries?

**Comment by itsgoingd** [comment]
Yeah, that should be possible, assuming you are using the capsule setup from the readme here - https://github.com/illuminate/database (you will also need the optional events part).

Here is an idea how to make it work (not tested):

```php
$dataSource = new Clockwork\DataSources\EloquentDataSource(
    $capsule->getDatabaseManager(),
    $eventDispatcher
));

$clockwork->addDataSource($dataSource);

$dataSource->listenToEvents();
```

**Comment by rikiless** [comment]
thanks
