### ISSUE TITLE
"Show details" link is wrong

### ISSUE THREAD

**Issue by superDuperCyberTechno** [itsgoingd/clockwork#530]
The toolbar links to a relative path rather than the root of the app to load the Clockwork webapp.

Simply prepending a slash to the href attribute in the script (https://cdn.jsdelivr.net/gh/underground-works/clockwork-browser@1/dist/toolbar.js) fixes it for me.

**Comment by itsgoingd** [comment]
Fixed in https://github.com/itsgoingd/clockwork/pull/542, link will now be absolute and work with subdirs.
