### ISSUE TITLE
Can't install for latest Laravel on PHP 8.0.8 (PSR version incompatible)

### ISSUE THREAD

**Issue by byGits** [itsgoingd/clockwork#533]
Title says it all, here is a screenshot as well:
![2021-10-13-glxa7](https://user-images.githubusercontent.com/53629749/137064793-6c8fcff2-34a6-48e8-8017-19e6d2d88144.jpg)

**Comment by kkame** [comment]
After removing the composer.lock file, try reinstalling it? Often times, problems can arise if you install with a psr/log:1.* dependency in composer.lock. This is not a clockwork issue.

**Comment by itsgoingd** [comment]
Sorry for taking so long, but psr/log 2.0 compatible Clockwork version has just been released. You should be able to install Clockwork in the latest Laravel again with no issues.
