### ISSUE TITLE
PHP 8.1 - PDO::quote():  Passing null to parameter #1 ($string) of type string is deprecated in  /vendor/itsgoingd/clockwork/Clockwork/DataSource/EloquentDataSource.php  on line 271

### ISSUE THREAD

**Issue by Codomic** [itsgoingd/clockwork#544]
I'm getting this Warning after upgrading to php 8.1:

PDO::quote():  Passing null to parameter #1 ($string) of type string is deprecated in  /vendor/itsgoingd/clockwork/Clockwork/DataSource/EloquentDataSource.php  on line 271

Any quick fix?

**Comment by itsgoingd** [comment]
Hey, thanks for the report, will fix later today.

**Comment by itsgoingd** [comment]
Fixed in Clockwork 5.1.2.
