### ISSUE TITLE
preg_match and str_replace error 

### ISSUE THREAD

**Issue by Pinnokkio** [itsgoingd/clockwork#549]
I'm using latest version of laravel.
![image](https://user-images.githubusercontent.com/83555759/146673866-cee0c4ee-d692-4998-88e8-8f60fb3ff231.png)

**Comment by itsgoingd** [comment]
Hey, thanks for the report, fixed in master (https://github.com/itsgoingd/clockwork/commit/df3a7c15358627ebc6d3144985ff721be1e84873), will be released shortly.
