### ISSUE TITLE
BUG with log

### ISSUE THREAD

**Issue by Wit3** [itsgoingd/clockwork#550]
Hi, i i try to log everything with

`clock($variable);`

that not is a string, receive this message.

```
TypeError
Psr\Log\AbstractLogger::debug(): Argument #1 ($message) must be of type Stringable|string, array given, called in /var/www/html/vendor/itsgoingd/clockwork/Clockwork/Clockwork.php on line 230
```

Version used Latest 5.1.2 ( same with 5.1.1 )

**Comment by itsgoingd** [comment]
Hey, thanks for the report. This is now fixed in master (https://github.com/itsgoingd/clockwork/pull/551) and will be released shortly.
