### ISSUE TITLE
change the middleware priority

### ISSUE THREAD

**Issue by williamqian** [itsgoingd/clockwork#554]
How to set the \App\Http\Middleware\PreventRequestsDuringMaintenance before ClockworkMiddleware，I want to disable log clockwork files  in storage/clockwork after run php artisan down。

**Comment by itsgoingd** [comment]
Hey, I've added an ability to manually register the middleware.

You can now simply manually add the `\Clockwork\Support\Laravel\ClockworkMiddleware` to your kernel middleware stack in whatever position you need.

This is available in master now and will be released soon.
