### ISSUE TITLE
Email logging doesn't work with laravel 9

### ISSUE THREAD

**Issue by dyanakiev** [itsgoingd/clockwork#556]
The issue is here: https://github.com/laravel/framework/pull/38481#issuecomment-1020129554
After disabling clockwork the issue was resolved.
![CleanShot 2022-01-24 at 17 50 13](https://user-images.githubusercontent.com/11967079/150816355-0b275efb-28ec-4f5a-90ab-5b7afafb507e.png)

**Comment by itsgoingd** [comment]
Hey, thanks for the report. I have not done any testing on Laravel 9 yet, but will try to get a compatible release out before L9 releases. If you find any other issues please let me know.

**Comment by itsgoingd** [comment]
This is now fixed in master and will be released soon.
