### ISSUE TITLE
Requests from tests are displayed in web panel even if CLOCKWORK_TESTS_COLLECT is set to false

### ISSUE THREAD

**Issue by SimBig** [itsgoingd/clockwork#559]
## Actual behaviour:
It looks like clockwork still logs the requests to the Clockwork UI when `CLOCKWORK_TESTS_COLLECT` is set to `false`.

The request data seems to be obfuscated and is not displayed:
![image](https://user-images.githubusercontent.com/26680884/151366646-90e5e5f2-cd37-4754-9618-4a51d8ae499b.png)

## Expected Behaviour:
When `CLOCKWORK_TESTS_COLLECT` is set to `false`, I'd expect no data and requests to be logged by clockwork.

## Workaround:

Right now this behaviour could be reached be wrapping the `setUpClockwork()`-method:

```
protected function setUp(): void
{
    parent::setUp();
    if (env('CLOCKWORK_TESTS_COLLECT')) {
        $this->setUpClockwork();
    }
}
```

**Comment by itsgoingd** [comment]
Fixed in master, thanks!
