### ISSUE TITLE
Fix link to file when PostgresSQL 

### ISSUE THREAD

**Issue by Wit3** [itsgoingd/clockwork#561]
Hi, i've installed this package for benefit with postgresql

tpetry/laravel-postgresql-enhanced

But when open clockwork the link to file where the query run it's wrong.

An example is in the screenshot attached
![clockwork_with_enanched_pgsql](https://user-images.githubusercontent.com/5450259/152759284-7ae689ce-de29-49d3-979e-5af617ef733e.png)
d

**Comment by itsgoingd** [comment]
Hey, try adding the package vendor (`tpetry`) into the `skip_vendors` list in the Clockwork config file.

**Comment by Wit3** [comment]
Thanks it's worked
