### ISSUE TITLE
Support PHP \Throwable

### ISSUE THREAD

**Issue by EdmondDantes** [itsgoingd/clockwork#565]
https://github.com/itsgoingd/clockwork/blob/6a7b3942224fa53cf3704d9adba636e1f3dfeb9a/Clockwork/Request/Log.php#L121

\Throwable is the base exception class in PHP. Errors of this class are not displayed correctly 

`return ! empty($context['exception']) && $context['exception'] instanceof \Throwable && empty($context['raw']);`

**Comment by mahagr** [comment]
It'll work even in PHP 5.6 even if it doesn't have the Throwable class.

**Comment by itsgoingd** [comment]
Added in master (https://github.com/itsgoingd/clockwork/commit/fdc2b3164666e342e9e15d2667cfc46fed095461), thanks. Will tag a new release later this week.
