### ISSUE TITLE
Symfony 6 and Return Types

### ISSUE THREAD

**Issue by mikerockett** [itsgoingd/clockwork#568]
I've just upgraded an app to Laravel 9, which uses Symfony 6.

Unfortunately, the capturing formatter is now broken due to the following:

```
Declaration of Clockwork\Support\Laravel\Console\CapturingFormatter::isDecorated() must be compatible with Symfony\Component\Console\Formatter\OutputFormatterInterface::isDecorated(): bool
```

Other methods of the implemented interface are affected as well.

**Comment by itsgoingd** [comment]
Thanks for the report, sorry to keep you waiting, will fix this one soon.

**Comment by itsgoingd** [comment]
Fixed in master (https://github.com/itsgoingd/clockwork/commit/ab5be8aa825fcb6c8114800386efe939b3b334c1), will tag a new release later this week.
