### ISSUE TITLE
Clockwork 5.1.0 + PHP 8.1.3 + Docker - Profile is not present for current request

### ISSUE THREAD

**Issue by mattfletcher** [itsgoingd/clockwork#569]
I am having issues getting the profiler working on my install of Clockwork. Every time I make a request, it reports that:
**Profile is not present for current request**

Changing the enable/disable button has no effect.

Dockerfile contains:
```
pecl install xdebug
docker-php-ext-enable xdebug
```

php.ini contains:
```
xdebug.mode=profile
xdebug.start_with_request=trigger
```

(also tried with)
```
xdebug.mode=profile
xdebug.start_with_request=yes
```

phpinfo() output:
X-Xdebug-Profile-Filename | /tmp/cachegrind.out.24.gz

![image](https://user-images.githubusercontent.com/414180/157067412-c1614bd3-00d1-4b5d-b6df-d321eb2407c0.png)

**Comment by mixdd** [comment]
Also had this issue and I don't think Clockwork likes the compressed output. Maybe try:

`xdebug.use_compression=false`

and see if that works?

**Comment by Cluster2a** [comment]
> Also had this issue and I don't think Clockwork likes the compressed output. Maybe try:
> 
> `xdebug.use_compression=false`
> 
> and see if that works?

Works for me - thanks!

**Comment by mattfletcher** [comment]
> Also had this issue and I don't think Clockwork likes the compressed output. Maybe try:
> 
> `xdebug.use_compression=false`
> 
> and see if that works?

Yes, this fixes the issue, thank you so much!

**Comment by itsgoingd** [comment]
Hey, completely missed this issue, sorry!

Support for compressed profiler output should be pretty easy to add, adding it to the TODO list. Disabling compression seems like a good workaround for now, thanks @mixdd!
