### ISSUE TITLE
Mongo laravel create() method failing only while clockwork installed

### ISSUE THREAD

**Issue by foron23** [itsgoingd/clockwork#575]
Good morning,
In order to set some context, currently I am developing a Laravel application which connects to a Mongodb database.
The  [driver](https://github.com/jenssegers/laravel-mongodb) which I am using works, and my intention was to plug this library into the project in order to measure and profile the database performance.
However, having the library installed according to the [documentation](https://underground.works/clockwork/#documentation), when I try to create a Model using Eloquent I find the following error: 
`mb_strpos() expects parameter 1 to be string, array given`
In order to isolate the problem, I found out that after removing the package the method works as expected again.

Could It be that this library is incompatible with the database paradigm which I am using? Or is it an unexpected behaviour?
Thanks in advance,

Additional information:

- laravel => 5.8
- PHP => 7.4
- jenssegers/mongodb => 3.5
- itsgoingd/clockwork => 5.1.6

**Comment by itsgoingd** [comment]
Hey, yes indeed, we assume you are working with an SQL database when using Eloquent. I'm kinda interested at taking a look at that Mongo driver to see if there is anything we can easily do to support it, but no promises.

**Comment by foron23** [comment]
I'll keep an eye on the project then, just in case the integration gets implemented.
Thank you very much!
