### ISSUE TITLE
Web portal __clockwork/latest return false

### ISSUE THREAD

**Issue by tokidoki11** [itsgoingd/clockwork#576]
Version: 5.16

When checking via WebPortal /clockwork/app I can see /__clockwork/latest being called
but it returns false thus leaving the page blank

Checking via Chrome Extension it is working as expected

**Comment by tokidoki11** [comment]
@itsgoingd 
any command you want me to run?

as a rough idea I run this this with Laravel 6 on Docker environment

**Comment by UlrichEckhardt** [comment]
```php
		$clockworkDataUri = '#/__clockwork(?:/(?<id>[0-9-]+))?(?:/(?<direction>(?:previous|next)))?(?:/(?<count>\d+))?#';
		if (preg_match($clockworkDataUri, $request->getUri()->getPath(), $matches)) {
			$matches = array_merge([ 'id' => null, 'direction' => null, 'count' => null ], $matches);
			return $this->retrieveRequest($request, $matches['id'], $matches['direction'], $matches['count']);
		}
```
This code is from today's master branch, in three different places. It lacks support for the symbolic "latest" ID. Support for "latest" seems to be present for Laravel, Lumen and Symfony only.
