### ISSUE TITLE
PHP 8.0 compatibility issue with `count(null)`

### ISSUE THREAD

**Issue by marcus-at-localhost** [itsgoingd/clockwork#585]
After updating a Vanilla implementation of Clockwork,  my page dies with **count(): Argument #1 ($value) must be of type Countable|array, null given** at this point:  https://github.com/itsgoingd/clockwork/blob/a9df6cbcfd172bbe729dbf32e18aeaabebb6da23/Clockwork/Request/ShouldCollect.php#L87-L89

![image](https://user-images.githubusercontent.com/1337223/178758089-ed2b2904-f9be-46da-82c1-70e0fb159de4.png)

I suppose `$this->only` refers to this:https://github.com/itsgoingd/clockwork/blob/a9df6cbcfd172bbe729dbf32e18aeaabebb6da23/Clockwork/Request/ShouldCollect.php#L31-L33 but I have no idea when or how it is filled.

As a quick fix I got it running with casting `$this->only` as array `count(`(array)$this->only))`.

I assume this is because `count` throws a type error since PHP 8 https://www.php.net/manual/en/function.count.php

**Comment by itsgoingd** [comment]
Hey, in the vanilla implementation it's filled by the `requests.only` config value, which defaults to an empty array. Is it possible you are setting it to `null` somewhere in your code?

**Comment by marcus-at-localhost** [comment]
Ok, I haven't set this config key in a former version of Clockwork. I set it in the options and it works now, but for some reason it's not defaulting to an array if not set. But that might be my implementation.
Thanks you!
