### ISSUE TITLE
Blank web interface page

### ISSUE THREAD

**Issue by thomeu** [itsgoingd/clockwork#586]
I'm stuck and probably missing something.

Using:
Linux
Nginx
PHP 8
Laravel 9
Clockwork ^5.1

Installed Clockwork but when I try to access I see a blank page.
Log files are being created in `storage/clockwork` but can't access Clockwork via browser.

Viewing the source from the browser you get to see code:
`<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><!--[if IE]><link rel="icon" href="img/icons/favicon-32x32.png"><![endif]--><title>Clockwork</title>...`

Errors I see in Chrome DevTools Console:
![image](https://user-images.githubusercontent.com/205975/180409542-f6d4dafd-8ab3-4ffe-a527-581884f582cd.png)

I have tried with some random clear commands from terminal but no luck.
Something you've seen before?
Thanks

**Comment by itsgoingd** [comment]
Hey, have you had any luck figuring this out? What is the actual content of the javascript files?

**Comment by thomeu** [comment]
Ei. Nope. I tried to install Clockwork in another proyect, other server with same setup, and same thing.

Adding the two js files I see when viewing the source code:
[app.1b17e5e6.txt](https://github.com/itsgoingd/clockwork/files/9552055/app.1b17e5e6.txt)
[chunk-vendors.a7f629a4.txt](https://github.com/itsgoingd/clockwork/files/9552056/chunk-vendors.a7f629a4.txt)

Nginx configuration
```
server {
    listen 8080;
    listen [::]:8080;
    server_name example.com;
    root /home/site/wwwroot/public;
 
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
 
    index index.php;
 
    charset utf-8;
 
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
 
    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }
 
    error_page 404 /index.php;
 
    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
 
    location ~ /\.(?!well-known).* {
        deny all;
    }
}
```

route:list
![image](https://user-images.githubusercontent.com/205975/189766152-75660099-de6c-444f-81c5-71790277873a.png)

**Comment by itsgoingd** [comment]
Closing this since it's and old issue, feel free to reopen if this still does not work for you.
