### ISSUE TITLE
Event with a string property should be shortend in the event-overview

### ISSUE THREAD

**Issue by simbig** [itsgoingd/clockwork#589]
If an Event has a string as a parameter the full string will be reviewed in the event overview. In case of very long string e.g. `Nuwave\Lighthouse\Events\BuildSchemaString->userSchema` (the string contains the whole GraphQL-definition document) the event overview is hardly usable because it will cover multiple pages:

![image](https://user-images.githubusercontent.com/26680884/182393412-48597742-731e-46cd-a0bd-fc025ddb07e7.png)

I'd suggest to shorten the string properties to e.g. 20 chars in the overview or display just the type `string` as is it also done with classes. If the user whats to see the whole string, the detail view can be unfolded.

**Comment by itsgoingd** [comment]
Clockwork 5.3 will now shorten long strings in the previews of pretty-printed values.

<img width="806" alt="Screenshot 2024-10-29 at 01 16 07" src="https://github.com/user-attachments/assets/438d0c58-a6b6-4b90-8c2e-3b53adaa9d2f">
