### ISSUE TITLE
How to use Clockwork with multiple projects/urls?

### ISSUE THREAD

**Issue by madman-81** [itsgoingd/clockwork#595]
I'm running multiple projects, each with it's own URL, but it seems that Clockwork is always using the url from first project I installed it on. So if I want to test/debug http://project_B/ it's still using http://project_A/__clockwork/ because I started with project_A.

How can I change projects? Why isn't Clockwork requesting the /__clockwork/ url at the same host as the browser tab is on? Or am I doing something wrong?

**Comment by eng-ahmad-sameer** [comment]
I have the same problem.

Did you find any solution?

**Comment by ig23** [comment]
create a custom service provider and update this method
registerRoutes and add project path in all the routes that is register into main ClockServiceprovider.
e.g

` $router->get(env('PROJECT_PATH).'/__clockwork/{id:(?:[0-9-]+|latest)}/extended', 'Clockwork\Support\Lumen\Controller@getExtendedData');`

**Comment by itsgoingd** [comment]
Closing this since it's an old issue, please reopen if this is still a problem.
