### ISSUE TITLE
abort(404) in a global middleware and clockwork waiting... for ever

### ISSUE THREAD

**Issue by Brand3000** [itsgoingd/clockwork#597]
Hello, everyone!
As it might be understandable from the subject, I have a global middleware that does abort(404) in some scenarios.
Doesn't matter if the abortion is happening or not, but clockwork shows "Waiting..." forever.
If I comment the string with abort, everything works fine.
Could somebody pay attention to this issue, please?

**Comment by itsgoingd** [comment]
I would need to see a reproduction code on this one, please reopen if you still have this issue.
