### ISSUE TITLE
Call to a member function getKeyName() on array

### ISSUE THREAD

**Issue by LucaRed** [itsgoingd/clockwork#605]
I get the following error after updating to `v5.1.9` and being logged in with any user (I'm using Laravel + Laravel Breeze):

```
Call to a member function getKeyName() on array
```

`vendor/itsgoingd/clockwork/Clockwork/DataSource/LaravelDataSource.php` on line `206`

This problem wasn't present on `v5.1.8`.

**Comment by itsgoingd** [comment]
Well, that was embarrassing. Fixed in 5.1.10, sorry.

**Comment by LucaRed** [comment]
Thank you for the quick fix!
