### ISSUE TITLE
Error when using custom non-eloquent-model User-Object: `Call to undefined method App\Auth\User::getKeyName()`

### ISSUE THREAD

**Issue by m-thalmann-athesia** [itsgoingd/clockwork#606]
When using a custom model for authentication, that does not extend from the Eloquent Model the following error occurrs:

```php
Call to undefined method App\Auth\User::getKeyName()
in \vendor\itsgoingd\clockwork\Clockwork\DataSource\LaravelDataSource.php on line 205
```

This is because the `Illuminate\Contracts\Auth\Authenticatable` interface does not contain a `getKeyName()` function. Wouldn't it be better to use the `getAuthIdentifierName()` function of that interface instead?

**Comment by nadinengland** [comment]
Ran into this issue too. The CMS we use (Statamic.com) doesn't extend from Eloquent Model either but does implement the `Illuminate\Contracts\Auth\Authenticatable` interface.

For those who come across this before it gets resolved, choices were:

1. use the Laravel container and extend the User class to have the method.
2. Just disable clockwork for now `CLOCKWORK_ENABLED=false`

I went with the latter for the time being :/

**Comment by itsgoingd** [comment]
Hey, thanks for the reports, will fix later today.

**Comment by itsgoingd** [comment]
Unfortunately we can't use `getAuthIdentifierName()` directly, since we would run into the same issue the original change tried to fix - people running Eloquent strict mode and not selecting `id` or some of the other columns for the user.

**Comment by m-thalmann-athesia** [comment]
@itsgoingd hmm are you sure? Since you could still use the `$user->getAttributes()` call like now and check if the key received from the `getAuthIdentifierName()` function exists? Am I thinking wrong here?

**Comment by itsgoingd** [comment]
Can you please try pulling `v5.x-dev` and see if it works for you?

@m-thalmann-athesia Sorry, I've explained wrong thing, there are actually two different issues:

- if you are not extending Model you won't even have `getAttributes()`
- Laravel 5.0 does not have `getAuthIdentifierName()`, which is our lowest supported Laravel version

The final code ended up being a bit convoluted, but should work around all of these issues.

**Comment by m-thalmann-athesia** [comment]
@itsgoingd this fixes it! Thank you very much for your fast solution and great work!
