### ISSUE TITLE
No Results in Chrome (new Ticket for a slightly different issue)

### ISSUE THREAD

**Issue by ragingdave** [itsgoingd/clockwork#61]
I have clockwork actually setup and working in my local homestead environment, but on my production server it doesn't seem to work.  The headers are coming through and the files are being generated, and if I navigate to them, they come back with valid json.  Kind of don't know what else to do.
Just to note, even though this is a production server, I do have debug enabled for the time being (still technically in development).
Any Insight would be great

**Comment by geea789** [comment]
did you use the require itsgoingd/clockwork -- dev
and what is set in you .env file?
