### ISSUE TITLE
Clockwork tries to create storage/clockwork folder even it's not enabled

### ISSUE THREAD

**Issue by gitstashgithub** [itsgoingd/clockwork#612]
Hi guys,

We use clockwork in our local and it works great. However when we did a release in server, it caused issue. We have different server users for request and backend task and the default clockwork folder permission is 644 so it has permission issue. 

Except for the permission issue, what I don't understand is the clockwork is not enabled in server, so why it still tries to write the index file(or check the file is writable)?

Thanks.
Gordon

**Comment by gitstashgithub** [comment]
I suggest everyone use 
`composer require itsgoingd/clockwork --dev`
instead of `composer require itsgoingd/clockwork`
if you don't use clockwork in production.

**Comment by itsgoingd** [comment]
This has been changed in Clockwork 5.2, which no longer checks the storage directory permissions when not enabled.
