### ISSUE TITLE
Profile is not present for current request.

### ISSUE THREAD

**Issue by HeadStudios** [itsgoingd/clockwork#617]
I am receiving the error "Profile is not present for current request." in the Profiler tab in Clockwork despite Profiler showing as enabled in phpinfo() and the following code in my php.ini file

[PHP]
zend_extension="/usr/lib/php/20210902/xdebug.so"
xdebug.remote_enable=1
xdebug.remote_autostart=1 
xdebug.mode=profile
xdebug.start_with_request=yes
xdebug.log=/etc/php/8.1/fpm/xdebug.log

Any input for potential reasons would be much appreciated.

Thank you!

**Comment by royretina** [comment]
same problem, none of the fixes mentioned previously here worked

i am on laravel 10 with the latest 5.1 version of clockwork

**Comment by mattvb91** [comment]
any updates? Having the same issue right now.

**Comment by cmrafifar** [comment]
I got it working by removing the line `xdebug.start_with_request=trigger` ... note the documentation said trigger not yes

Probably `trigger` works, but the documentation didn't seem to mention how to actually trigger it per request.

**Comment by itsgoingd** [comment]
Hey, with the trigger option, you should be able to control whether Xdebug profiler is enabled by clicking on the enable button or checkbox in the Clockwork app.

<img width="1044" alt="Screenshot 2023-12-10 at 20 03 01" src="https://github.com/itsgoingd/clockwork/assets/821582/05d46158-382f-4540-99fa-151a9d04356d">

You can of course enable Xdebug profiler for all requests, but running the profiler adds a substantial performance overhead to your requests.
