### ISSUE TITLE
Log errors even in 500 Crash

### ISSUE THREAD

**Issue by magarrent** [itsgoingd/clockwork#619]
Hey there! First of all awesome tool!

Is it possible to log the requests even if it fails?
I think it doesn't save the request log if it throws an error, is it possible?

Thanks!

**Comment by itsgoingd** [comment]
Hey, if it's possible to log we already log it, this includes most types of errors, unhandled exceptions, etc. There are still some common instances where the Clockwork code for storing the request can't run, eg. if your code calls dd/die/exit, if php runs out of memory, etc.
