### ISSUE TITLE
Chrome extension doesn't work for me

### ISSUE THREAD

**Issue by yuritsuki** [itsgoingd/clockwork#620]
Responses are stuck at "Waiting" with error: "Error loading request metadata Cannot read properties of undefined (reading 'response')"
Response headers are set (x-clockwork-id, x-clockwork-version, x-powered-by), clockwork log files too.

Everything works fine at /__clockwork but chrome extension doesn't.

Stack: PHP 7.4, Laravel 7, Vue.JS 3

**Comment by nidhiG2610** [comment]
Having same problem. How did you fix it? @yuritsuki
