### ISSUE TITLE
No output in devtools extension when using `dump()`

### ISSUE THREAD

**Issue by FeBe95** [itsgoingd/clockwork#631]
# Description
Whenever I use a `dump()` statement in my PHP code, nothing is logged in the embedded clockwork console in my browser devtools panel. The web-interface in [myapp.localhost/clockwork](myapp.localhost/clockwork) works perfectly fine though.

Using the network tab of my browser's devtools, I can see that the X-Clockwork headers and response cookies are missing whenever I am using a `dump()` call.

# Example code
### routes/web.php:
```PHP
Route::get('test', "TestController@show");
```
### app/Http/Controllers/TestController.php:
```PHP
namespace App\Http\Controllers;

class TestController extends Controller {
    public function show(): string
    {
        dump("Output Test");
        return "Hello World!";
    }
}
```

# Expected Result
Dumping data with `dump()` should not interfere with the logging behavior of the browser extension. The necessary data does get generated and saved, as it is available in the standalone web-interface.
I understand if it doesn't work with Laravel's `dd()` function, as this function call `exit(1)` and thus ends the PHP process directly.

Is there something I need to configure in Laravel or Clockwork to get this working?

# Actual Result
### Browser:
![grafik](https://user-images.githubusercontent.com/7470739/234092538-c28675d8-89d0-4eeb-8b7d-45a8f4e3683e.png)

### Browser Extension (DevTools Panel):
![grafik](https://user-images.githubusercontent.com/7470739/234091875-a5a9fe7a-0a67-463d-82f0-fcbb4df787c0.png)

### Web-Interface:
![grafik](https://user-images.githubusercontent.com/7470739/234092125-32569929-5a47-4c48-8394-c97ee4aaa77a.png)

**Comment by itsgoingd** [comment]
Hey, thanks for the detailed report.

Unfortunately I think this is a sort-of limitation of how dump works. Looks like dump immediately sends the output to the browser, this means headers are also sent at the point when you call dump.

Clockwork headers are set at the end of the request processing, but since at that point headers were already sent, this has no effect. The web UI still works, since it does not use the Clockwork headers at all and instead polls the Clockwork api for new requests.

**Comment by itsgoingd** [comment]
Yeah, it is technically possible, there is no nice Laravel way to set the headers at the right time, but you could just use the underlying `header` php function at the start of a global middleware:

```php
header('X-Clockwork-Id: ' . $this->app['clockwork']->request()->id);
header('X-Clockwork-Version: ' . \Clockwork\Clockwork::VERSION);
```

I don't think this is something we want to do in Clockwork though.
