### ISSUE TITLE
No visible Instructions for setting up with Laravel running on docker

### ISSUE THREAD

**Issue by drewgallagher** [itsgoingd/clockwork#635]
There doesn't seem to be any instructions for setting up Clockwork with Laravel Apps running on docker. Can you add them?

**Comment by itsgoingd** [comment]
Hey, there are no specific instructions for Docker, normal installation guide applies. Laravel Sail works out of the box, with other Docker environments it would depend on the Docker setup itself.

If you have any specific questions or issues with your Docker setup, feel free to ask.

**Comment by hamihaa** [comment]
![Screenshot 2023-08-18 at 21 13 31](https://github.com/itsgoingd/clockwork/assets/23343814/8bbae753-7efd-4ddd-9dc6-06fe8db4bae2)


@itsgoingd  for me, each request always stays on "waiting" in clockwork. What am i missing?

**Comment by itsgoingd** [comment]
Please reopen if you have any instructions on how to reproduce this issue.
