### ISSUE TITLE
Failed to Install: "Failed to download itsgoingd/clockwork"

### ISSUE THREAD

**Issue by anon59310** [itsgoingd/clockwork#638]
Attempting to install and received the following errors. Can someone please advise?

# composer require itsgoingd/clockwork
Info from https://repo.packagist.org: #StandWithUkraine
./composer.json has been updated
Running composer update itsgoingd/clockwork
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
    Failed to download itsgoingd/clockwork from dist: The zip extension and unzi
p/7z commands are both missing, skipping.
The php.ini used by your command-line PHP is: C:\xampp\php\php.ini
    Now trying to download from source

In GitDownloader.php line 82:

  git was not found in your PATH, skipping source download

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install
PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-ins
tall] [--no-audit] [--audit-format AUDIT-FORMAT] [--update-no-dev] [-w|--update-
with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--
with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-pla
tform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize
-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloade
r-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]

**Comment by itsgoingd** [comment]
Hey, looks like you are missing both zip extension and git. This is not really Clockwork related, but issue with your Composer setup.
