### ISSUE TITLE
Empty extension data with Slim and custom basepath

### ISSUE THREAD

**Issue by sorinionescu-logit** [itsgoingd/clockwork#640]
When using Slim framework and setting a custom base path, the data in devtools is stuck at `waiting...` and eventually gets timeout with error message:

```
Error loading request metadata.
e is undefined
```

Below an example of the container bindings for a slim v4 app (note the line with `$app->setBasePath('/api');`):
```php
//....
$app = AppFactory::create();
$app->setBasePath('/api');
$clockwork = $container->get(Clockwork::class);
$app->add(new ClockworkMiddleware($app, $clockwork));
```
The headers:

```
X-Clockwork-Id:1688389879-9204-816001392
X-Clockwork-Path: /api
X-Clockwork-Version: 5.1.12
```

Debugging the extension, the requests are going to `/api1688389879-9204-816001392` instead of `/api/__clockwork/1688389879-9204-816001392`:
```
http://localhost:8080/api1688389879-9204-816001392
```
Changing the file `vendor/itsgoingd/clockwork/Clockwork/Support/Slim/ClockworkMiddleware.php` at line 96 from:

```php
if ($basePath = $this->app->getBasePath()) {
    $response = $response->withHeader('X-Clockwork-Path', $basePath);
}
```
to contain `/__clockwork/` does the trick and the extension works again:

```php
if ($basePath = $this->app->getBasePath()) {
	$response = $response->withHeader('X-Clockwork-Path', "$basePath/__clockwork/");
}
```

as this changes the header to have the correct path for clockwork:
```
X-Clockwork-Path: /api/__clockwork/
```

**Comment by itsgoingd** [comment]
Hey, thanks for looking into this. Would you like to make a PR with your fix?
