### ISSUE TITLE
Error loading request metadata.

### ISSUE THREAD

**Issue by dokeeer** [itsgoingd/clockwork#642]
Hello! I'm using laravel and trying to install clockwork, but when i try to see logs result the following error occurs:
![image](https://github.com/itsgoingd/clockwork/assets/88163502/5a252191-5921-4852-966b-f7afd04ec38e)

Error loading request metadata.

Cannot read properties of undefined (reading 'response')

I guess composer browser extension tries to read some data from storage/clockwork/index or .json files, so there are following structures of rows:
index:
1689116796-8769-2072954922,1689116796.7475,GET,/,Closure,200,255.67603111267,request

.json:
{"id":"1689116666-1669-197527232","version":1,"type":"request","time":1689116666.063678,"method":"GET","url":"https:\/\/laravel","uri":"\/","headers":{"host":["laravel"],"connection":["keep-alive"],"cache-control":["max-age=0"],"sec-ch-ua":["\"Chromium\";v=\"112\", \"YaBrowser\";v=\"23\", \"Not:A-Brand\";v=\"99\""],"sec-ch-ua-mobile":["?0"],"sec-ch-ua-platform":["\"Windows\""],"upgrade-insecure-requests":["1"],"user-agent":["Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/112.0.0.0 YaBrowser\/23.5.4.674 Yowser\/2.5 Safari\/537.36"],"accept":["text\/html,application\/xhtml+xml,application\/xml;q=0.9,image\/avif,image\/webp,image\/apng,*\/*;q=0.8,application\/signed-exchange;v=b3;q=0.7"],"sec-fetch-site":["none"],"sec-fetch-mode":["navigate"],"sec-fetch-user":["?1"],"sec-fetch-dest":["document"],"accept-encoding":["gzip, deflate, br"],"accept-language":["ru,en;q=0.9"],"cookie":["clockwork-profile=; XDEBUG_PROFILE=; XSRF-TOKEN=eyJpdiI6Ilo4enNEN2dvS25NNWNUSEdtSm5XTVE9PSIsInZhbHVlIjoiL0VoVGdwZHUwWEFwSlBjbXJWMHNWQ2hqa09tTFBoVDZSSm5TNkxpRWlHMFIvSU9Zdi9tZk8yanh1Si9UVHJ3MVgyaldueXdjNFp4TFlYZy95RCtzeUtzN1MzMVNxS2t2cnBYZU04TEtDUzlGYldDQXFjT3dBd3dtY09kT1hLV2ciLCJtYWMiOiJhMzFmNGUzMjY5MDcxNmM3YjZiNzdlZjhiMmE0MDZjM2FjZjRiMTI2YTBmNTA0NDdlMzRlNzg0ZWIyNjhlOTRlIiwidGFnIjoiIn0%3D; laravel_session=eyJpdiI6InV4UHJZT2RkZFZYTTRYR2N5MzRrTFE9PSIsInZhbHVlIjoia0NtcEg4S2kxTEhkNmlJWFhESjZOTzZFNVhCU0NHazliaGJWQmxsZ1g1U3duNHZLRmU5T0hlN2NCWjFUc2ppS3BOR29IdmRYRFJzSkJUa0ZabmN6b1lUa3pjYnRvSHczcUFjMExib3d0UlpSS0hBTWRFc25zbUZreVNkMTJQOVQiLCJtYWMiOiIzZThjYTEyY2YyYTY2OGRlMGNmMTliYTBiYjM1Mjk4ZmYxODQ1OGFjMzlmZWZhYjRkZGUzZDQyY2U1NWJmM2Y0IiwidGFnIjoiIn0%3D"]},"controller":"Closure","getData":[],"postData":[],"requestData":"","sessionData":{"_token":"MgsxIacBFSglYM39D4BvVdVsrePzptluEETvc52U","_previous":{"__type__":"array","url":"https:\/\/laravel"},"_flash":{"__type__":"array","old":{"__type__":"array"},"new":{"__type__":"array"}}},"authenticatedUser":null,"cookies":{"clockwork-profile":"","XDEBUG_PROFILE":"","XSRF-TOKEN":"eyJpdiI6Ilo4enNEN2dvS25NNWNUSEdtSm5XTVE9PSIsInZhbHVlIjoiL0VoVGdwZHUwWEFwSlBjbXJWMHNWQ2hqa09tTFBoVDZSSm5TNkxpRWlHMFIvSU9Zdi9tZk8yanh1Si9UVHJ3MVgyaldueXdjNFp4TFlYZy95RCtzeUtzN1MzMVNxS2t2cnBYZU04TEtDUzlGYldDQXFjT3dBd3dtY09kT1hLV2ciLCJtYWMiOiJhMzFmNGUzMjY5MDcxNmM3YjZiNzdlZjhiMmE0MDZjM2FjZjRiMTI2YTBmNTA0NDdlMzRlNzg0ZWIyNjhlOTRlIiwidGFnIjoiIn0=","laravel_session":"eyJpdiI6InV4UHJZT2RkZFZYTTRYR2N5MzRrTFE9PSIsInZhbHVlIjoia0NtcEg4S2kxTEhkNmlJWFhESjZOTzZFNVhCU0NHazliaGJWQmxsZ1g1U3duNHZLRmU5T0hlN2NCWjFUc2ppS3BOR29IdmRYRFJzSkJUa0ZabmN6b1lUa3pjYnRvSHczcUFjMExib3d0UlpSS0hBTWRFc25zbUZreVNkMTJQOVQiLCJtYWMiOiIzZThjYTEyY2YyYTY2OGRlMGNmMTliYTBiYjM1Mjk4ZmYxODQ1OGFjMzlmZWZhYjRkZGUzZDQyY2U1NWJmM2Y0IiwidGFnIjoiIn0="},"responseTime":1689116666.306469,"responseStatus":200,"responseDuration":242.79093742370605,"memoryUsage":23068672,"middleware":["web"],"databaseQueries":[{"query":"SELECT * FROM `posts`","duration":2.31,"connection":"mysql","time":1689116666.2711298,"trace":[{"call":"Illuminate\\Database\\Eloquent\\Model::all()","file":"laravel-serializable-closure:\/\/function () {\n\n    return \\view('posts', [\n        'posts'=>\\App\\Models\\Post::all()\n    ]);\n\n}","line":5,"isVendor":false},{"call":"Illuminate\\Routing\\RouteFileRegistrar::{closure}()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\CallableDispatcher.php","line":40,"isVendor":true},{"call":"Illuminate\\Routing\\CallableDispatcher->dispatch()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php","line":237,"isVendor":true},{"call":"Illuminate\\Routing\\Route->runCallable()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php","line":208,"isVendor":true},{"call":"Illuminate\\Routing\\Route->run()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php","line":799,"isVendor":true},{"call":"Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php","line":141,"isVendor":true},{"call":"Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php","line":50,"isVendor":true},{"call":"Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php","line":180,"isVendor":true},{"call":"Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php","line":78,"isVendor":true},{"call":"Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php","line":180,"isVendor":true}],"model":"App\\Models\\Post","tags":[]},{"query":"SELECT * FROM `categories` WHERE `categories`.`id` = 1 LIMIT 1","duration":0.52,"connection":"mysql","time":1689116666.289815,"trace":[{"call":"Illuminate\\Database\\Eloquent\\Model->__get()","file":"C:\\OSPanel\\domains\\lara-app\\storage\\framework\\views\\8eda59aa7d6c87446b23a78ed5e6a372.php","line":20,"isVendor":false},{"call":"require()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\Filesystem\\Filesystem.php","line":124,"isVendor":true},{"call":"Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\Filesystem\\Filesystem.php","line":125,"isVendor":true},{"call":"Illuminate\\Filesystem\\Filesystem->getRequire()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Engines\\PhpEngine.php","line":58,"isVendor":true},{"call":"Illuminate\\View\\Engines\\PhpEngine->evaluatePath()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Engines\\CompilerEngine.php","line":72,"isVendor":true},{"call":"Illuminate\\View\\Engines\\CompilerEngine->get()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php","line":195,"isVendor":true},{"call":"Illuminate\\View\\View->getContents()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php","line":178,"isVendor":true},{"call":"Illuminate\\View\\View->renderContents()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php","line":147,"isVendor":true},{"call":"Illuminate\\View\\View->render()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Response.php","line":69,"isVendor":true},{"call":"Illuminate\\Http\\Response->setContent()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Response.php","line":35,"isVendor":true}],"model":"App\\Models\\Category","tags":[]},{"query":"SELECT * FROM `categories` WHERE `categories`.`id` = 2 LIMIT 1","duration":0.53,"connection":"mysql","time":1689116666.294733,"trace":[{"call":"Illuminate\\Database\\Eloquent\\Model->__get()","file":"C:\\OSPanel\\domains\\lara-app\\storage\\framework\\views\\8eda59aa7d6c87446b23a78ed5e6a372.php","line":20,"isVendor":false},{"call":"require()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\Filesystem\\Filesystem.php","line":124,"isVendor":true},{"call":"Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\Filesystem\\Filesystem.php","line":125,"isVendor":true},{"call":"Illuminate\\Filesystem\\Filesystem->getRequire()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Engines\\PhpEngine.php","line":58,"isVendor":true},{"call":"Illuminate\\View\\Engines\\PhpEngine->evaluatePath()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Engines\\CompilerEngine.php","line":72,"isVendor":true},{"call":"Illuminate\\View\\Engines\\CompilerEngine->get()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php","line":195,"isVendor":true},{"call":"Illuminate\\View\\View->getContents()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php","line":178,"isVendor":true},{"call":"Illuminate\\View\\View->renderContents()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php","line":147,"isVendor":true},{"call":"Illuminate\\View\\View->render()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Response.php","line":69,"isVendor":true},{"call":"Illuminate\\Http\\Response->setContent()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Response.php","line":35,"isVendor":true}],"model":"App\\Models\\Category","tags":[]},{"query":"SELECT * FROM `categories` WHERE `categories`.`id` = 3 LIMIT 1","duration":0.42,"connection":"mysql","time":1689116666.297386,"trace":[{"call":"Illuminate\\Database\\Eloquent\\Model->__get()","file":"C:\\OSPanel\\domains\\lara-app\\storage\\framework\\views\\8eda59aa7d6c87446b23a78ed5e6a372.php","line":20,"isVendor":false},{"call":"require()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\Filesystem\\Filesystem.php","line":124,"isVendor":true},{"call":"Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\Filesystem\\Filesystem.php","line":125,"isVendor":true},{"call":"Illuminate\\Filesystem\\Filesystem->getRequire()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Engines\\PhpEngine.php","line":58,"isVendor":true},{"call":"Illuminate\\View\\Engines\\PhpEngine->evaluatePath()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Engines\\CompilerEngine.php","line":72,"isVendor":true},{"call":"Illuminate\\View\\Engines\\CompilerEngine->get()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php","line":195,"isVendor":true},{"call":"Illuminate\\View\\View->getContents()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php","line":178,"isVendor":true},{"call":"Illuminate\\View\\View->renderContents()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php","line":147,"isVendor":true},{"call":"Illuminate\\View\\View->render()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Response.php","line":69,"isVendor":true},{"call":"Illuminate\\Http\\Response->setContent()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Response.php","line":35,"isVendor":true}],"model":"App\\Models\\Category","tags":[]}],"databaseQueriesCount":4,"databaseSlowQueries":0,"databaseSelects":4,"databaseInserts":0,"databaseUpdates":0,"databaseDeletes":0,"databaseOthers":0,"databaseDuration":3.7800000000000002,"cacheQueries":[],"cacheReads":0,"cacheHits":0,"cacheWrites":0,"cacheDeletes":0,"cacheTime":null,"modelsActions":[],"modelsRetrieved":{"App\\Models\\Post":3,"App\\Models\\Category":3},"modelsCreated":[],"modelsUpdated":[],"modelsDeleted":[],"redisCommands":[],"queueJobs":[],"timelineData":[{"description":"Controller","start":1689116666.211637,"end":1689116666.306386,"duration":94.74897384643555,"color":null,"data":null}],"log":[{"message":"Debugbar exception: Route [debugbar.openhandler] not defined.","exception":null,"context":{"__type__":"array"},"level":"error","time":1689116666.30629,"trace":[{"call":"Illuminate\\Log\\LogManager->error()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\barryvdh\\laravel-debugbar\\src\\LaravelDebugbar.php","line":795,"isVendor":true},{"call":"Barryvdh\\Debugbar\\LaravelDebugbar->modifyResponse()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\barryvdh\\laravel-debugbar\\src\\Middleware\\InjectDebugbar.php","line":72,"isVendor":true},{"call":"Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php","line":180,"isVendor":true},{"call":"Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php","line":21,"isVendor":true},{"call":"Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull.php","line":31,"isVendor":true},{"call":"Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php","line":180,"isVendor":true},{"call":"Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php","line":21,"isVendor":true},{"call":"Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TrimStrings.php","line":40,"isVendor":true},{"call":"Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php","line":180,"isVendor":true},{"call":"Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()","file":"C:\\OSPanel\\domains\\lara-app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php","line":27,"isVendor":true}]}],"events":[],"routes":[],"notifications":[],"emailsData":[],"viewsData":[{"description":"Rendering a view","start":1689116666.285806,"end":1689116666.285806,"duration":0,"color":null,"data":{"name":"posts","data":{"__type__":"array"}}},{"description":"Rendering a view","start":1689116666.299758,"end":1689116666.299758,"duration":0,"color":null,"data":{"name":"components.layout","data":{"__type__":"array"}}}],"userData":[],"subrequests":[],"xdebug":[],"commandName":null,"commandArguments":[],"commandArgumentsDefaults":[],"commandOptions":[],"commandOptionsDefaults":[],"commandExitCode":null,"commandOutput":null,"jobName":null,"jobDescription":null,"jobStatus":null,"jobPayload":[],"jobQueue":null,"jobConnection":null,"jobOptions":[],"testName":null,"testStatus":null,"testStatusMessage":null,"testAsserts":[],"clientMetrics":[],"webVitals":[],"parent":null,"updateToken":"d4a2d9ec"}

I'm still not sure that the problem is somewhere in these files, but i hope i'm correct and you can faster determine where problem is. I am using Yandex Browser (based on Chrome), and tried in Chrome. Same error.

Thank you!

**Comment by itsgoingd** [comment]
Hey, do you see the same error when you use `http://your-app/clockwork`? What does `http://your-app/__clockwork/latest` return?

**Comment by dokeeer** [comment]
It works fine, and i tried to see tab again after visiting this url and it started to work. 
I don't know how but the problem is solved.
Also I cleared all cache of my app before and didnt check on clockwork tab before visiting `http://your-app/clockwork,` so maybe it had an impact.
Thank you a lot.
