### ISSUE TITLE
Error with the new laravel/slack-notification-channel v3.0 

### ISSUE THREAD

**Issue by maximepvrt** [itsgoingd/clockwork#643]
```
Error: Cannot access protected property Illuminate\Notifications\Slack\SlackMessage::$username in /Users/maxime/Repos/benevolt-app/vendor/itsgoingd/clockwork/Clockwork/DataSource/LaravelNotificationsDataSource.php:193
Stack trace:
```

**Comment by adityamaru** [comment]
👋 what release of clockwork will this fix be in? Also is a workaround to use an older version of slack-notification-channel?

**Comment by maximepvrt** [comment]
The specific release of Clockwork including this fix hasn't been released. In the meantime, it's worth noting that Slack notification v2 will still be functional in the upcoming version that supports v3
