### ISSUE TITLE
Feature: Possibility to show or hide duplicate requests

### ISSUE THREAD

**Issue by JulRod** [itsgoingd/clockwork#645]
When managing a legacy project it is very common to have duplicate queries to the database and you can quickly show if they are duplicate or not, or how many queries are duplicated and how much execution time has been wasted.
I think this feature can help improve project performance. I am willing to get into it if you think it can be really useful. 

**An example that I see on a personal project using laravel 7.4 and passport 10.4:**
<img width="818" alt="Captura de pantalla 2023-08-27 a las 19 59 02" src="https://github.com/itsgoingd/clockwork/assets/26247524/eb6a28d4-f136-4e69-b3d1-59ebcd945af8">

On this case ordering the queries was useful to see the duplication. But when the request show many queries, sorting them and seeing dozens of duplicated queries is not helpful to have an overview of what is happening. Having the possibility to hide the duplicated ones and show the total amount of wasted execution time can help to identify problems more quickly and efficiently .

**Comment by itsgoingd** [comment]
Hey, detecting duplicate queries is a hard problem to solve, as you might want to write a code that intentionally runs the same query multiple times. At the other hand, looping through a relationship in Eloquent without using eager-loads, might lead to execution of many "duplicate" queries, which are not an exact duplicates (they always contain different id).

We currently do support detecting of duplicate queries in Eloquent (the n+1 problem), this can be turned on by setting `CLOCKWORK_DATABASE_DETECT_DUPLICATE_QUERIES` to true.

We could also support detecting exact duplicates, but I'm not sure how useful that would be, as it is pretty uncommon issue and it might cause false positives.

**Comment by JulRod** [comment]
Hi, sorry I don't saw this option when I searched for anything similar. I will try it but I'm pretty sure that is all I need.
Seeing the clockwork.php config file I think there are enough config options to can trace the cases that I had thought. Sorry for the issue when I only needed to search a bit more..
