### ISSUE TITLE
JsonResponse not getting correct header

### ISSUE THREAD

**Issue by FredrikPAC** [itsgoingd/clockwork#646]
I have an error with the following:
On line 428 it checks if the response is an instance of a Illuminate\Http\Response making all responses that are Illuminate\Http\JsonResponse fail. Could this be changed to the more core Symfony\Component\HttpFoundation\Response instead?

https://github.com/itsgoingd/clockwork/blob/1a5ad0fc8e632b0e7c21291717d4ebff77ccc7e8/Clockwork/Support/Laravel/ClockworkSupport.php#L427-L439

**Comment by itsgoingd** [comment]
Hey, sorry I missed this issue somehow. I think this is intentional, as the toolbar does not really work for api responses atm.
