### ISSUE TITLE
Unable to Expand Array/Object with Key Starting with Numeric

### ISSUE THREAD

**Issue by masdimdev** [itsgoingd/clockwork#658]
Unable to open or expand array or object keys when the key starts with a numeric value (e.g., "123test") or a date format (e.g., "2023-10-31"). It seems that Clockwork might be treating these keys differently or not recognizing them correctly.

![image](https://github.com/itsgoingd/clockwork/assets/9777941/6abd380c-b8c2-45bc-8162-0a81a0cb7e36)

**Comment by itsgoingd** [comment]
Hey, thanks for the report, will fix in the next release.

**Comment by masdimdev** [comment]
I've found a simple workaround that seems to resolve the problem. I added a "+" symbol to the variable, and this has fixed the issue in my case.

![image](https://github.com/itsgoingd/clockwork/assets/9777941/28ada789-af72-4b54-813f-85dc42680dac)

**Comment by itsgoingd** [comment]
This has been fixed in master a while ago (https://github.com/underground-works/clockwork-app/commit/25084abb5a0c375996eca69f66c246c73bc62329) and will be released in Clockwork 5.3.
