### ISSUE TITLE
Symfony 6.3 BC break

### ISSUE THREAD

**Issue by mihai-stancu** [itsgoingd/clockwork#659]
Hello,

Symfony appears to have changed various things so that Clockwork does not work out of the box.

First thing I ran into was that stricter types are now required for the `getContainerExtensionClass` method:
```php
ClockworkBundle::getContainerExtensionClass(): string
```

The next issue was not receiving the $container injected in `ClockworkFactory` -- this may relate to my setup, I'll test on a vanilla symfony install to make sure.

What is your currently supported version of Symfony?

**Comment by mihai-stancu** [comment]
At the least this should be mentioned in composer's conflicts section to avoid installing clockwork on an usupported version of Symfony.

**Comment by erikn69** [comment]
Symfony 6 compatibility was reversed, https://github.com/itsgoingd/clockwork/commit/51eae8daba1384020e128171e4c86f80f88aa9b9

**Comment by mihai-stancu** [comment]
Thank you @erikn69 that's useful to know.

**Comment by erikn69** [comment]
There are also PHP 8.2 deprecations , 
https://github.com/itsgoingd/clockwork/blob/e46932c92cf0bf03c2470d781f9f322b25c62519/Clockwork/Support/Symfony/ClockworkFactory.php#L12
```
Dynamic propertiy `container`
User Deprecated: Since symfony/framework-bundle 5.4: 
    Accessing the "profiler" service directly from the container is deprecated, use dependency injection instead.
```

**Comment by itsgoingd** [comment]
Hey, I've pushed a bunch of Symfony 6 fixes to dev-master, please give it a try and let me know if it works for you.

Unfortunately, it's impossible to release these in 5.1.x, as they break compatibility with older Symfony versions running on older PHP.

**Comment by mihai-stancu** [comment]
Thank you, I'll take it for a spin!

**Comment by PaolaRuby** [comment]
@itsgoingd hi, what about two [Symfony/ClockworkBundle.php](https://github.com/itsgoingd/clockwork/blob/master/Clockwork/Support/Symfony/ClockworkBundle.php) files, one for V6 support, like 
```php
// Symfony/ClockworkBundleV6.php
class ClockworkBundleV6 extends Bundle
{
	protected function getContainerExtensionClass(): string
	{
		return ClockworkExtension::class;
	}
}
```

**Comment by itsgoingd** [comment]
@PaolaRuby That's definitively possible, I'm just not fan of that naming convention and I'm working on a next major version of Clockwork anyway. Since major versions can break backwards-compatibility, we can replace the main Symfony bundle with the updated one and either provide another legacy one or tell people using older Symfony to use older Clockwork version.

**Comment by edvordo** [comment]
Old-ish issue, but I thought I'd chime in anyway.

Instead of two files, I've seen devs, that wanted to support older applications just do a PHP version conditional in the class file and implement the whole class within that conditional.

In this case, it could look something like this:

```php
if (true === version_compare(PHP_VERSION, '7.0.0', '<')) {
  class ClockworkBundle extends Bundle
  {
	  protected function getContainerExtensionClass()
	  {
		  return ClockworkExtension::class;
	  }
  }
} else {
  class ClockworkBundle extends Bundle
  {
	  protected function getContainerExtensionClass(): string
	  {
		  return ClockworkExtension::class;
	  }
  }
}

```
Ugly? Maybe, but it's a solution.

**Comment by itsgoingd** [comment]
This would be a valid option if the Symfony versions differed only in apis, but won't work when one of the versions uses new PHP syntax features. The older PHP parser needs to parse both branches and throws an error once it encounters the new return type syntax.

**Comment by edvordo** [comment]
Well, the symfony [kernel provides its current version](https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/HttpKernel/Kernel.php#L79), so the above conditional could be changed to something like this

```php
if (true === version_compare(\Symfony\Component\HttpKernel\Kernel::VERSION, '6.0.0', '<')) {
``` 
and you'd be good to go for whichever version of symfony the end-project uses.

Granted, this is just one class, relatively small and easy to maintain. I'm not familiar with symfony or clockwork enough to say how many classes would need a workaround like this or how much more headache to would add to your life.

**Comment by itsgoingd** [comment]
Since we now require PHP 7.1, we can support all versions of Symfony from 4 to 7.x with a single bundle in Clockwork 5.3.
