### ISSUE TITLE
Laravel 4.2.10 - Target [Psr\Log\LoggerInterface] is not instantiable.

### ISSUE THREAD

**Issue by spencerdeinum** [itsgoingd/clockwork#67]
Upon updating to 4.2.10 I get this error when using the Laravel service provider.

Stack trace.

<pre>
Illuminate\Container\BindingResolutionException thrown with message "Target [Psr\Log\LoggerInterface] is not instantiable."

Stacktrace:
#35 Illuminate\Container\BindingResolutionException in /vagrant/vendor/laravel/framework/src/Illuminate/Container/Container.php:513
#34 Illuminate\Container\Container:build in /vagrant/vendor/laravel/framework/src/Illuminate/Container/Container.php:428
#33 Illuminate\Container\Container:make in /vagrant/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:462
#32 Illuminate\Foundation\Application:make in /vagrant/vendor/laravel/framework/src/Illuminate/Mail/MailServiceProvider.php:247
#31 Illuminate\Mail\MailServiceProvider:Illuminate\Mail\{closure} in /vagrant/vendor/laravel/framework/src/Illuminate/Container/Container.php:214
#30 Illuminate\Container\Container:Illuminate\Container\{closure} in /vagrant/vendor/laravel/framework/src/Illuminate/Container/Container.php:501
#29 Illuminate\Container\Container:build in /vagrant/vendor/laravel/framework/src/Illuminate/Container/Container.php:428
#28 Illuminate\Container\Container:make in /vagrant/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:462
#27 Illuminate\Foundation\Application:make in /vagrant/vendor/laravel/framework/src/Illuminate/Container/Container.php:806
#26 Illuminate\Container\Container:offsetGet in /vagrant/vendor/laravel/framework/src/Illuminate/Mail/MailServiceProvider.php:102
#25 Illuminate\Mail\MailServiceProvider:Illuminate\Mail\{closure} in /vagrant/vendor/laravel/framework/src/Illuminate/Container/Container.php:214
#24 Illuminate\Container\Container:Illuminate\Container\{closure} in /vagrant/vendor/laravel/framework/src/Illuminate/Container/Container.php:501
#23 Illuminate\Container\Container:build in /vagrant/vendor/laravel/framework/src/Illuminate/Container/Container.php:428
#22 Illuminate\Container\Container:make in /vagrant/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:462
#21 Illuminate\Foundation\Application:make in /vagrant/vendor/laravel/framework/src/Illuminate/Container/Container.php:806
#20 Illuminate\Container\Container:offsetGet in /vagrant/vendor/laravel/framework/src/Illuminate/Mail/MailServiceProvider.php:38
#19 Illuminate\Mail\MailServiceProvider:Illuminate\Mail\{closure} in /vagrant/vendor/laravel/framework/src/Illuminate/Container/Container.php:214
#18 Illuminate\Container\Container:Illuminate\Container\{closure} in /vagrant/vendor/laravel/framework/src/Illuminate/Container/Container.php:501
#17 Illuminate\Container\Container:build in /vagrant/vendor/laravel/framework/src/Illuminate/Container/Container.php:428
#16 Illuminate\Container\Container:make in /vagrant/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:462
#15 Illuminate\Foundation\Application:make in /vagrant/vendor/laravel/framework/src/Illuminate/Container/Container.php:806
#14 Illuminate\Container\Container:offsetGet in /vagrant/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkServiceProvider.php:49
#13 Clockwork\Support\Laravel\ClockworkServiceProvider:Clockwork\Support\Laravel\{closure} in /vagrant/vendor/laravel/framework/src/Illuminate/Container/Container.php:501
#12 Illuminate\Container\Container:build in /vagrant/vendor/laravel/framework/src/Illuminate/Container/Container.php:428
#11 Illuminate\Container\Container:make in /vagrant/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:462
#10 Illuminate\Foundation\Application:make in /vagrant/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkServiceProvider.php:26
#9 Clockwork\Support\Laravel\ClockworkServiceProvider:boot in /vagrant/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:585
#8 Illuminate\Foundation\Application:Illuminate\Foundation\{closure} in <#unknown>:0
#7 array_walk in /vagrant/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:585
#6 Illuminate\Foundation\Application:boot in /vagrant/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:743
#5 Illuminate\Foundation\Application:handle in /vagrant/vendor/laravel/framework/src/Illuminate/Session/Middleware.php:72
#4 Illuminate\Session\Middleware:handle in /vagrant/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php:47
#3 Illuminate\Cookie\Queue:handle in /vagrant/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php:51
#2 Illuminate\Cookie\Guard:handle in /vagrant/vendor/stack/builder/src/Stack/StackedHttpKernel.php:23
#1 Stack\StackedHttpKernel:handle in /vagrant/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:641
#0 Illuminate\Foundation\Application:run in /vagrant/public/index.php:49

</pre>

**Comment by itsgoingd** [comment]
Fix included in Laravel 4.2.12+, thanks for investigating and fixing this!
