### ISSUE TITLE
Using MonologDataSource trigger error

### ISSUE THREAD

**Issue by DominicDetta** [itsgoingd/clockwork#676]
I'm using the monolog package version 2.9.2 and I obtain the following error: 

```php
PHP Fatal error:  Declaration of Clockwork\\Support\\Monolog\\Handler\\ClockworkHandler::write(array $record) must be compatible with Monolog\\Handler\\AbstractProcessingHandler::write(array $record): void in /var/www/html/vendor/itsgoingd/clockwork/Clockwork/Support/Monolog/Handler/ClockworkHandler.php on line 21
```

The code to add the new DataSource: 
```php
$this->clockwork->addDataSource(new \Clockwork\DataSource\MonologDataSource($this->logger));
```

**Comment by DominicDetta** [comment]
I found that the correct handler to use is `Clockwork\Support\Monolog\Monolog2\ClockworkHandler`.
A new monolog datasource which implements this handler would be great. I can create a PR if you want.

**Comment by itsgoingd** [comment]
Ah, I guess I forgot we had a Monolog data source as well, when adding handlers for newer Monolog versions. I think we can improve the data source, to check what Monolog version is installed and register the correct handler.
