### ISSUE TITLE
Laravel 5 - changes to filters and controllers

### ISSUE THREAD

**Issue by martindilling** [itsgoingd/clockwork#68]
Just a little heads up, some new changes in the Laravel 5 branch changes filters to middleware. And makes controllers plain objects that uses annotations to set middleware.
I'll try to take a look at it if I get the time, but just wanted to tell you what's up ;)

https://github.com/laravel/laravel/commit/b8f3dd6265b4bfd318eab98ef65887203a809173

**Comment by itsgoingd** [comment]
Full Laravel 5 support now available in Clockwork 1.7.
