### ISSUE TITLE
(Laravel) Chrome extension has option to "Load more", but the web page doesn't?

### ISSUE THREAD

**Issue by amnah** [itsgoingd/clockwork#681]
Hi,

I was wondering if there was a reason why the Laravel webpage doesn't include an option to load older results?

![Screenshot 2024-02-16 at 12 35 05 AM](https://github.com/itsgoingd/clockwork/assets/2630503/6407378e-a14c-4ce3-a95e-98b3338659e2)

**Comment by itsgoingd** [comment]
Hey, you can scroll up, to reveal the load more button and search input.
