### ISSUE TITLE
Slack Message Notification tries to access protected property

### ISSUE THREAD

**Issue by Light-it-luc** [itsgoingd/clockwork#690]
When I try to send a Slack Notification through an action, or in an Event Listener, I get the following error:

Error: Cannot access protected property Domain\Slack\Messages\SlackMessage::$username in file /var/www/html/vendor/itsgoingd/clockwork/Clockwork/DataSource/LaravelNotificationsDataSource.php on line 193

#0 /var/www/html/vendor/itsgoingd/clockwork/Clockwork/DataSource/LaravelNotificationsDataSource.php(157): Clockwork\DataSource\LaravelNotificationsDataSource-&gt;resolveSlackChannelSpecific()
#1 /var/www/html/vendor/itsgoingd/clockwork/Clockwork/DataSource/LaravelNotificationsDataSource.php(102): Clockwork\DataSource\LaravelNotificationsDataSource-&gt;resolveChannelSpecific()
#2 /var/www/html/vendor/itsgoingd/clockwork/Clockwork/DataSource/LaravelNotificationsDataSource.php(52): Clockwork\DataSource\LaravelNotificationsDataSource-&gt;sendingNotification()

This is the function that's trying to access the protected username property:

```
protected function resolveSlackChannelSpecific($event, $message)
	{
		return [
			'subject' => get_class($event->notification),
			'from'    => $message->username,
			'to'      => $message->channel,
			'content' => $message->content
		];
	}
```

The other properties (channel, and content) are also protected, I believe. 

What's weird about this is that, if the notification is sent in a scheduled command, I don't get the error. When I disabled clockword with `CLOCKWORK_ENABLE=false` the notification was sent with no problems.

**Comment by itsgoingd** [comment]
Hey, are you using some third-party Slack notifications library? As far as I can see, the official library has public properties - https://github.com/laravel/slack-notification-channel/blob/3.x/src/Messages/SlackMessage.php

**Comment by itsgoingd** [comment]
Ah, I see, looks like this was added in the 3.0 release of that library. I should have a fix ready soon.

**Comment by itsgoingd** [comment]
Actually, looks like we already support slack-notification-channel v3 since Clockwork 5.2, so simply updating Clockwork should resolve this issue.

**Comment by Light-it-luc** [comment]
Oh, I see. I was using version 5.1. Thanks!
