### ISSUE TITLE
Where is the response in this?

### ISSUE THREAD

**Issue by stockarea** [itsgoingd/clockwork#700]
I can't see response which is being sent by the API in the logs and debugging. 

Is there any way I can get it?

![image](https://github.com/itsgoingd/clockwork/assets/51982217/396622ae-46d0-4018-a14a-b60dda029dac)

**Comment by stockarea** [comment]
Okay, but response is CRUCIAL part in debugging things.

**Comment by itsgoingd** [comment]
Yeah, it's a bit tricky to implement, since we don't know what the response will be. It can be empty, simple json response, but also some huge 500MB json structure or a 5GB binary blob, and we need to support all these cases, ideally without crashing your app and adding a lot of processing time.

**Comment by itsgoingd** [comment]
Duplicate of https://github.com/itsgoingd/clockwork/issues/127.
