### ISSUE TITLE
Profile is not present for current request

### ISSUE THREAD

**Issue by devope** [itsgoingd/clockwork#705]
Hey there!

I stuck in problem with enabling Profiler.
Help me please to understand what I am missing here.

The output of `php --ini`:

```
Configuration File (php.ini) Path: /opt/homebrew/etc/php/8.3
Loaded Configuration File:         /opt/homebrew/etc/php/8.3/php.ini
Scan for additional .ini files in: /opt/homebrew/etc/php/8.3/conf.d
Additional .ini files parsed:      /opt/homebrew/etc/php/8.3/conf.d/99-xdebug.ini,
/opt/homebrew/etc/php/8.3/conf.d/error_log.ini,
/opt/homebrew/etc/php/8.3/conf.d/ext-opcache.ini,
/opt/homebrew/etc/php/8.3/conf.d/php-memory-limits.ini
```

The content of `/opt/homebrew/etc/php/8.3/conf.d/99-xdebug.ini`:

```ini
zend_extension=xdebug.so
xdebug.mode=profile
xdebug.start_with_request=yes
```

macOS 14.4.1 (23E224)

**Comment by itsgoingd** [comment]
Hey, thanks for your message. This has been a known issue with the default Xdebug configuration. I've finally updated our installation guide, to include this setting - https://underground.works/clockwork/#docs-xdebug-profiler
