### ISSUE TITLE
No such file in iframe.html.php

### ISSUE THREAD

**Issue by fedorovsergey** [itsgoingd/clockwork#706]
In file 
https://github.com/itsgoingd/clockwork/blob/743aee4f29ec7773a05562865aa8a7655d25a868/Clockwork/Support/Vanilla/iframe.html.php#L16
attached an svg $asset('img/icons/safari-pinned-tab.svg') and $asset('img/icons/msapplication-icon-144x144.png') but in project is no such files. How does it works?

**Comment by UlrichEckhardt** [comment]
You need to take a look at `$asset`, which refers to a PHP function which resolves these paths to the correct location.

**Comment by itsgoingd** [comment]
Hey, I think I forgot to update the iframe when updating the web UI recently, thanks for bringing this into my attention. The web UI is quite broken in master though, so I don't recommend using it right now.

**Comment by itsgoingd** [comment]
The web interface has been updated and old icons cleaned up in master (https://github.com/itsgoingd/clockwork/commit/806cc10b275e791ed6ab6c48ec30a0fcaeea2afb).
