### ISSUE TITLE
Chrome Extension needs to be updated to Manifest v3

### ISSUE THREAD

**Issue by webdevnerdstuff** [itsgoingd/clockwork#709]
Please update the Chrome Extension to use Manifest v3.

https://chromewebstore.google.com/detail/dmggabnehkmmfmdffgajcflpdjlnoemp

![image](https://github.com/user-attachments/assets/669dee49-1c87-413d-921d-7822739b6d79)

**Comment by itsgoingd** [comment]
Hey, the good news is, I should already have a branch with a working Manifest v3 implementation somewhere. I was planning to introduce it with the next Clockwork release, but I will probably backport it and do a patch release this week to make sure it keeps working.

**Comment by webdevnerdstuff** [comment]
Perfect, thank you! :) 

Good thing is that it does still work currently, so Chrome is behind schedule for disabling v2 extensions.

**Comment by itsgoingd** [comment]
Clockwork Chrome 5.1.1 has been submitted for review, the only change is the introduction of the Manifest v3. Hopefully it will be published in a few days.

**Comment by itsgoingd** [comment]
Published now. :)

**Comment by webdevnerdstuff** [comment]
The update has been applied, and the waring is no longer there. Thank you!
