### ISSUE TITLE
Cant find how to open historical json

### ISSUE THREAD

**Issue by pastebimas** [itsgoingd/clockwork#713]
Hello,

I see there are plenty of logs that I was generating in storage/clockwork, but can't find any way to load any of them. Default web interface loads "latest" and then "next". No buttons anywhere to load all or specific file.

Is this intended? I see there are methods to load specific one or all, but can't find frontend source files, to make adjustments.

Thank you

**Comment by itsgoingd** [comment]
Hey, if you scroll up in the request list you will find a search field and load more button, which can be used to search and load older requests. 

You can find the Clockwork app source here - https://github.com/underground-works/clockwork-app
