### ISSUE TITLE
PHP 8.4: Missing`$escape` param for `fputcsv` and `str_getcsv`

### ISSUE THREAD

**Issue by gharlan** [itsgoingd/clockwork#718]
With the upcoming PHP 8.4 I get these deprecation notices:

> fputcsv(): the $escape parameter must be provided as its default value will change 
> Clockwork/Storage/FileStorage.php:306

> str_getcsv(): the $escape parameter must be provided as its default value will change
> Clockwork/Storage/FileStorage.php:231

**Comment by itsgoingd** [comment]
Thanks, I'll fix it soon.

**Comment by itsgoingd** [comment]
Fixed in master now (https://github.com/itsgoingd/clockwork/pull/719), will release with Clockwork 5.3 before PHP 8.4 general availability.
