### ISSUE TITLE
outgoing link to display much more data.

### ISSUE THREAD

**Issue by evaisse** [itsgoingd/clockwork#81]
Hello, first I must say I think clockwork is the best profiler tool around IMHO, especially because it's simple, clean and work outside of the scope of the request itself. I develop a solution that don't use the clockwork driver but use the clockwork chrome extension, but I have a lot more informations to display if user desire, and **I would like to display a simple outgoing link** to allow the user to display of a complete process details page that I produce somewhere else. There is much more information on my debug details that the chrome toolbar could contains, *so I don't want to "add" data to the current extension* but simply allow user to click on a link  request details to 

I suggest a simple ``moreDetailsUri`` property at the root of the clockwork json schema, which contains url like "https://foo.com/bar/{{id}}" , and a button as suggested in the screenshot below.  that could be displayed in the chrome extension.

![screenshot]
(http://img15.hostingpics.net/pics/987565Capturedcran20141223190412.png)

I think simpler is better.

This could maybe help to this todo also, instead of doing iframe stuff :  https://github.com/itsgoingd/clockwork/issues/71

Do you think it's possible ?

I can do the pull request for this feature if accepted.

**Comment by itsgoingd** [comment]
Hey, sorry for the late reply.

One of the features I'm working on for Clockwork 2.0 is a customisable toolbar (the one that has only clear button atm). The use case I was thinking was adding buttons for Laravel artisan commands so you don't have to ssh to the server when you need to run some remote commands etc. but it can work really well for your use case as well.

The code for this feature is almost done (not yet on github), but I'm a bit stuck with the 2.0 version as a whole, so I can't give you any eta on release. I'm planning to release 1.7 with Laravel 5 support as soon as L5 is released and hopefully then I'll start making some progress on 2.0.
