### ISSUE TITLE
Laravel 5 - Call to undefined method Application::after()

### ISSUE THREAD

**Issue by Flynsarmy** [itsgoingd/clockwork#82]
Getting the error `Call to undefined method Illuminate\Foundation\Application::after()` in ClockworkServiceProvider.php line 84 when loading any page in L5.

```
in ClockworkServiceProvider.php line 84
at HandleExceptions->fatalExceptionFromError(array('type' => '1', 'message' => 'Call to undefined method Illuminate\Foundation\Application::after()', 'file' => '/path/to/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkServiceProvider.php', 'line' => '84')) in HandleExceptions.php line 116
at HandleExceptions->handleShutdown()
```

I have both the middleware and provider rows added to my appropriate config files.

**Comment by itsgoingd** [comment]
Hey, Laravel 5 is not yet supported in the stable version. It was supported in dev-master, but even that was broken by recent changes in Laravel 5. I'll fix dev-master when 5.0-BETA is tagged and a new stable version should be ready as soon as final 5.0 is released.

**Comment by morrislaptop** [comment]
I've got a package which acts as a bridge to get Clockwork - working! https://github.com/morrislaptop/LaravelFivePackageBridges

**Comment by freekmurze** [comment]
Hi, what's the status of Laravel 5 compatibility? Are you tagging a compatible soon?

**Comment by itsgoingd** [comment]
Hey, Clockwork 1.7 including full Laravel 5 compatibility was tagged a few days ago.

**Comment by freekmurze** [comment]
O, I didn't see that! Nice!
