### ISSUE TITLE
Unable to use clockwork in Laravel by following steps in README

### ISSUE THREAD

**Issue by gxela** [itsgoingd/clockwork#83]
Error Output: PHP Fatal error:  Call to undefined method Clockwork\Support\Laravel\Facade::info()

**Comment by itsgoingd** [comment]
Hey, I can't really think of any scenario that would result in this error, can you share more information about your environment and a stack trace if possible? What version of Laravel are you running?

**Comment by gxela** [comment]
I will have to try this out again when I have a chance. I was using Laravel 4.2. and following the README for logging the info
