### ISSUE TITLE
Laravel 5 "Maximum function nesting level of '100' reached"

### ISSUE THREAD

**Issue by john052** [itsgoingd/clockwork#85]
I know the Laravel 5 support is experimental and I can't be much help in trying to track down the cause of the error, but I'll just leave it here in case someone else runs into it.

I was making some changes and started getting this error:
```
FatalErrorException in MySqlGrammar.php line 127:
Maximum function nesting level of '100' reached, aborting!
```
After about 2 hours of trying to track it down I started disabling any extra service providers and middleware. When I disabled the clockwork middleware the error disappeared.

I'm sorry I can't be of more help but I have no idea what was causing it. It was literally a matter of calling a function in one place in the code giving the error, and calling it somewhere else not giving any error.

**Comment by itsgoingd** [comment]
Hey, can you please post full stack trace and/or sample code that triggers this error?
Might be some problem with logging database queries, were you doing some complex Eloquent calls or something like that?

**Comment by john052** [comment]
That's basically all I got. That's why it took forever to track it down because I only got the cryptic message with no real indication of where it's happening.

The only fancy eloquent call that could be messing it up is getting the user roles from a pivot table. But no problems anywhere else, only in this one very specific instance.

What made it even more frustrating is that if I called the function causing the error inside the blade view it works, but calling it inside another function that's called inside the view gives the error.

So for now I solved it by just calling the function inside the blade view. I'll try to get the error again and see if i can get something useful from the debugger.

**Comment by john052** [comment]
So under normal circumstances I can't get the error on the debugging server. Lowering the nesting level can give me the error again, but still no useful info on why it's only happening in that very specific instance.

Since I'm only getting it on the artisan server with clockwork enabled and I can work around it, I'm not going to worry about it anymore. Just going to assume that in that very specific instance it's going over the maximum nesting level. Possibly because of a complex query.

**Comment by mikeerickson** [comment]
@john052 

If you adjust your php.ini file to something like 200, this will cure the issue

[xdebug]
xdebug.max_nesting_level = 200

Note:  You will most likely see the same error when using something like Behat with Laravel as well.

**Comment by UnderlineWords** [comment]
Thanks @mikeerickson It's works now on Laravel 5.1.1

**Comment by poul-kg** [comment]
Thanks @mikeerickson this helped.

**Comment by sputinyk** [comment]
@mikeerickson , thanks!!!

**Comment by andrewf137** [comment]
Thanks @mikeerickson, big help!
