### ISSUE TITLE
Clockwork not parsing file in chrome debugger

### ISSUE THREAD

**Issue by mikeerickson** [itsgoingd/clockwork#86]
I dont see any output in the Chrome debugger (but the file is definitely created)  Do I need to configure a path as to where CW looks for files for parsing?

http://d.pr/i/iYlP

**Comment by mikeerickson** [comment]
Update;  Using Laravel 5 and Clockwork 'dev-master'

From composer.json

    "itsgoingd/clockwork": "dev-master"

**Comment by itsgoingd** [comment]
Hey, please don't use dev-master, Laravel 5 support is already available in 1.7. To troubleshoot the issue, check the network tab in dev tools if your server responses contain X-Clockwork headers, if that works see if http://your-site/_clockwork/x_clockwork_id_value returns correct JSON data.

**Comment by mikeerickson** [comment]
@itsgoingd 

I have updated to use 1.7.x
The headers are present in response
the result of http call

The requested resource /_clockwork/1424218466.4956.23131550 was not found on this server.

**Comment by itsgoingd** [comment]
Sorry, it is /__clockwork/1424218466.4956.23131550 (two underscores), try this one please.

**Comment by mikeerickson** [comment]
@itsgoingd 

Same results... ;(

**Comment by mikeerickson** [comment]
@itsgoingd I am going to create a brand new empty L5 project and see if I can get working.

**Comment by mikeerickson** [comment]
@itsgoingd OK, using a fresh install of laravel, just created using 

<code>
$ composer create-project laravel/laravel l5-clockwork
</code>

- Installed CW 1.7 via composer (then composer update)
- Added service provider, middleware and facade

Still not working

**Comment by mikeerickson** [comment]
@itsgoingd Here is my test application 

https://github.com/mikeerickson/l5-clockwork.git

**Comment by itsgoingd** [comment]
Hey, I've cloned your repo, added .env file enabling the debug mode and Clockwork runs fine for me (using artisan serve). Maybe you forgot to enable the debug mode? That would cause the headers not to be sent though. Can you please test your app using the built-in php server (artisan serve) to rule out web server configuration issue?

**Comment by mikeerickson** [comment]
@itsgoingd 

Curious how it could be  a server issue (I was using built-in php server)

But, using `artisan serve` all works so go figure!

Thanks for your efforts mate, greatly appreciated

**Comment by edogawaconan** [comment]
I think the readme needs an update since it still mentions version 1.6 and laravel 5 support only available in dev-master.

**Comment by itsgoingd** [comment]
Ah, forgot to change default branch to v1, thanks!
