### ISSUE TITLE
how to do catch the ajax request?

### ISSUE THREAD

**Issue by stevenyangecho** [itsgoingd/clockwork#87]
I'm useing laravel 5 and chrome
if get a ajax request ,then the chrome Network panel can see the request .
but the ​Clockwork cant see it.

**Comment by itsgoingd** [comment]
Hey, if you have Clockwork open at the time of the request it should work. Can you check if data for the request were collected in `storage/clockwork/` ?

**Comment by stevenyangecho** [comment]
yes,thanks,try again today,it works!
