### ISSUE TITLE
Cannot redeclare class Slim_Middleware

### ISSUE THREAD

**Issue by nickkjordan** [itsgoingd/clockwork#88]
After going through the instructions to add with Slim, but I get a fatal error with php:

**Fatal error**: Cannot redeclare class Slim_Middleware in **/../vendor/slim/slim/Slim/Middleware.php** on line **41**

Any clue why this is being declared twice?

In composer.json, I have
"autoload": {
    "psr-0": {
                "Slim": "vendor/slim/slim"
            }
}

**Comment by itsgoingd** [comment]
Hey, you should follow this guide to install Slim http://docs.slimframework.com/#Installation, no need to specify the autoload section by yourself.
