### ISSUE TITLE
clockwork is ignoring environmental configs

### ISSUE THREAD

**Issue by InstanceOfMichael** [itsgoingd/clockwork#92]
Using Laravel 4.2:

It seems like ``app/config/packages/itsgoingd/clockwork/clockwork.php`` is used, but ``app/config/:environment_name/packages/itsgoingd/clockwork/clockwork.php`` is ignored.

Is there a way to manually enable this?

**Comment by itsgoingd** [comment]
The correct path is "app/config/packages/itsgoingd/clockwork/:environment_name/clockwork.php".

**Comment by InstanceOfMichael** [comment]
Ok, that worked instantly, thank you :+1:
