### ISSUE TITLE
Any way to add the middleware based on the environment with Laravel 5?

### ISSUE THREAD

**Issue by EspadaV8** [itsgoingd/clockwork#93]
Currently the only way to add the middleware is in the protected array within Kernel.php, however, for production I don't want Clockwork installed (saved to --dev).

Is there any way that the middleware can only been added based on the environment variable?

**Comment by EspadaV8** [comment]
Answering my own question.

I've found that you can check env('APP_ENV') within the Kernel class despite the fact that DetectEnvironment bootstrap class hasn't been run yet.

```php
    /**
     * Create a new HTTP kernel instance.
     *
     * @param  Application $app
     * @param  Router      $router
     */
    public function __construct(Application $app, Router $router)
    {
        if (env('APP_ENV', 'production') === 'local') {
            $this->prependMiddleware('Clockwork\Support\Laravel\ClockworkMiddleware');
        }

        parent::__construct($app, $router);
    }
```

**Comment by rsdev000** [comment]
Hi

I was looking for this too. 
Unfortunately your solution does not work for me.  env('APP_ENV') returns 'production' despite the setting in the .env file.
I have APP_ENV=local and APP_DEBUG=true in the .env file.

What could be the problem?

Thanks in advance

**Comment by zhuzhichao** [comment]
@rsdev000  I have the same problem.

**Comment by itsgoingd** [comment]
Hey, I've never needed to do this myself, but if you don't even install Clockwork for non-dev environments, maybe you could change the condition to simply check for the existence of the class?

I personally have Clockwork installed even in production where it is automatically disabled (based on app.debug being set to false) and has pretty much zero performance impact.

**Comment by zhuzhichao** [comment]
@itsgoingd Hi

I have moved "itsgoingd/clockwork": "~1.7" from "require-dev" to "require" in composer.json file. Because the dev environment can't find some class from "clockwork".

It works well, when I turn on/off debug. Thank you.

**Comment by cruzaljon1990** [comment]
> Hi
> 
> I was looking for this too. Unfortunately your solution does not work for me. env('APP_ENV') returns null despite the setting in the .env file. So env('APP_ENV', 'production') === 'local' is always 'production' . I have APP_ENV=local and APP_DEBUG=true in the .env file.
> 
> What could be the problem? Do you have APP_ENV defined in nginx / apache ?
> 
> Thanks in advance

The parent constructor should go first.

```
    /**
     * Create a new HTTP kernel instance.
     *
     * @param  Application $app
     * @param  Router      $router
     */
    public function __construct(Application $app, Router $router)
    {
        parent::__construct($app, $router);

        if (env('APP_ENV', 'production') === 'local') {
            $this->prependMiddleware('Clockwork\Support\Laravel\ClockworkMiddleware');
        }
    }
```
