### ISSUE TITLE
Display Queries from API

### ISSUE THREAD

**Issue by cbakker86** [itsgoingd/clockwork#94]
Hi,

First I want to thank you for this great library. I really like debugging in my Chrome dev with Clockwork.

I have a lot of different laravel 4.2 instances/applications. One instance is the API, handling all Queries with Eloquent. Every other Application talks with the API through REST with the guzzle http client. I already have https://github.com/hannesvdvreken/guzzle-clockwork implemented as well.

Q: Is it possible to display the queries + run time from the API in the Clockwork toolbar in Chrome through one of the other applications? I have already seen how you can implement Clockwork in Postman, wich is great, but since we are doing Multiple API calls (5-10) in 1 page load / ajax request, it seems much better to integrate everything in the front-end.
If this is not yet possible, how would you approach this challenge?

Thanks for your time.

Chris

**Comment by itsgoingd** [comment]
Hey,

Unfortunately I can see no way this can be done out of the box without modifying your own code. A possible solution could be modifying your API client code to capture the Clockwork headers from the API calls, fetch the Clockwork metadata from the API server based on the header values and save it as log messages or timeline entries to the frontend app Clockwork instance. (I can provide more details on a possible implementation if you are interested.)

Simpler alternative would be to use the [Clockwork CLI client](https://github.com/ptrofimov/clockwork-cli) on the API server which shows all received HTTP requests. If you would rather use a web based UI, [Clockwork Web](https://github.com/itsgoingd/clockwork-web) could be easily modified to work in similar fashion.

its
