### ISSUE TITLE
FileViewFinder issue

### ISSUE THREAD

**Issue by apps4u** [itsgoingd/clockwork#96]
HI , I used to use LaravelPhpDebugbar package but I ran into a issue where packages that had namespaced view would not work when that package had View monitoring set to true in it config . So I could only use if I did collect data on views. 

So I moved to your package as I was told it better which I found to be true when used with the Chrome extension . But It seems to run into the same issue so then I have this package installed I run into the same issue . For example I got a media package that can email the media file but when I try to do that I get a error saying the view hint path can not be found. 

Now when I first got this issue using PHPDebug bar I spent a week trying to find a  bug in the package before we worked out it was the Debugbar package. So Im 100% sure its not the media package Im using . 

What seems to happen is if I have any package like this that monitors views and you try to access a view that is in a package namespace then the Laravel FileViewFinder for some reason has a empty $hints property which should contain a array of view namespaces . 
\

**Comment by itsgoingd** [comment]
Hey, can you give me some example package that is known to break and/or some example code to reproduce this issue?

**Comment by apps4u** [comment]
Cartalyst/Media its in the Cartalyst packages which cost money to access but I can give you the package if you want to reproduce the issue. 

Jason Kristian | Director | Apps 4 U Pty Ltd.
ph: +61 075699 8109
mob: +61 0411 389 392
e: Jason Kristian <mailto:jasonk@apps4u.com.au>

**Comment by apps4u** [comment]
you can also just create a Laravel package with a service provider that loads some view that re in a namespace that all its needs you can event do that with out a package.
Jason Kristian | Director | Apps 4 U Pty Ltd.
ph: +61 075699 8109
mob: +61 0411 389 392
e: Jason Kristian <mailto:jasonk@apps4u.com.au>

**Comment by itsgoingd** [comment]
Hey, I haven't been able to replicate this, using this code in my controller:

```php
View::addNamespace('foo', base_path('resources/views/foo'));
return View::make('foo::hello');
```

View renders and appears in Clockwork as expected (running latest Laravel 5.0 and Clockwork).
